#!/usr/bin/env python3
"""Generate encblob.S for the aarch64 EL1 reachability probe.

Rows listed in skip.txt are omitted: at EL1 an encoding really can wedge the
machine (a WFI with interrupts masked, a write to SCTLR_EL1), and the row that
did it is named by the last hex the probe printed before running it.

Author: Maccoy Merrell.
"""
import os
import sys

src = sys.argv[1] if len(sys.argv) > 1 else 'reach_in.hex'
hexes = [h.strip() for h in open(src) if h.strip()]
skip = set(open('skip.txt').read().split()) if os.path.exists('skip.txt') else set()
sel = [h for h in hexes if h not in skip]
with open('encblob.S', 'w') as f:
    f.write('/* GENERATED by sysreach_mkblob.py -- do not edit */\n'
            '    .section .rodata\n    .align 16\n    .globl enc_blob\n'
            'enc_blob:\n')
    for h in sel:
        b = [h[i:i + 2] for i in range(0, len(h), 2)]
        assert len(b) == 4, h
        # length, three pad bytes, then the encoding WORD at offset 4.  With
        # the MMU off the probe's data accesses are Device-nGnRnE and a word
        # load from an odd offset takes an alignment fault, so the encoding
        # may not sit at offset 1.
        f.write('    .byte %d,0,0,0' % len(b) + ''.join(',0x%s' % x for x in b) +
                ',0' * 8 + '\n')
    f.write('    .globl enc_count\n    .align 8\nenc_count: .quad %d\n' % len(sel))
sys.stderr.write('blob rows %d, skipped %d\n' % (len(sel), len(skip)))
