PIN_ROOT ?= /mnt/md0/PIN/pin-external-4.2-99776-g21d818fa2-gcc-linux
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TOOL_ROOTS := champsim_memop_pintool

include $(CONFIG_ROOT)/makefile.config
include $(TOOLS_ROOT)/Config/makefile.default.rules
