"""
Generate the mipsel EXECUTION probes for the gem5 cross-check.

Same construction rule as the aarch64 set: static ``-nostdlib`` non-PIE ELFs
whose data lives in a fixed-address ``.data`` arena, so that an effective
address is a link-time fact both simulators must agree on rather than a
property of how each one lays out a process.

``.set noreorder`` is on throughout: MIPS branch delay slots are written out
explicitly, because a delay slot the assembler filled is an instruction the
comparison would have to explain and nobody wrote.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CC = 'mipsel-linux-gnu-gcc'

HEAD = """\
// GENERATED by mkprobes_mipsel.py -- ARC 3 mipsel execution probe
.set noreorder
.set noat
.section .data
.balign 64
.globl arena
arena:
"""

TAIL = """
.globl done
done:
  li   $v0, 4001
  li   $a0, 0
  syscall
  nop
"""

PRO = """
.section .text
.globl _start
_start:
  lui  $s0, %hi(arena)
  addiu $s0, $s0, %lo(arena)
"""


def arena(n=128, seed=0x1234):
    out, v = [], seed
    for _ in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .word 0x%08x' % (v & 0xffffffff))
    return '\n'.join(out) + '\n'


PROBES = {}

PROBES['p_int'] = """
  li   $t0, 0x12345678
  li   $t1, 0x76543210
  addu $t2, $t0, $t1
  subu $t3, $t0, $t1
  and  $t4, $t0, $t1
  or   $t5, $t0, $t1
  xor  $t6, $t0, $t1
  nor  $t7, $t0, $t1
  sll  $t8, $t0, 7
  srl  $t9, $t0, 7
  sra  $s1, $t0, 7
  sllv $s2, $t0, $t1
  srlv $s3, $t0, $t1
  slt  $s4, $t0, $t1
  sltu $s5, $t0, $t1
  slti $s6, $t0, 100
  addiu $s7, $t0, 100
  andi $t0, $t0, 0xff00
  ori  $t1, $t1, 0x00ff
  xori $t2, $t2, 0x0f0f
  lui  $t3, 0xabcd
  mult $t0, $t1
  mfhi $t4
  mflo $t5
  multu $t0, $t1
  mthi $t4
  mtlo $t5
  div  $zero, $t0, $t1
  mflo $t6
  mfhi $t7
  divu $zero, $t0, $t1
  mflo $t8
  clz  $t9, $t0
  clo  $s1, $t0
  seb  $s2, $t0
  seh  $s3, $t0
  wsbh $s4, $t0
  rotr $s5, $t0, 5
  ext  $s6, $t0, 4, 12
  ins  $s7, $t0, 4, 12
  movz $t0, $t1, $zero
  movn $t1, $t0, $t2
  mul  $t2, $t0, $t1
  madd $t0, $t1
  msub $t0, $t1
"""

PROBES['p_mem'] = """
  lw   $t0, 0($s0)
  lw   $t1, 4($s0)
  lb   $t2, 8($s0)
  lbu  $t3, 9($s0)
  lh   $t4, 10($s0)
  lhu  $t5, 12($s0)
  lwl  $t6, 3($s0)
  lwr  $t6, 0($s0)
  sw   $t0, 256($s0)
  sb   $t2, 260($s0)
  sh   $t4, 262($s0)
  swl  $t0, 267($s0)
  swr  $t0, 264($s0)
  lw   $t7, 16($s0)
  sw   $t7, 272($s0)
  ll   $t8, 288($s0)
  addiu $t8, $t8, 1
  sc   $t8, 288($s0)
  lw   $t9, 288($s0)
  pref 0, 320($s0)
  pref 1, 384($s0)
  synci 0($s0)
  sync
  lw   $s1, 20($s0)
  sw   $s1, 292($s0)
"""

PROBES['p_fp'] = """
  lwc1 $f0, 0($s0)
  lwc1 $f2, 4($s0)
  ldc1 $f4, 8($s0)
  ldc1 $f6, 16($s0)
  add.s $f8, $f0, $f2
  sub.s $f10, $f0, $f2
  mul.s $f12, $f0, $f2
  div.s $f14, $f0, $f2
  add.d $f16, $f4, $f6
  mul.d $f18, $f4, $f6
  abs.s $f20, $f0
  neg.s $f22, $f0
  sqrt.s $f24, $f20
  cvt.w.s $f30, $f0
  mov.s $f20, $f0
  mfc1 $t0, $f0
  mtc1 $t0, $f2
  cfc1 $t1, $31
  swc1 $f8, 256($s0)
  sdc1 $f16, 264($s0)
  c.eq.s $f0, $f2
  c.lt.s $f0, $f2
"""


PROBES['p_flow'] = """
  li   $t0, 0
  li   $t1, 4
lloop:
  addiu $t0, $t0, 1
  bne  $t0, $t1, lloop
  nop
  beq  $t0, $t1, l1
  nop
  nop
l1:
  bgez $t0, l2
  nop
l2:
  bltz $t0, l3
  nop
l3:
  blez $zero, l4
  nop
l4:
  bgtz $t0, l5
  nop
l5:
  jal  sub1
  nop
  b    after
  nop
sub1:
  addu $t2, $t0, $t1
  jr   $ra
  nop
after:
  la   $t3, after2
  jr   $t3
  nop
after2:
  nop
"""


def build(outdir):
    os.makedirs(outdir, exist_ok=True)
    made, failed = [], []
    for name, body in PROBES.items():
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD + arena() + PRO + body + TAIL)
        elf = os.path.join(outdir, name)
        cmd = [CC, '-EL', '-nostdlib', '-nostartfiles', '-static',
               '-no-pie', '-mno-abicalls', '-fno-pic', '-march=mips32r2',
               '-Wl,--build-id=none', '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            failed.append((name, p.stdout.decode('utf-8', 'replace')))
        else:
            made.append(elf)
    return made, failed


if __name__ == '__main__':
    made, failed = build(sys.argv[1] if len(sys.argv) > 1
                         else os.path.join(HERE, 'mipsel'))
    for n, err in failed:
        sys.stderr.write('FAILED %s\n%s\n' % (n, err))
    print('\n'.join(made))
    sys.exit(1 if failed else 0)
