"""
Generate the aarch64 EXECUTION probes for the gem5 cross-check.

Every probe is a static ``-nostdlib`` non-PIE ELF whose data lives in a
``.data`` arena at a FIXED virtual address.  That is the whole trick that makes
an address comparison between two different simulators meaningful: the stack,
the auxv and the environment are laid out differently by gem5's SE-mode process
loader and by qemu-user, so any address derived from SP differs between the two
runs for reasons that have nothing to do with either tool's correctness.  An
address derived from a link-time symbol does not.  The probes therefore touch
the arena and never the stack.

The vocabulary is chosen against the OPEN rows of the aarch64 memop table, not
for breadth: the 738 UNACCOUNTED count rows are ``ld2``/``ld3``/``ld4``,
``ldp``/``stp`` and the ``ld1``/``st1`` multi-register forms, so those are here
in strength.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CC = 'aarch64-linux-gnu-gcc'

HEAD = """\
// GENERATED by mkprobes_aarch64.py -- ARC 3 aarch64 execution probe
.section .data
.balign 64
.globl arena
arena:
"""

TAIL = """
.globl done
done:
  mov  x8, #93
  mov  x0, #0
  svc  #0
"""

PRO = """
.section .text
.globl _start
_start:
  adrp x20, arena
  add  x20, x20, :lo12:arena
"""


def arena(n=128, seed=0x1234):
    out, v = [], seed
    for _ in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .quad 0x%016x' % v)
    return '\n'.join(out) + '\n'


PROBES = {}

PROBES['p_int'] = """
  mov  x0, #0x1234
  movk x0, #0x89ab, lsl #16
  movk x0, #0xdef0, lsl #32
  movk x0, #0x0123, lsl #48
  mov  x1, #0x4321
  movk x1, #0x8765, lsl #16
  add  x2, x0, x1
  sub  x3, x0, x1
  and  x4, x0, x1
  orr  x5, x0, x1
  eor  x6, x0, x1
  lsl  x7, x0, #7
  lsr  x8, x0, #7
  asr  x9, x0, #7
  ror  x10, x0, #7
  mul  x11, x0, x1
  umulh x12, x0, x1
  smulh x13, x0, x1
  madd x14, x0, x1, x2
  msub x15, x0, x1, x2
  udiv x16, x0, x1
  sdiv x17, x0, x1
  rev  x18, x0
  rev16 x19, x0
  clz  x21, x0
  rbit x22, x0
  sxtb x23, w0
  sxth x24, w0
  sxtw x25, w0
  ubfx x26, x0, #4, #12
  sbfx x27, x0, #4, #12
  bfi  x28, x0, #8, #16
  adds x2, x0, x1
  adc  x3, x0, x1
  subs x4, x0, x1
  sbc  x5, x0, x1
  cmp  x0, x1
  cset x6, gt
  csinc x7, x0, x1, ne
  extr x8, x0, x1, #13
  add  w9, w0, w1
  sub  w10, w0, w1
  neg  x11, x0
  mvn  x12, x0
  bic  x13, x0, x1
  orn  x14, x0, x1
  eon  x15, x0, x1
"""

PROBES['p_mem'] = """
  ldr  x0, [x20]
  ldr  x1, [x20, #8]
  ldr  w2, [x20, #16]
  ldrb w3, [x20, #17]
  ldrh w4, [x20, #18]
  ldrsb x5, [x20, #19]
  ldrsh x6, [x20, #20]
  ldrsw x7, [x20, #24]
  ldur x8, [x20, #3]
  ldur w9, [x20, #5]
  str  x0, [x20, #256]
  str  w2, [x20, #264]
  strb w3, [x20, #268]
  strh w4, [x20, #270]
  stur x1, [x20, #195]
  add  x10, x20, #512
  ldr  x11, [x10], #8
  ldr  x12, [x10, #8]!
  str  x11, [x10], #8
  str  x12, [x10, #8]!
  mov  x13, #32
  ldr  x14, [x20, x13]
  ldr  x15, [x20, x13, lsl #0]
  ldr  w16, [x20, w13, uxtw #2]
  str  x14, [x20, x13]
  ldp  x0, x1, [x20, #64]
  ldp  w2, w3, [x20, #80]
  stp  x0, x1, [x20, #320]
  stp  w2, w3, [x20, #248]
  ldpsw x4, x5, [x20, #88]
  ldp  x6, x7, [x20, #96]!
  ldp  x8, x9, [x20], #16
  ldr  x0, [x20, #0]
"""

PROBES['p_simd'] = """
  ldr  q0, [x20]
  ldr  d1, [x20, #16]
  ldr  s2, [x20, #24]
  ldr  h3, [x20, #28]
  ldr  b4, [x20, #30]
  str  q0, [x20, #256]
  str  d1, [x20, #272]
  str  s2, [x20, #280]
  add  x21, x20, #384
  ld1  {v5.16b}, [x21]
  ld1  {v6.16b, v7.16b}, [x21]
  ld1  {v8.16b, v9.16b, v10.16b}, [x21]
  ld1  {v11.16b, v12.16b, v13.16b, v14.16b}, [x21]
  ld2  {v15.16b, v16.16b}, [x21]
  ld3  {v17.16b, v18.16b, v19.16b}, [x21]
  ld4  {v20.16b, v21.16b, v22.16b, v23.16b}, [x21]
  add  x22, x20, #640
  st1  {v5.16b}, [x22]
  st1  {v6.16b, v7.16b}, [x22]
  st2  {v15.16b, v16.16b}, [x22]
  st3  {v17.16b, v18.16b, v19.16b}, [x22]
  st4  {v20.16b, v21.16b, v22.16b, v23.16b}, [x22]
  ld1r {v24.16b}, [x21]
  ld1  {v25.b}[3], [x21]
  st1  {v25.b}[3], [x22]
  ldp  q26, q27, [x20, #128]
  stp  q26, q27, [x22, #64]
  add  v28.16b, v5.16b, v6.16b
  addv b29, v5.16b
  umov w0, v5.b[2]
  ins  v30.b[1], w0
  dup  v31.16b, w0
"""

PROBES['p_atomic'] = """
  add  x21, x20, #768
  mov  x1, #0x55
  str  x1, [x21]
  ldxr x2, [x21]
  add  x2, x2, #1
  stxr w3, x2, [x21]
  ldaxr x4, [x21]
  add  x4, x4, #1
  stlxr w5, x4, [x21]
  ldar x6, [x21]
  stlr x6, [x21]
  ldxrb w7, [x21]
  stxrb w8, w7, [x21]
  ldxrh w9, [x21]
  stxrh w10, w9, [x21]
  mov  x11, #0x56
  mov  x12, #0x99
  cas  x11, x12, [x21]
  casa x11, x12, [x21]
  casl x11, x12, [x21]
  casal x11, x12, [x21]
  swp  x12, x13, [x21]
  ldadd x12, x14, [x21]
  ldclr x12, x15, [x21]
  ldset x12, x16, [x21]
  ldeor x12, x17, [x21]
  ldsmax x12, x18, [x21]
  ldumin x12, x19, [x21]
  stadd x12, [x21]
"""

PROBES['p_fp'] = """
  ldr  d0, [x20]
  ldr  d1, [x20, #8]
  ldr  s2, [x20, #16]
  fmov d3, d0
  fmov x0, d0
  fmov d4, x0
  fadd d5, d0, d1
  fsub d6, d0, d1
  fmul d7, d0, d1
  fdiv d8, d0, d1
  fabs d9, d0
  fneg d10, d0
  fsqrt d11, d9
  fmadd d12, d0, d1, d5
  fcvt s13, d0
  fcvt d14, s13
  fcvtzs x1, d0
  fcvtzu x2, d9
  scvtf d15, x1
  ucvtf d16, x2
  frinta d17, d0
  fcmp d0, d1
  fcsel d18, d0, d1, gt
  fmax d19, d0, d1
  fmin d20, d0, d1
  str  d5, [x20, #256]
  str  s13, [x20, #264]
  mrs  x3, fpcr
  msr  fpcr, x3
  mrs  x4, fpsr
"""

PROBES['p_flow'] = """
  mov  x0, #0
  mov  x1, #4
lloop:
  add  x0, x0, #1
  cmp  x0, x1
  b.lt lloop
  cbz  x0, skip1
  mov  x2, #1
skip1:
  cbnz x0, skip2
  mov  x3, #2
skip2:
  tbz  x0, #0, skip3
  mov  x4, #3
skip3:
  tbnz x0, #2, skip4
  mov  x5, #4
skip4:
  bl   sub1
  adr  x6, skip5
  br   x6
skip5:
  ccmp x0, x1, #0, eq
  csel x7, x0, x1, eq
  csinv x8, x0, x1, ne
  csneg x9, x0, x1, ne
  cneg x10, x0, ne
  b    after
sub1:
  add  x11, x0, x1
  ret
after:
  nop
"""

PROBES['p_hint'] = """
  add  x21, x20, #896
  prfm pldl1keep, [x21]
  prfm pstl1keep, [x21, #64]
  prfum pldl1keep, [x21, #3]
  nop
  yield
  isb
  dsb sy
  dmb sy
  mrs  x1, ctr_el0
  mrs  x2, dczid_el0
  mrs  x3, tpidr_el0
  msr  tpidr_el0, x3
  mrs  x4, cntvct_el0
"""


PROBES['p_cache'] = """
  add  x21, x20, #896
  dc   cvau, x21
  dc   civac, x21
  dc   cvac, x21
  ic   ivau, x21
  dc   zva, x21
  nop
"""


def build(outdir):
    os.makedirs(outdir, exist_ok=True)
    made, failed = [], []
    for name, body in PROBES.items():
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD + arena() + PRO + body + TAIL)
        elf = os.path.join(outdir, name)
        cmd = [CC, '-nostdlib', '-nostartfiles', '-static', '-no-pie',
               '-Wl,--build-id=none', '-march=armv8.4-a+lse+crc',
               '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            failed.append((name, p.stdout.decode('utf-8', 'replace')))
        else:
            made.append(elf)
    return made, failed


if __name__ == '__main__':
    made, failed = build(sys.argv[1] if len(sys.argv) > 1
                         else os.path.join(HERE, 'aarch64'))
    for n, err in failed:
        sys.stderr.write('FAILED %s\n%s\n' % (n, err))
    print('\n'.join(made))
    sys.exit(1 if failed else 0)
