"""
Generate the x86_64 EXECUTION probes for the gem5 correct-path cross-check.

Same construction rule as the aarch64 and mipsel sets, and for the same
reason: gem5's SE-mode process loader and qemu-user lay out the stack, the
auxiliary vector and the environment differently, so any address derived from
the INHERITED stack pointer differs between the two runs for reasons that have
nothing to do with either tool.  Every probe is therefore a static
``-nostdlib`` non-PIE ELF that works out of a fixed-address ``.data`` arena.

WHAT IS DIFFERENT ON x86-64, AND WHY IT IS NOT A LOOPHOLE
=========================================================
The other two sets simply never touch the stack.  Doing that here would delete
``push``/``pop``/``call``/``ret`` -- an eighth of the ISA's dynamic footprint
and the only forms that make an implicit memory access -- from a leg whose
whole purpose is the memop axes.  So the prologue INSTALLS the stack pointer
at a link-time address inside the arena::

    movq $stk, %rsp

After that every stack address is a link-time fact both simulators must agree
on, exactly like every other address in the probe, and the implicit-access
forms are IN the comparison rather than excluded from it.  The inherited
pointer is overwritten before it is ever read, so nothing about either
loader's layout reaches an axis.

The probes end with ``exit`` (``$60``) rather than ``exit_group``: both
simulators implement both, and one syscall number keeps the last aligned
instruction the same across the set.  gem5 SE mode does not retire ``syscall``
into its instruction trace at all -- measured, the log ends at the instruction
BEFORE it -- so every guest contributes exactly one TRC-ONLY instruction and
the leg says so rather than absorbing it.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CC = 'gcc'

HEAD = """\
// GENERATED by mkprobes_x86_64.py -- ARC 3 x86_64 execution probe
.section .data
.balign 64
.globl arena
arena:
"""

#: the fixed stack, in the arena, so that every implicit stack access has a
#: link-time address.  512 bytes of guard below `stk` keeps a deep push
#: sequence inside the object it was linked into.
MID = """
.balign 64
.globl stkbase
stkbase:
  .fill 1024, 1, 0
.globl stk
stk:
  .fill 64, 1, 0
.balign 64
.globl scratch
scratch:
  .fill 512, 1, 0
"""

PRO = """
.section .text
.globl _start
_start:
  movq $stk, %rsp
  movq $arena, %r15
  movq $scratch, %r14
"""

TAIL = """
.globl done
done:
  movl $60, %eax
  xorl %edi, %edi
  syscall
"""


def arena(n=64, seed=0x1234):
    """A deterministic arena.  The bytes are a link-time fact, so both
    simulators read the same operand values and a value axis compares
    something other than zero."""
    out, v = [], seed
    for _ in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .quad 0x%016x' % v)
    return '\n'.join(out) + '\n'


PROBES = {}

#: INTEGER.  ALU, shifts, the multiply/divide plumbing, the conditional moves
#: and the byte-width writes R7.1 turns on.
PROBES['p_int'] = """
  movq $0x1234567890abcdef, %rax
  movq $0x0fedcba987654321, %rbx
  addq %rbx, %rax
  subq %rbx, %rax
  andq %rbx, %rax
  orq  %rbx, %rax
  xorq %rbx, %rax
  addl $0x1234, %eax
  subl $0x99, %ebx
  incq %rcx
  decq %rcx
  negq %rbx
  notq %rbx
  shlq $7, %rax
  shrq $3, %rax
  sarq $2, %rax
  movl $9, %ecx
  shlq %cl, %rbx
  rolq $5, %rax
  rorq $9, %rbx
  movq %rax, %rdx
  imulq %rbx, %rdx
  movq $17, %rsi
  xorq %rdx, %rdx
  movq $0x123456789, %rax
  divq %rsi
  movq $0x7fffffff, %rax
  cqto
  idivq %rsi
  cmpq %rbx, %rax
  cmovlq %rbx, %rax
  cmovgeq %rsi, %rbx
  testq %rax, %rax
  setz  %al
  setnz %bl
  sets  %r8b
  movzbq %al, %rcx
  movsbq %bl, %rdx
  movzwl %ax, %r9d
  movswq %bx, %r10
  movl  %eax, %r11d
  bswapq %rax
  bswapl %ecx
  btq   $9, %rax
  btsq  $10, %rax
  btrq  $11, %rax
  btcq  $12, %rax
  bsfq  %rax, %r12
  bsrq  %rax, %r13
  popcntq %rax, %rbx
  leaq  9(%r15,%rsi,4), %rdi
  xchgq %rax, %rbx
  adcq  %rbx, %rax
  sbbq  %rbx, %rax
  clc
  stc
  cmc
  cld
"""

#: MEMORY.  Every access width, both directions, sign- and zero-extending
#: loads, the read-modify-write forms and an unaligned pair.
PROBES['p_mem'] = """
  movq   (%r15), %rax
  movl   8(%r15), %ebx
  movw   16(%r15), %cx
  movb   18(%r15), %dl
  movzbq 19(%r15), %rsi
  movsbq 20(%r15), %rdi
  movzwq 22(%r15), %r8
  movswq 24(%r15), %r9
  movslq 28(%r15), %r10
  movq   %rax, 0(%r14)
  movl   %ebx, 8(%r14)
  movw   %cx,  12(%r14)
  movb   %dl,  14(%r14)
  movq   $0x11223344, 16(%r14)
  movl   $0x99aabbcc, 24(%r14)
  addq   %rax, 32(%r14)
  subl   %ebx, 40(%r14)
  incq   48(%r14)
  decl   56(%r14)
  andq   %rax, 64(%r14)
  orl    %ebx, 72(%r14)
  xorb   %dl,  80(%r14)
  movq   33(%r15), %r11
  movq   %r11, 88(%r14)
  xchgq  %rax, 96(%r14)
  cmpq   %rax, 104(%r14)
  negq   112(%r14)
  notl   120(%r14)
  shlq   $3, 128(%r14)
  leaq   200(%r14), %r12
  movq   (%r12), %r13
  prefetcht0 (%r15)
  prefetchnta 64(%r15)
"""

#: SSE.  Packed integer and floating point, aligned and unaligned 128-bit
#: accesses, the scalar forms that write only the low half of an XMM register,
#: and the two moves that cross the register-file boundary.
PROBES['p_simd'] = """
  movdqu (%r15), %xmm0
  movdqu 16(%r15), %xmm1
  movdqa 32(%r15), %xmm2
  movaps 48(%r15), %xmm3
  movups 65(%r15), %xmm4
  paddd  %xmm1, %xmm0
  psubd  %xmm1, %xmm0
  paddb  %xmm2, %xmm1
  paddw  %xmm2, %xmm1
  paddq  %xmm3, %xmm2
  pand   %xmm1, %xmm0
  por    %xmm2, %xmm0
  pxor   %xmm3, %xmm0
  pcmpeqd %xmm1, %xmm1
  psllq  $4, %xmm0
  psrlq  $2, %xmm0
  punpcklqdq %xmm1, %xmm0
  punpckhqdq %xmm2, %xmm1
  pshufd $0x1b, %xmm0, %xmm5
  addps  %xmm1, %xmm3
  mulps  %xmm1, %xmm3
  subps  %xmm2, %xmm3
  addpd  %xmm2, %xmm4
  mulpd  %xmm2, %xmm4
  andps  %xmm0, %xmm3
  xorps  %xmm3, %xmm3
  movsd  (%r15), %xmm6
  movss  8(%r15), %xmm7
  addsd  %xmm6, %xmm6
  mulss  %xmm7, %xmm7
  cvtsi2sdq %rax, %xmm8
  cvttsd2si %xmm6, %rbx
  movq   %rax, %xmm9
  movq   %xmm9, %rcx
  movd   %eax, %xmm10
  movd   %xmm10, %edx
  movdqu %xmm0, 0(%r14)
  movdqa %xmm1, 16(%r14)
  movaps %xmm2, 32(%r14)
  movups %xmm3, 49(%r14)
  movsd  %xmm6, 80(%r14)
  movss  %xmm7, 88(%r14)
  stmxcsr 96(%r14)
  ldmxcsr 96(%r14)
"""

#: x87.  The stack pushes and pops that move TOP, the arithmetic that writes
#: the status word, and the control-word transfers.
#:
#: THE ORDER IS LOAD-BEARING.  gem5 does not implement `fwait`, `fninit`,
#: `fsqrt`, `ffree`, `fincstp` or `fdecstp`: it warns once and retires them
#: with NO effects.  An unimplemented instruction in the MIDDLE of an x87
#: chain leaves the two machines with different stacks and different TOPs from
#: that point on, so every later x87 value disagrees for a reason that has
#: nothing to do with the instruction it is charged to -- which is what the
#: first version of this probe did, and it produced x87 store-data rows that
#: looked like tracer defects and were the probe's own.
#:
#: They are therefore in a TRAILING section, after everything that depends on
#: x87 state, where they still exercise the axes (each one names a destination
#: the reference does not) and can poison nothing.  `finit` is absent
#: altogether: both simulators start a process with the x87 unit already in
#: its initialised state, so the instruction bought nothing and cost the
#: whole chain.
PROBES['p_x87'] = """
  flds   (%r15)
  flds   4(%r15)
  fldl   8(%r15)
  fadds  16(%r15)
  fmuls  20(%r15)
  faddp  %st(0), %st(1)
  fld    %st(0)
  fabs
  fchs
  fld1
  fldz
  fldpi
  faddp  %st(0), %st(1)
  fxch   %st(1)
  fsubp  %st(0), %st(1)
  fstps  0(%r14)
  fstpl  8(%r14)
  fnstcw 16(%r14)
  fldcw  16(%r14)
  fnstsw %ax
  fnstsw 20(%r14)
  fstpl  24(%r14)
  fstpl  32(%r14)
// -------- from here on the reference does not model the instruction --------
  fsqrt
  ffree  %st(1)
  fincstp
  fdecstp
  fwait
"""

#: CONTROL FLOW.  A taken and a not-taken conditional, a backward loop, a
#: direct call and its return, an indirect jump and an indirect call -- every
#: one of which makes an implicit stack access at a link-time address because
#: the prologue installed the stack pointer.
PROBES['p_flow'] = """
  movl $0, %ecx
  movl $5, %edx
lloop:
  incl %ecx
  cmpl %edx, %ecx
  jne  lloop
  je   ltaken
  nop
ltaken:
  jg   lnot
  nop
lnot:
  jmp  lfwd
  nop
lfwd:
  pushq %rax
  pushq %rbx
  popq  %rsi
  popq  %rdi
  call  sub1
  leaq  sub2(%rip), %r10
  jmp   *%r10
sub1:
  addq  %rcx, %rdx
  ret
sub2:
  leaq  sub3(%rip), %r11
  call  *%r11
  jmp   after
sub3:
  xorq  %r8, %r8
  ret
after:
  pushfq
  popq  %r9
  nop
"""

#: ATOMICS AND THE READ-MODIFY-WRITE FORMS gem5 lowers through `ldstl`/`stul`.
PROBES['p_atomic'] = """
  movq $0x1111, 0(%r14)
  movq $0x2222, 8(%r14)
  movl $0x33, 16(%r14)
  lock incq 0(%r14)
  lock decq 0(%r14)
  lock addq %rax, 8(%r14)
  lock subl %ebx, 16(%r14)
  lock andq %rax, 8(%r14)
  lock orl  %ebx, 16(%r14)
  lock xorq %rax, 8(%r14)
  movq $1, %rbx
  lock xaddq %rbx, 0(%r14)
  movq 0(%r14), %rax
  movq $99, %rbx
  lock cmpxchgq %rbx, 0(%r14)
  movq $0xdead, %rcx
  xchgq %rcx, 8(%r14)
  lock btsq $3, 24(%r14)
  lock btrq $4, 24(%r14)
  mfence
  lfence
  sfence
"""


def build(outdir):
    os.makedirs(outdir, exist_ok=True)
    made, failed = [], []
    for name, body in PROBES.items():
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD + arena() + MID + PRO + body + TAIL)
        elf = os.path.join(outdir, name)
        cmd = [CC, '-nostdlib', '-nostartfiles', '-static', '-no-pie',
               '-Wl,--build-id=none', '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            failed.append((name, p.stdout.decode('utf-8', 'replace')))
        else:
            made.append(elf)
    return made, failed


if __name__ == '__main__':
    made, failed = build(sys.argv[1] if len(sys.argv) > 1
                         else os.path.join(HERE, 'x86_64'))
    for n, err in failed:
        sys.stderr.write('FAILED %s\n%s\n' % (n, err))
    print('\n'.join(made))
    sys.exit(1 if failed else 0)
