#ifndef CHAMPSIM_TRACER_MNEMONICS_X86_H
#define CHAMPSIM_TRACER_MNEMONICS_X86_H

/*
 * ISA-specific classification tables for champsim_tracer — x86.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include <capstone/x86.h>

/* X86: 191/245 classified, 54 REG_NONE */
static const RegClassification x86_reg_class[X86_REG_ENDING] = {
    [X86_REG_AH] = { REG_GPR0 },  /* ah */
    [X86_REG_AL] = { REG_GPR0 },  /* al */
    [X86_REG_AX] = { REG_GPR0 },  /* ax */
    [X86_REG_BH] = { REG_GPR3 },  /* bh */
    [X86_REG_BL] = { REG_GPR3 },  /* bl */
    [X86_REG_BP] = { REG_FP_REG },  /* bp */
    [X86_REG_BPL] = { REG_FP_REG },  /* bpl */
    [X86_REG_BX] = { REG_GPR3 },  /* bx */
    [X86_REG_CH] = { REG_GPR1 },  /* ch */
    [X86_REG_CL] = { REG_GPR1 },  /* cl */
    [X86_REG_CX] = { REG_GPR1 },  /* cx */
    [X86_REG_DH] = { REG_GPR2 },  /* dh */
    [X86_REG_DI] = { REG_GPR5 },  /* di */
    [X86_REG_DIL] = { REG_GPR5 },  /* dil */
    [X86_REG_DL] = { REG_GPR2 },  /* dl */
    [X86_REG_DX] = { REG_GPR2 },  /* dx */
    [X86_REG_EAX] = { REG_GPR0 },  /* eax */
    [X86_REG_EBP] = { REG_FP_REG },  /* ebp */
    [X86_REG_EBX] = { REG_GPR3 },  /* ebx */
    [X86_REG_ECX] = { REG_GPR1 },  /* ecx */
    [X86_REG_EDI] = { REG_GPR5 },  /* edi */
    [X86_REG_EDX] = { REG_GPR2 },  /* edx */
    [X86_REG_EFLAGS] = { REG_FLAGS },  /* rflags */
    [X86_REG_EIP] = { REG_IP },  /* eip */
    [X86_REG_ESI] = { REG_GPR4 },  /* esi */
    [X86_REG_ESP] = { REG_SP },  /* esp */
    [X86_REG_RAX] = { REG_GPR0 },  /* rax */
    [X86_REG_RBP] = { REG_FP_REG },  /* rbp */
    [X86_REG_RBX] = { REG_GPR3 },  /* rbx */
    [X86_REG_RCX] = { REG_GPR1 },  /* rcx */
    [X86_REG_RDI] = { REG_GPR5 },  /* rdi */
    [X86_REG_RDX] = { REG_GPR2 },  /* rdx */
    [X86_REG_RIP] = { REG_IP },  /* rip */
    [X86_REG_RSI] = { REG_GPR4 },  /* rsi */
    [X86_REG_RSP] = { REG_SP },  /* rsp */
    [X86_REG_SI] = { REG_GPR4 },  /* si */
    [X86_REG_SIL] = { REG_GPR4 },  /* sil */
    [X86_REG_SP] = { REG_SP },  /* sp */
    [X86_REG_SPL] = { REG_SP },  /* spl */
    [X86_REG_FP0] = { REG_FPR0 },  /* fp0 */
    [X86_REG_FP1] = { REG_FPR1 },  /* fp1 */
    [X86_REG_FP2] = { REG_FPR2 },  /* fp2 */
    [X86_REG_FP3] = { REG_FPR3 },  /* fp3 */
    [X86_REG_FP4] = { REG_FPR4 },  /* fp4 */
    [X86_REG_FP5] = { REG_FPR5 },  /* fp5 */
    [X86_REG_FP6] = { REG_FPR6 },  /* fp6 */
    [X86_REG_FP7] = { REG_FPR7 },  /* fp7 */
    [X86_REG_MM0] = { REG_VEC0 },  /* mm0 */
    [X86_REG_MM1] = { REG_VEC1 },  /* mm1 */
    [X86_REG_MM2] = { REG_VEC2 },  /* mm2 */
    [X86_REG_MM3] = { REG_VEC3 },  /* mm3 */
    [X86_REG_MM4] = { REG_VEC4 },  /* mm4 */
    [X86_REG_MM5] = { REG_VEC5 },  /* mm5 */
    [X86_REG_MM6] = { REG_VEC6 },  /* mm6 */
    [X86_REG_MM7] = { REG_VEC7 },  /* mm7 */
    [X86_REG_R8] = { REG_GPR6 },  /* r8 */
    [X86_REG_R9] = { REG_GPR7 },  /* r9 */
    [X86_REG_R10] = { REG_GPR8 },  /* r10 */
    [X86_REG_R11] = { REG_GPR9 },  /* r11 */
    [X86_REG_R12] = { REG_GPR10 },  /* r12 */
    [X86_REG_R13] = { REG_GPR11 },  /* r13 */
    [X86_REG_R14] = { REG_GPR12 },  /* r14 */
    [X86_REG_R15] = { REG_GPR13 },  /* r15 */
    [X86_REG_ST0] = { REG_FPR0 },  /* st(0) */
    [X86_REG_ST1] = { REG_FPR1 },  /* st(1) */
    [X86_REG_ST2] = { REG_FPR2 },  /* st(2) */
    [X86_REG_ST3] = { REG_FPR3 },  /* st(3) */
    [X86_REG_ST4] = { REG_FPR4 },  /* st(4) */
    [X86_REG_ST5] = { REG_FPR5 },  /* st(5) */
    [X86_REG_ST6] = { REG_FPR6 },  /* st(6) */
    [X86_REG_ST7] = { REG_FPR7 },  /* st(7) */
    [X86_REG_XMM0] = { REG_VEC0 },  /* xmm0 */
    [X86_REG_XMM1] = { REG_VEC1 },  /* xmm1 */
    [X86_REG_XMM2] = { REG_VEC2 },  /* xmm2 */
    [X86_REG_XMM3] = { REG_VEC3 },  /* xmm3 */
    [X86_REG_XMM4] = { REG_VEC4 },  /* xmm4 */
    [X86_REG_XMM5] = { REG_VEC5 },  /* xmm5 */
    [X86_REG_XMM6] = { REG_VEC6 },  /* xmm6 */
    [X86_REG_XMM7] = { REG_VEC7 },  /* xmm7 */
    [X86_REG_XMM8] = { REG_VEC8 },  /* xmm8 */
    [X86_REG_XMM9] = { REG_VEC9 },  /* xmm9 */
    [X86_REG_XMM10] = { REG_VEC10 },  /* xmm10 */
    [X86_REG_XMM11] = { REG_VEC11 },  /* xmm11 */
    [X86_REG_XMM12] = { REG_VEC12 },  /* xmm12 */
    [X86_REG_XMM13] = { REG_VEC13 },  /* xmm13 */
    [X86_REG_XMM14] = { REG_VEC14 },  /* xmm14 */
    [X86_REG_XMM15] = { REG_VEC15 },  /* xmm15 */
    [X86_REG_XMM16] = { REG_VEC16 },  /* xmm16 */
    [X86_REG_XMM17] = { REG_VEC17 },  /* xmm17 */
    [X86_REG_XMM18] = { REG_VEC18 },  /* xmm18 */
    [X86_REG_XMM19] = { REG_VEC19 },  /* xmm19 */
    [X86_REG_XMM20] = { REG_VEC20 },  /* xmm20 */
    [X86_REG_XMM21] = { REG_VEC21 },  /* xmm21 */
    [X86_REG_XMM22] = { REG_VEC22 },  /* xmm22 */
    [X86_REG_XMM23] = { REG_VEC23 },  /* xmm23 */
    [X86_REG_XMM24] = { REG_VEC24 },  /* xmm24 */
    [X86_REG_XMM25] = { REG_VEC25 },  /* xmm25 */
    [X86_REG_XMM26] = { REG_VEC26 },  /* xmm26 */
    [X86_REG_XMM27] = { REG_VEC27 },  /* xmm27 */
    [X86_REG_XMM28] = { REG_VEC28 },  /* xmm28 */
    [X86_REG_XMM29] = { REG_VEC29 },  /* xmm29 */
    [X86_REG_XMM30] = { REG_VEC30 },  /* xmm30 */
    [X86_REG_XMM31] = { REG_VEC31 },  /* xmm31 */
    [X86_REG_YMM0] = { REG_VEC0 },  /* ymm0 */
    [X86_REG_YMM1] = { REG_VEC1 },  /* ymm1 */
    [X86_REG_YMM2] = { REG_VEC2 },  /* ymm2 */
    [X86_REG_YMM3] = { REG_VEC3 },  /* ymm3 */
    [X86_REG_YMM4] = { REG_VEC4 },  /* ymm4 */
    [X86_REG_YMM5] = { REG_VEC5 },  /* ymm5 */
    [X86_REG_YMM6] = { REG_VEC6 },  /* ymm6 */
    [X86_REG_YMM7] = { REG_VEC7 },  /* ymm7 */
    [X86_REG_YMM8] = { REG_VEC8 },  /* ymm8 */
    [X86_REG_YMM9] = { REG_VEC9 },  /* ymm9 */
    [X86_REG_YMM10] = { REG_VEC10 },  /* ymm10 */
    [X86_REG_YMM11] = { REG_VEC11 },  /* ymm11 */
    [X86_REG_YMM12] = { REG_VEC12 },  /* ymm12 */
    [X86_REG_YMM13] = { REG_VEC13 },  /* ymm13 */
    [X86_REG_YMM14] = { REG_VEC14 },  /* ymm14 */
    [X86_REG_YMM15] = { REG_VEC15 },  /* ymm15 */
    [X86_REG_YMM16] = { REG_VEC16 },  /* ymm16 */
    [X86_REG_YMM17] = { REG_VEC17 },  /* ymm17 */
    [X86_REG_YMM18] = { REG_VEC18 },  /* ymm18 */
    [X86_REG_YMM19] = { REG_VEC19 },  /* ymm19 */
    [X86_REG_YMM20] = { REG_VEC20 },  /* ymm20 */
    [X86_REG_YMM21] = { REG_VEC21 },  /* ymm21 */
    [X86_REG_YMM22] = { REG_VEC22 },  /* ymm22 */
    [X86_REG_YMM23] = { REG_VEC23 },  /* ymm23 */
    [X86_REG_YMM24] = { REG_VEC24 },  /* ymm24 */
    [X86_REG_YMM25] = { REG_VEC25 },  /* ymm25 */
    [X86_REG_YMM26] = { REG_VEC26 },  /* ymm26 */
    [X86_REG_YMM27] = { REG_VEC27 },  /* ymm27 */
    [X86_REG_YMM28] = { REG_VEC28 },  /* ymm28 */
    [X86_REG_YMM29] = { REG_VEC29 },  /* ymm29 */
    [X86_REG_YMM30] = { REG_VEC30 },  /* ymm30 */
    [X86_REG_YMM31] = { REG_VEC31 },  /* ymm31 */
    [X86_REG_ZMM0] = { REG_VEC0 },  /* zmm0 */
    [X86_REG_ZMM1] = { REG_VEC1 },  /* zmm1 */
    [X86_REG_ZMM2] = { REG_VEC2 },  /* zmm2 */
    [X86_REG_ZMM3] = { REG_VEC3 },  /* zmm3 */
    [X86_REG_ZMM4] = { REG_VEC4 },  /* zmm4 */
    [X86_REG_ZMM5] = { REG_VEC5 },  /* zmm5 */
    [X86_REG_ZMM6] = { REG_VEC6 },  /* zmm6 */
    [X86_REG_ZMM7] = { REG_VEC7 },  /* zmm7 */
    [X86_REG_ZMM8] = { REG_VEC8 },  /* zmm8 */
    [X86_REG_ZMM9] = { REG_VEC9 },  /* zmm9 */
    [X86_REG_ZMM10] = { REG_VEC10 },  /* zmm10 */
    [X86_REG_ZMM11] = { REG_VEC11 },  /* zmm11 */
    [X86_REG_ZMM12] = { REG_VEC12 },  /* zmm12 */
    [X86_REG_ZMM13] = { REG_VEC13 },  /* zmm13 */
    [X86_REG_ZMM14] = { REG_VEC14 },  /* zmm14 */
    [X86_REG_ZMM15] = { REG_VEC15 },  /* zmm15 */
    [X86_REG_ZMM16] = { REG_VEC16 },  /* zmm16 */
    [X86_REG_ZMM17] = { REG_VEC17 },  /* zmm17 */
    [X86_REG_ZMM18] = { REG_VEC18 },  /* zmm18 */
    [X86_REG_ZMM19] = { REG_VEC19 },  /* zmm19 */
    [X86_REG_ZMM20] = { REG_VEC20 },  /* zmm20 */
    [X86_REG_ZMM21] = { REG_VEC21 },  /* zmm21 */
    [X86_REG_ZMM22] = { REG_VEC22 },  /* zmm22 */
    [X86_REG_ZMM23] = { REG_VEC23 },  /* zmm23 */
    [X86_REG_ZMM24] = { REG_VEC24 },  /* zmm24 */
    [X86_REG_ZMM25] = { REG_VEC25 },  /* zmm25 */
    [X86_REG_ZMM26] = { REG_VEC26 },  /* zmm26 */
    [X86_REG_ZMM27] = { REG_VEC27 },  /* zmm27 */
    [X86_REG_ZMM28] = { REG_VEC28 },  /* zmm28 */
    [X86_REG_ZMM29] = { REG_VEC29 },  /* zmm29 */
    [X86_REG_ZMM30] = { REG_VEC30 },  /* zmm30 */
    [X86_REG_ZMM31] = { REG_VEC31 },  /* zmm31 */
    [X86_REG_R8B] = { REG_GPR6 },  /* r8b */
    [X86_REG_R9B] = { REG_GPR7 },  /* r9b */
    [X86_REG_R10B] = { REG_GPR8 },  /* r10b */
    [X86_REG_R11B] = { REG_GPR9 },  /* r11b */
    [X86_REG_R12B] = { REG_GPR10 },  /* r12b */
    [X86_REG_R13B] = { REG_GPR11 },  /* r13b */
    [X86_REG_R14B] = { REG_GPR12 },  /* r14b */
    [X86_REG_R15B] = { REG_GPR13 },  /* r15b */
    [X86_REG_R8D] = { REG_GPR6 },  /* r8d */
    [X86_REG_R9D] = { REG_GPR7 },  /* r9d */
    [X86_REG_R10D] = { REG_GPR8 },  /* r10d */
    [X86_REG_R11D] = { REG_GPR9 },  /* r11d */
    [X86_REG_R12D] = { REG_GPR10 },  /* r12d */
    [X86_REG_R13D] = { REG_GPR11 },  /* r13d */
    [X86_REG_R14D] = { REG_GPR12 },  /* r14d */
    [X86_REG_R15D] = { REG_GPR13 },  /* r15d */
    [X86_REG_R8W] = { REG_GPR6 },  /* r8w */
    [X86_REG_R9W] = { REG_GPR7 },  /* r9w */
    [X86_REG_R10W] = { REG_GPR8 },  /* r10w */
    [X86_REG_R11W] = { REG_GPR9 },  /* r11w */
    [X86_REG_R12W] = { REG_GPR10 },  /* r12w */
    [X86_REG_R13W] = { REG_GPR11 },  /* r13w */
    [X86_REG_R14W] = { REG_GPR12 },  /* r14w */
    [X86_REG_R15W] = { REG_GPR13 },  /* r15w */
};

/* X86: 440/1524 classified, 1084 unknown */
static const InsnClassification x86_insn_class[X86_INS_ENDING] = {
    [X86_INS_ADC]                   = { GEN_OP_INT_ADC,   BRANCH_NONE,          MF_NONE },
    [X86_INS_ADD]                   = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [X86_INS_ADDPD]                 = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_ADDPS]                 = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_ADDSD]                 = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_ADDSS]                 = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_AND]                   = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [X86_INS_ANDNPD]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_ANDNPS]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_ANDPD]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_ANDPS]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_BSF]                   = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [X86_INS_BSR]                   = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [X86_INS_BT]                    = { GEN_OP_TEST,      BRANCH_NONE,          MF_NONE },
    [X86_INS_BTC]                   = { GEN_OP_TEST,      BRANCH_NONE,          MF_NONE },
    [X86_INS_BTR]                   = { GEN_OP_TEST,      BRANCH_NONE,          MF_NONE },
    [X86_INS_BTS]                   = { GEN_OP_TEST,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CALL]                  = { GEN_OP_CALL,      BRANCH_DIRECT_CALL,   MF_NONE },
    [X86_INS_CBW]                   = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_CDQ]                   = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_CDQE]                  = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_CLC]                   = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_CLD]                   = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVA]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVAE]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVB]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVBE]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVE]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVG]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVGE]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVL]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVLE]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVNE]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVNO]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVNP]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVNS]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVO]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVP]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMOVS]                 = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [X86_INS_CMP]                   = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_CMPXCHG]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [X86_INS_CMPXCHG8B]             = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [X86_INS_CMPXCHG16B]            = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [X86_INS_COMISD]                = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_COMISS]                = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CPUID]                 = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_CQO]                   = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTDQ2PD]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTDQ2PS]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTPD2DQ]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTPD2PS]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTPS2DQ]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTPS2PD]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTSD2SI]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTSD2SS]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTSI2SD]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTSI2SS]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTSS2SD]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTSS2SI]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTTPD2DQ]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTTPS2DQ]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTTSD2SI]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTTSS2SI]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CWDE]                  = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_DEC]                   = { GEN_OP_DEC,       BRANCH_NONE,          MF_NONE },
    [X86_INS_DIV]                   = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_DIVPD]                 = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_DIVPS]                 = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FDIVR]                 = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FDIVRP]                = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_DIVSD]                 = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_DIVSS]                 = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FDIVP]                 = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_ENDBR32]               = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_ENDBR64]               = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_JMP]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_NONE },
    [X86_INS_FLDCW]                 = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FNSTCW]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_FSUB]                  = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_HLT]                   = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_IDIV]                  = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_IMUL]                  = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [X86_INS_INC]                   = { GEN_OP_INC,       BRANCH_NONE,          MF_NONE },
    [X86_INS_INT]                   = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [X86_INS_JAE]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JA]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JBE]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JB]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JCXZ]                  = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_NONE },
    [X86_INS_JECXZ]                 = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_NONE },
    [X86_INS_JE]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JGE]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JG]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JLE]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JL]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JNE]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JNO]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JNP]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JNS]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JO]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JP]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_JRCXZ]                 = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_NONE },
    [X86_INS_JS]                    = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_CONDITIONAL },
    [X86_INS_LDMXCSR]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [X86_INS_FLDZ]                  = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FLD1]                  = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FLD]                   = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_LEA]                   = { GEN_OP_LEA,       BRANCH_NONE,          MF_NONE },
    [X86_INS_LEAVE]                 = { GEN_OP_POP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_LFENCE]                = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [X86_INS_LOOPNE]                = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_NONE },
    [X86_INS_LZCNT]                 = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [X86_INS_MFENCE]                = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [X86_INS_CVTPD2PI]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTPI2PD]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTPI2PS]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTPS2PI]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTTPD2PI]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_CVTTPS2PI]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVD]                  = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVQ]                  = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [X86_INS_PADDB]                 = { GEN_OP_VEC_ADD,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PADDD]                 = { GEN_OP_VEC_ADD,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PADDQ]                 = { GEN_OP_VEC_ADD,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PADDW]                 = { GEN_OP_VEC_ADD,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PANDN]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PAND]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PCMPEQB]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PCMPEQD]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PCMPEQW]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PMAXUB]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PMINUB]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PMOVMSKB]              = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PMULLW]                = { GEN_OP_VEC_MUL,   BRANCH_NONE,          MF_NONE },
    [X86_INS_POR]                   = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PSHUFB]                = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PSUBB]                 = { GEN_OP_VEC_SUB,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PSUBD]                 = { GEN_OP_VEC_SUB,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PSUBQ]                 = { GEN_OP_VEC_SUB,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PSUBW]                 = { GEN_OP_VEC_SUB,   BRANCH_NONE,          MF_NONE },
    [X86_INS_PUNPCKHBW]             = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PUNPCKHWD]             = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PUNPCKLBW]             = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PUNPCKLDQ]             = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PUNPCKLWD]             = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PXOR]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_MOV]                   = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVABS]                = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVAPD]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVAPS]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVDQA]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVDQU]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVHPD]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVHPS]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVLPD]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVLPS]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSB]                 = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSD]                 = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSLDUP]              = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSQ]                 = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSS]                 = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSW]                 = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSX]                 = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVSXD]                = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVUPD]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVUPS]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MOVZX]                 = { GEN_OP_MOVZX,     BRANCH_NONE,          MF_NONE },
    [X86_INS_MUL]                   = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [X86_INS_MULPD]                 = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_MULPS]                 = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_MULSD]                 = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_MULSS]                 = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_NEG]                   = { GEN_OP_NEG,       BRANCH_NONE,          MF_NONE },
    [X86_INS_NOP]                   = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_NOT]                   = { GEN_OP_NOT,       BRANCH_NONE,          MF_NONE },
    [X86_INS_OR]                    = { GEN_OP_OR,        BRANCH_NONE,          MF_NONE },
    [X86_INS_ORPD]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_ORPS]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_OUT]                   = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_OUTSB]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_OUTSD]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_OUTSW]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_PCMPGTB]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PCMPISTRI]             = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_PMULLD]                = { GEN_OP_VEC_MUL,   BRANCH_NONE,          MF_NONE },
    [X86_INS_POPCNT]                = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [X86_INS_POP]                   = { GEN_OP_POP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_PSHUFD]                = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PSLLDQ]                = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PSRLDQ]                = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PUNPCKLQDQ]            = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_PUSH]                  = { GEN_OP_PUSH,      BRANCH_NONE,          MF_NONE },
    [X86_INS_PUSHF]                 = { GEN_OP_PUSH,      BRANCH_NONE,          MF_NONE },
    [X86_INS_PUSHFQ]                = { GEN_OP_PUSH,      BRANCH_NONE,          MF_NONE },
    [X86_INS_RDSSPQ]                = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_RDTSC]                 = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_RCL]                   = { GEN_OP_ROL,       BRANCH_NONE,          MF_NONE },
    [X86_INS_RET]                   = { GEN_OP_RET,       BRANCH_RETURN,        MF_NONE },
    [X86_INS_RCR]                   = { GEN_OP_ROR,       BRANCH_NONE,          MF_NONE },
    [X86_INS_ROL]                   = { GEN_OP_ROL,       BRANCH_NONE,          MF_NONE },
    [X86_INS_ROR]                   = { GEN_OP_ROR,       BRANCH_NONE,          MF_NONE },
    [X86_INS_SAL]                   = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [X86_INS_SAR]                   = { GEN_OP_SAR,       BRANCH_NONE,          MF_NONE },
    [X86_INS_SBB]                   = { GEN_OP_INT_SBB,   BRANCH_NONE,          MF_NONE },
    [X86_INS_SETAE]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETA]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETBE]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETB]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETE]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETGE]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETG]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETLE]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETL]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETNE]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETNO]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETNP]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETNS]                 = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETO]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETP]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETSSBSY]              = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SETS]                  = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [X86_INS_SFENCE]                = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [X86_INS_SHL]                   = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [X86_INS_SHR]                   = { GEN_OP_SHR,       BRANCH_NONE,          MF_NONE },
    [X86_INS_SHUFPD]                = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_SHUFPS]                = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_SQRTPD]                = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_SQRTPS]                = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_SQRTSD]                = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_SQRTSS]                = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_STMXCSR]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_STOSB]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_STOSQ]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_STOSW]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_FST]                   = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FSTP]                  = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_SUB]                   = { GEN_OP_INT_SUB,   BRANCH_NONE,          MF_NONE },
    [X86_INS_SUBPD]                 = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_SUBPS]                 = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_FSUBR]                 = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_SUBSD]                 = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_SUBSS]                 = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_SYSCALL]               = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [X86_INS_SYSENTER]              = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [X86_INS_TEST]                  = { GEN_OP_TEST,      BRANCH_NONE,          MF_NONE },
    [X86_INS_TZCNT]                 = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [X86_INS_UCOMISD]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_UCOMISS]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_UNPCKHPD]              = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_UNPCKHPS]              = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_UNPCKLPD]              = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_UNPCKLPS]              = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_VADDPD]                = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VADDPS]                = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VADDSD]                = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VADDSS]                = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VANDNPD]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VANDNPS]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VANDPD]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VANDPS]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VCOMISD]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCOMISS]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTDQ2PD]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTDQ2PS]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPD2DQ]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPD2PS]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPD2QQ]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPD2UDQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPD2UQQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPH2PS]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPS2DQ]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPS2PD]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPS2PH]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPS2QQ]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPS2UDQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTPS2UQQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTQQ2PD]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTQQ2PS]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSD2SI]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSD2SS]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSD2USI]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSI2SD]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSI2SS]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSS2SD]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSS2SI]             = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTSS2USI]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPD2DQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPD2QQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPD2UDQ]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPD2UQQ]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPS2DQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPS2QQ]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPS2UDQ]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTPS2UQQ]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTSD2SI]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTSD2USI]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTSS2SI]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTTSS2USI]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTUDQ2PD]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTUDQ2PS]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTUQQ2PD]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTUQQ2PS]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTUSI2SD]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VCVTUSI2SS]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VDIVPD]                = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VDIVPS]                = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VDIVSD]                = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VDIVSS]                = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD132PD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD132PS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD132SD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD132SS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD213PD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD213PS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD213SD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD213SS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD231PD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD231PS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD231SD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADD231SS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDPD]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDPS]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSD]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSS]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUB132PD]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUB132PS]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUB213PD]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUB213PS]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUB231PD]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUB231PS]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUBPD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMADDSUBPS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB132PD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB132PS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB132SD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB132SS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB213PD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB213PS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB213SD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB213SS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB231PD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB231PS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB231SD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUB231SS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADD132PD]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADD132PS]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADD213PD]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADD213PS]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADD231PD]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADD231PS]        = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADDPD]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBADDPS]           = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBPD]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBPS]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBSD]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFMSUBSS]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD132PD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD132PS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD132SD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD132SS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD213PD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD213PS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD213SD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD213SS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD231PD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD231PS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD231SD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADD231SS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADDPD]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADDPS]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADDSD]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMADDSS]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB132PD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB132PS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB132SD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB132SS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB213PD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB213PS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB213SD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB213SS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB231PD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB231PS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB231SD]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUB231SS]          = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUBPD]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUBPS]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUBSD]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VFNMSUBSS]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVQ]                 = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVAPD]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVAPS]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVD]                 = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVDQA]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVDQU]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVHPD]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVHPS]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVLPD]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVLPS]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVSD]                = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVSS]                = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVUPD]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMOVUPS]               = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VMULPD]                = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VMULPS]                = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VMULSD]                = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VMULSS]                = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VORPD]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VORPS]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPANDN]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPAND]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPBROADCASTB]          = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VPBROADCASTD]          = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VPCMPEQB]              = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPCMPEQD]              = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPCMPEQW]              = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPCMPGTB]              = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPMINUB]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPMOVMSKB]             = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VPOR]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VPSHUFB]               = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_VPSHUFD]               = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_VPSUBB]                = { GEN_OP_VEC_SUB,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VPXOR]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VSHUFPD]               = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_VSHUFPS]               = { GEN_OP_VEC_SHUF,  BRANCH_NONE,          MF_NONE },
    [X86_INS_VSQRTPD]               = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VSQRTPS]               = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VSQRTSD]               = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VSQRTSS]               = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [X86_INS_VSUBPD]                = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VSUBPS]                = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VSUBSD]                = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VSUBSS]                = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VUCOMISD]              = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VUCOMISS]              = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [X86_INS_VXORPD]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VXORPS]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_VZEROUPPER]            = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_WAIT]                  = { GEN_OP_FENCE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_XCHG]                  = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [X86_INS_XGETBV]                = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [X86_INS_XOR]                   = { GEN_OP_XOR,       BRANCH_NONE,          MF_NONE },
    [X86_INS_XORPD]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_XORPS]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [X86_INS_XRSTOR]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [X86_INS_XRSTOR64]              = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [X86_INS_XSAVE]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [X86_INS_XSAVE64]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },

    /* --- SPEC2017 rate workload additions --- */
    [X86_INS_ANDN]                        = { GEN_OP_AND,    BRANCH_NONE,           MF_NONE },
    [X86_INS_BLSI]                        = { GEN_OP_AND,    BRANCH_NONE,           MF_NONE },
    [X86_INS_BLSMSK]                      = { GEN_OP_AND,    BRANCH_NONE,           MF_NONE },
    [X86_INS_BLSR]                        = { GEN_OP_AND,    BRANCH_NONE,           MF_NONE },
    [X86_INS_BSWAP]                       = { GEN_OP_MOV,    BRANCH_NONE,           MF_NONE },
    [X86_INS_BZHI]                        = { GEN_OP_AND,    BRANCH_NONE,           MF_NONE },
    [X86_INS_FABS]                        = { GEN_OP_FP_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_FADD]                        = { GEN_OP_FP_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_FCHS]                        = { GEN_OP_FP_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_FCMOVBE]                     = { GEN_OP_CMOV,   BRANCH_NONE,           MF_NONE },
    [X86_INS_FCOMI]                       = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_FCOMPI]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_FDIV]                        = { GEN_OP_FP_DIV, BRANCH_NONE,           MF_NONE },
    [X86_INS_FILD]                        = { GEN_OP_FP_CVT, BRANCH_NONE,           MF_NONE },
    [X86_INS_FMUL]                        = { GEN_OP_FP_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_FMULP]                       = { GEN_OP_FP_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_FSQRT]                       = { GEN_OP_FP_SQRT, BRANCH_NONE,           MF_NONE },
    [X86_INS_FSUBP]                       = { GEN_OP_FP_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_FSUBRP]                      = { GEN_OP_FP_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_FUCOMI]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_FUCOMPI]                     = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_FXCH]                        = { GEN_OP_FP_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_MOVBE]                       = { GEN_OP_MOV,    BRANCH_NONE,           MF_NONE },
    [X86_INS_PREFETCHT0]                  = { GEN_OP_NOP,    BRANCH_NONE,           MF_NONE },
    [X86_INS_RORX]                        = { GEN_OP_ROR,    BRANCH_NONE,           MF_NONE },
    [X86_INS_SARX]                        = { GEN_OP_SAR,    BRANCH_NONE,           MF_NONE },
    [X86_INS_SHLX]                        = { GEN_OP_SHL,    BRANCH_NONE,           MF_NONE },
    [X86_INS_SHRX]                        = { GEN_OP_SHR,    BRANCH_NONE,           MF_NONE },
    [X86_INS_STOSD]                       = { GEN_OP_STORE,  BRANCH_NONE,           MF_NONE },
    [X86_INS_UD2]                         = { GEN_OP_NOP,    BRANCH_NONE,           MF_NONE },
    [X86_INS_VADDSUBPD]                   = { GEN_OP_FP_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VADDSUBPS]                   = { GEN_OP_FP_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VBLENDPD]                    = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VBLENDPS]                    = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VBLENDVPD]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VBLENDVPS]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VBROADCASTF128]              = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VBROADCASTSD]                = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VBROADCASTSS]                = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VCMP]                        = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VEXTRACTF128]                = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VEXTRACTI128]                = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VEXTRACTPS]                  = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VGATHERDPD]                  = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VGATHERDPS]                  = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VGATHERQPD]                  = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VGATHERQPS]                  = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VHADDPD]                     = { GEN_OP_FP_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VHADDPS]                     = { GEN_OP_FP_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VHSUBPS]                     = { GEN_OP_FP_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_VINSERTF128]                 = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VINSERTI128]                 = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VINSERTPS]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMASKMOVPD]                  = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMASKMOVPS]                  = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMAXPD]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMAXPS]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMAXSD]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMAXSS]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMINPD]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMINPS]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMINSD]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMINSS]                      = { GEN_OP_FP_CMP, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMOVDDUP]                    = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMOVHLPS]                    = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMOVLHPS]                    = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMOVMSKPD]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMOVSHDUP]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VMOVSLDUP]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPABSB]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPABSD]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPABSW]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPACKUSDW]                   = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPACKUSWB]                   = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPADDB]                      = { GEN_OP_VEC_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPADDD]                      = { GEN_OP_VEC_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPADDQ]                      = { GEN_OP_VEC_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPADDW]                      = { GEN_OP_VEC_ADD, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPALIGNR]                    = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPAVGB]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPAVGW]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPBLENDD]                    = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPBLENDVB]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPBLENDW]                    = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPBROADCASTQ]                = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPBROADCASTW]                = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPCMPEQQ]                    = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPCMPGTD]                    = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPCMPGTQ]                    = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPCMPGTW]                    = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPERM2F128]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPERM2I128]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPERMD]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPERMILPD]                   = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPERMILPS]                   = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPERMPD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPERMQ]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPEXTRB]                     = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPEXTRD]                     = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPEXTRQ]                     = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPEXTRW]                     = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPGATHERDD]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPGATHERDQ]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPGATHERQD]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPGATHERQQ]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPHADDD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPHMINPOSUW]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPINSRB]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPINSRD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPINSRQ]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPINSRW]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMADDWD]                    = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMASKMOVD]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMASKMOVQ]                  = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMAXSB]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMAXSD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMAXSW]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMAXUB]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMAXUD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMAXUW]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMINSB]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMINSD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMINSW]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMINUD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMINUW]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVSXBW]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVSXDQ]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVSXWD]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVZXBD]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVZXBW]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVZXDQ]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVZXWD]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMOVZXWQ]                   = { GEN_OP_VEC_MOV, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMULDQ]                     = { GEN_OP_VEC_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMULHUW]                    = { GEN_OP_VEC_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMULHW]                     = { GEN_OP_VEC_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMULLD]                     = { GEN_OP_VEC_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMULLW]                     = { GEN_OP_VEC_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPMULUDQ]                    = { GEN_OP_VEC_MUL, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSADBW]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSHUFLW]                    = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSLLD]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSLLQ]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSLLVD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSLLVQ]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSLLW]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRAD]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRAVD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRAW]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRLD]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRLDQ]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRLQ]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRLVD]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRLVQ]                     = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSRLW]                      = { GEN_OP_VEC_LOGIC, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSUBD]                      = { GEN_OP_VEC_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSUBQ]                      = { GEN_OP_VEC_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSUBUSB]                    = { GEN_OP_VEC_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSUBUSW]                    = { GEN_OP_VEC_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPSUBW]                      = { GEN_OP_VEC_SUB, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPTEST]                      = { GEN_OP_TEST,   BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKHBW]                  = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKHDQ]                  = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKHQDQ]                 = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKHWD]                  = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKLBW]                  = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKLDQ]                  = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKLQDQ]                 = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VPUNPCKLWD]                  = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VROUNDSD]                    = { GEN_OP_FP_CVT, BRANCH_NONE,           MF_NONE },
    [X86_INS_VROUNDSS]                    = { GEN_OP_FP_CVT, BRANCH_NONE,           MF_NONE },
    [X86_INS_VUNPCKHPD]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VUNPCKHPS]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VUNPCKLPD]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
    [X86_INS_VUNPCKLPS]                   = { GEN_OP_VEC_SHUF, BRANCH_NONE,           MF_NONE },
};

#endif /* CHAMPSIM_TRACER_MNEMONICS_X86_H */
