#ifndef WPTRACE_MNEMONICS_RISCV_H
#define WPTRACE_MNEMONICS_RISCV_H

/*
 * ISA-specific classification tables for wptrace — riscv.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include <capstone/riscv.h>

/* RISCV: 95/96 classified, 1 REG_NONE */
static const RegClassification riscv_reg_class[RISCV_REG_ENDING] = {
    [RISCV_REG_X0] = { REG_ZERO },  /* zero (hardwired zero) */
    [RISCV_REG_X1] = { REG_LR },  /* ra */
    [RISCV_REG_X2] = { REG_SP },  /* sp */
    [RISCV_REG_X3] = { REG_GPR3 },  /* gp */
    [RISCV_REG_X4] = { REG_GPR4 },  /* tp */
    [RISCV_REG_X5] = { REG_GPR5 },  /* t0 */
    [RISCV_REG_X6] = { REG_GPR6 },  /* t1 */
    [RISCV_REG_X7] = { REG_GPR7 },  /* t2 */
    [RISCV_REG_X8] = { REG_FP_REG },  /* s0 */
    [RISCV_REG_X9] = { REG_GPR9 },  /* s1 */
    [RISCV_REG_A0] = { REG_GPR10 },  /* a0 */
    [RISCV_REG_A1] = { REG_GPR11 },  /* a1 */
    [RISCV_REG_A2] = { REG_GPR12 },  /* a2 */
    [RISCV_REG_A3] = { REG_GPR13 },  /* a3 */
    [RISCV_REG_A4] = { REG_GPR14 },  /* a4 */
    [RISCV_REG_A5] = { REG_GPR15 },  /* a5 */
    [RISCV_REG_A6] = { REG_GPR16 },  /* a6 */
    [RISCV_REG_A7] = { REG_GPR17 },  /* a7 */
    [RISCV_REG_S2] = { REG_GPR18 },  /* s2 */
    [RISCV_REG_S3] = { REG_GPR19 },  /* s3 */
    [RISCV_REG_S4] = { REG_GPR20 },  /* s4 */
    [RISCV_REG_S5] = { REG_GPR21 },  /* s5 */
    [RISCV_REG_S6] = { REG_GPR22 },  /* s6 */
    [RISCV_REG_S7] = { REG_GPR23 },  /* s7 */
    [RISCV_REG_S8] = { REG_GPR24 },  /* s8 */
    [RISCV_REG_S9] = { REG_GPR25 },  /* s9 */
    [RISCV_REG_X26] = { REG_GPR26 },  /* s10 */
    [RISCV_REG_X27] = { REG_GPR27 },  /* s11 */
    [RISCV_REG_T3] = { REG_GPR28 },  /* t3 */
    [RISCV_REG_T4] = { REG_GPR29 },  /* t4 */
    [RISCV_REG_T5] = { REG_GPR30 },  /* t5 */
    [RISCV_REG_T6] = { REG_GPR31 },  /* t6 */
    [RISCV_REG_F0_32] = { REG_FPR0 },  /* ft0 */
    [RISCV_REG_F0_64] = { REG_FPR0 },  /* ft0 */
    [RISCV_REG_F1_32] = { REG_FPR1 },  /* ft1 */
    [RISCV_REG_F1_64] = { REG_FPR1 },  /* ft1 */
    [RISCV_REG_F2_32] = { REG_FPR2 },  /* ft2 */
    [RISCV_REG_F2_64] = { REG_FPR2 },  /* ft2 */
    [RISCV_REG_F3_32] = { REG_FPR3 },  /* ft3 */
    [RISCV_REG_F3_64] = { REG_FPR3 },  /* ft3 */
    [RISCV_REG_F4_32] = { REG_FPR4 },  /* ft4 */
    [RISCV_REG_F4_64] = { REG_FPR4 },  /* ft4 */
    [RISCV_REG_F5_32] = { REG_FPR5 },  /* ft5 */
    [RISCV_REG_F5_64] = { REG_FPR5 },  /* ft5 */
    [RISCV_REG_F6_32] = { REG_FPR6 },  /* ft6 */
    [RISCV_REG_F6_64] = { REG_FPR6 },  /* ft6 */
    [RISCV_REG_F7_32] = { REG_FPR7 },  /* ft7 */
    [RISCV_REG_F7_64] = { REG_FPR7 },  /* ft7 */
    [RISCV_REG_F8_32] = { REG_FPR8 },  /* fs0 */
    [RISCV_REG_F8_64] = { REG_FPR8 },  /* fs0 */
    [RISCV_REG_F9_32] = { REG_FPR9 },  /* fs1 */
    [RISCV_REG_F9_64] = { REG_FPR9 },  /* fs1 */
    [RISCV_REG_F10_32] = { REG_FPR10 },  /* fa0 */
    [RISCV_REG_F10_64] = { REG_FPR10 },  /* fa0 */
    [RISCV_REG_F11_32] = { REG_FPR11 },  /* fa1 */
    [RISCV_REG_F11_64] = { REG_FPR11 },  /* fa1 */
    [RISCV_REG_F12_32] = { REG_FPR12 },  /* fa2 */
    [RISCV_REG_F12_64] = { REG_FPR12 },  /* fa2 */
    [RISCV_REG_F13_32] = { REG_FPR13 },  /* fa3 */
    [RISCV_REG_F13_64] = { REG_FPR13 },  /* fa3 */
    [RISCV_REG_F14_32] = { REG_FPR14 },  /* fa4 */
    [RISCV_REG_F14_64] = { REG_FPR14 },  /* fa4 */
    [RISCV_REG_F15_32] = { REG_FPR15 },  /* fa5 */
    [RISCV_REG_F15_64] = { REG_FPR15 },  /* fa5 */
    [RISCV_REG_F16_32] = { REG_FPR16 },  /* fa6 */
    [RISCV_REG_F16_64] = { REG_FPR16 },  /* fa6 */
    [RISCV_REG_F17_32] = { REG_FPR17 },  /* fa7 */
    [RISCV_REG_F17_64] = { REG_FPR17 },  /* fa7 */
    [RISCV_REG_F18_32] = { REG_FPR18 },  /* fs2 */
    [RISCV_REG_F18_64] = { REG_FPR18 },  /* fs2 */
    [RISCV_REG_F19_32] = { REG_FPR19 },  /* fs3 */
    [RISCV_REG_F19_64] = { REG_FPR19 },  /* fs3 */
    [RISCV_REG_F20_32] = { REG_FPR20 },  /* fs4 */
    [RISCV_REG_F20_64] = { REG_FPR20 },  /* fs4 */
    [RISCV_REG_F21_32] = { REG_FPR21 },  /* fs5 */
    [RISCV_REG_F21_64] = { REG_FPR21 },  /* fs5 */
    [RISCV_REG_F22_32] = { REG_FPR22 },  /* fs6 */
    [RISCV_REG_F22_64] = { REG_FPR22 },  /* fs6 */
    [RISCV_REG_F23_32] = { REG_FPR23 },  /* fs7 */
    [RISCV_REG_F23_64] = { REG_FPR23 },  /* fs7 */
    [RISCV_REG_F24_32] = { REG_FPR24 },  /* fs8 */
    [RISCV_REG_F24_64] = { REG_FPR24 },  /* fs8 */
    [RISCV_REG_F25_32] = { REG_FPR25 },  /* fs9 */
    [RISCV_REG_F25_64] = { REG_FPR25 },  /* fs9 */
    [RISCV_REG_F26_32] = { REG_FPR26 },  /* fs10 */
    [RISCV_REG_F26_64] = { REG_FPR26 },  /* fs10 */
    [RISCV_REG_F27_32] = { REG_FPR27 },  /* fs11 */
    [RISCV_REG_F27_64] = { REG_FPR27 },  /* fs11 */
    [RISCV_REG_F28_32] = { REG_FPR28 },  /* ft8 */
    [RISCV_REG_F28_64] = { REG_FPR28 },  /* ft8 */
    [RISCV_REG_F29_32] = { REG_FPR29 },  /* ft9 */
    [RISCV_REG_F29_64] = { REG_FPR29 },  /* ft9 */
    [RISCV_REG_F30_32] = { REG_FPR30 },  /* ft10 */
    [RISCV_REG_F30_64] = { REG_FPR30 },  /* ft10 */
    [RISCV_REG_F31_32] = { REG_FPR31 },  /* ft11 */
    [RISCV_REG_F31_64] = { REG_FPR31 },  /* ft11 */
};

/* RISCV: 273/273 classified (all instructions) */
static const InsnClassification riscv_insn_class[RISCV_INS_ENDING] = {
    /* RV64I base */
    [RISCV_INS_ADD]                 = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_ADDI]                = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_ADDIW]               = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_ADDW]                = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_AND]                 = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_ANDI]                = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_AUIPC]               = { GEN_OP_LEA,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_BEQ]                 = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_BGE]                 = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_BGEU]                = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_BLT]                 = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_BLTU]                = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_BNE]                 = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_EBREAK]              = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [RISCV_INS_ECALL]               = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [RISCV_INS_FENCE]               = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_FENCE_I]             = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_FENCE_TSO]           = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_JAL]                 = { GEN_OP_CALL,      BRANCH_DIRECT_CALL,   MF_NONE },
    [RISCV_INS_JALR]                = { GEN_OP_CALL,      BRANCH_INDIRECT_CALL, MF_NONE },
    [RISCV_INS_LB]                  = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_LBU]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_LD]                  = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_LH]                  = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_LHU]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_LUI]                 = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_LW]                  = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_LWU]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_OR]                  = { GEN_OP_OR,        BRANCH_NONE,          MF_NONE },
    [RISCV_INS_ORI]                 = { GEN_OP_OR,        BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SB]                  = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SD]                  = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SH]                  = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLL]                 = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLLI]                = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLLIW]               = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLLW]                = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLT]                 = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLTI]                = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLTIU]               = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SLTU]                = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRA]                 = { GEN_OP_SAR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRAI]                = { GEN_OP_SAR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRAIW]               = { GEN_OP_SAR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRAW]                = { GEN_OP_SAR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRL]                 = { GEN_OP_SHR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRLI]                = { GEN_OP_SHR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRLIW]               = { GEN_OP_SHR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SRLW]                = { GEN_OP_SHR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SUB]                 = { GEN_OP_INT_SUB,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SUBW]                = { GEN_OP_INT_SUB,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SW]                  = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_XOR]                 = { GEN_OP_XOR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_XORI]                = { GEN_OP_XOR,       BRANCH_NONE,          MF_NONE },
    /* RV64M */
    [RISCV_INS_DIV]                 = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_DIVU]                = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_DIVUW]               = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_DIVW]                = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_MUL]                 = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_MULH]                = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_MULHSU]              = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_MULHU]               = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_MULW]                = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_REM]                 = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_REMU]                = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_REMUW]               = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_REMW]                = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    /* RV64A atomics */
    [RISCV_INS_AMOADD_D]            = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOADD_D_AQ]         = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOADD_D_AQ_RL]      = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOADD_D_RL]         = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOADD_W]            = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOADD_W_AQ]         = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOADD_W_AQ_RL]      = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOADD_W_RL]         = { GEN_OP_INT_ADD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_D]            = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_D_AQ]         = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_D_AQ_RL]      = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_D_RL]         = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_W]            = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_W_AQ]         = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_W_AQ_RL]      = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOAND_W_RL]         = { GEN_OP_AND,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_D]           = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_D_AQ]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_D_AQ_RL]     = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_D_RL]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_W]           = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_W_AQ]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_W_AQ_RL]     = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAXU_W_RL]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_D]            = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_D_AQ]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_D_AQ_RL]      = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_D_RL]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_W]            = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_W_AQ]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_W_AQ_RL]      = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMAX_W_RL]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_D]           = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_D_AQ]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_D_AQ_RL]     = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_D_RL]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_W]           = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_W_AQ]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_W_AQ_RL]     = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMINU_W_RL]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_D]            = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_D_AQ]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_D_AQ_RL]      = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_D_RL]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_W]            = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_W_AQ]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_W_AQ_RL]      = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOMIN_W_RL]         = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_D]             = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_D_AQ]          = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_D_AQ_RL]       = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_D_RL]          = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_W]             = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_W_AQ]          = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_W_AQ_RL]       = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOOR_W_RL]          = { GEN_OP_OR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_D]           = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_D_AQ]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_D_AQ_RL]     = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_D_RL]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_W]           = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_W_AQ]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_W_AQ_RL]     = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOSWAP_W_RL]        = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_D]            = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_D_AQ]         = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_D_AQ_RL]      = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_D_RL]         = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_W]            = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_W_AQ]         = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_W_AQ_RL]      = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_AMOXOR_W_RL]         = { GEN_OP_XOR,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_D]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_D_AQ]             = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_D_AQ_RL]          = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_D_RL]             = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_W]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_W_AQ]             = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_W_AQ_RL]          = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_LR_W_RL]             = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_D]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_D_AQ]             = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_D_AQ_RL]          = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_D_RL]             = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_W]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_W_AQ]             = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_W_AQ_RL]          = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_SC_W_RL]             = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    /* RV64F/D floating point */
    [RISCV_INS_FLD]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FLW]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSD]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSW]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FADD_S]              = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FADD_D]              = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSUB_S]              = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSUB_D]              = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMUL_S]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMUL_D]              = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FDIV_S]              = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FDIV_D]              = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSQRT_S]             = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSQRT_D]             = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMIN_S]              = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMIN_D]              = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMAX_S]              = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMAX_D]              = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMADD_S]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMADD_D]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMSUB_S]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMSUB_D]             = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FNMADD_S]            = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FNMADD_D]            = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FNMSUB_S]            = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FNMSUB_D]            = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSGNJ_S]             = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSGNJ_D]             = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSGNJN_S]            = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSGNJN_D]            = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSGNJX_S]            = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FSGNJX_D]            = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMV_W_X]             = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMV_X_W]             = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMV_D_X]             = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FMV_X_D]             = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_S_D]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_D_S]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_W_S]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_W_D]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_WU_S]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_WU_D]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_L_S]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_L_D]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_LU_S]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_LU_D]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_S_W]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_S_WU]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_S_L]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_S_LU]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_D_W]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_D_WU]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_D_L]            = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCVT_D_LU]           = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FEQ_S]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FEQ_D]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FLT_S]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FLT_D]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FLE_S]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FLE_D]               = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCLASS_S]            = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [RISCV_INS_FCLASS_D]            = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    /* Zicsr */
    [RISCV_INS_CSRRW]               = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_CSRRS]               = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_CSRRC]               = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_CSRRWI]              = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_CSRRSI]              = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_CSRRCI]              = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    /* System */
    [RISCV_INS_MRET]                = { GEN_OP_RET,       BRANCH_RETURN,        MF_NONE },
    [RISCV_INS_SRET]                = { GEN_OP_RET,       BRANCH_RETURN,        MF_NONE },
    [RISCV_INS_URET]                = { GEN_OP_RET,       BRANCH_RETURN,        MF_NONE },
    [RISCV_INS_WFI]                 = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_SFENCE_VMA]          = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [RISCV_INS_UNIMP]               = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    /* RV64C compressed */
    [RISCV_INS_C_ADD]               = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_ADDI]              = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_ADDI16SP]          = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_ADDI4SPN]          = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_ADDIW]             = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_ADDW]              = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_AND]               = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_ANDI]              = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_BEQZ]              = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_C_BNEZ]              = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [RISCV_INS_C_EBREAK]            = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [RISCV_INS_C_FLD]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_FLDSP]             = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_FLW]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_FLWSP]             = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_FSD]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_FSDSP]             = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_FSW]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_FSWSP]             = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_J]                 = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_NONE },
    [RISCV_INS_C_JAL]               = { GEN_OP_CALL,      BRANCH_DIRECT_CALL,   MF_NONE },
    [RISCV_INS_C_JALR]              = { GEN_OP_CALL,      BRANCH_INDIRECT_CALL, MF_NONE },
    [RISCV_INS_C_JR]                = { GEN_OP_BRANCH,    BRANCH_INDIRECT_JUMP, MF_NONE },
    [RISCV_INS_C_LD]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_LDSP]              = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_LI]                = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_LUI]               = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_LW]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_LWSP]              = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_MV]                = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_NOP]               = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_OR]                = { GEN_OP_OR,        BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SD]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SDSP]              = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SLLI]              = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SRAI]              = { GEN_OP_SAR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SRLI]              = { GEN_OP_SHR,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SUB]               = { GEN_OP_INT_SUB,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SUBW]              = { GEN_OP_INT_SUB,   BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SW]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_SWSP]              = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_UNIMP]             = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [RISCV_INS_C_XOR]               = { GEN_OP_XOR,       BRANCH_NONE,          MF_NONE },
};

#endif /* WPTRACE_MNEMONICS_RISCV_H */
