#ifndef WPTRACE_MNEMONICS_AARCH64_H
#define WPTRACE_MNEMONICS_AARCH64_H

/*
 * ISA-specific classification tables for wptrace — aarch64.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include <capstone/arm64.h>

/* ARM64: 256/341 classified, 85 REG_NONE */
static const RegClassification arm64_reg_class[ARM64_REG_ENDING] = {
    [ARM64_REG_FP] = { REG_FP_REG },  /* fp */
    [ARM64_REG_LR] = { REG_LR },  /* lr */
    [ARM64_REG_NZCV] = { REG_FLAGS },  /* nzcv */
    [ARM64_REG_SP] = { REG_SP },  /* sp */
    [ARM64_REG_B0] = { REG_VEC0 },  /* b0 */
    [ARM64_REG_B1] = { REG_VEC1 },  /* b1 */
    [ARM64_REG_B2] = { REG_VEC2 },  /* b2 */
    [ARM64_REG_B3] = { REG_VEC3 },  /* b3 */
    [ARM64_REG_B4] = { REG_VEC4 },  /* b4 */
    [ARM64_REG_B5] = { REG_VEC5 },  /* b5 */
    [ARM64_REG_B6] = { REG_VEC6 },  /* b6 */
    [ARM64_REG_B7] = { REG_VEC7 },  /* b7 */
    [ARM64_REG_B8] = { REG_VEC8 },  /* b8 */
    [ARM64_REG_B9] = { REG_VEC9 },  /* b9 */
    [ARM64_REG_B10] = { REG_VEC10 },  /* b10 */
    [ARM64_REG_B11] = { REG_VEC11 },  /* b11 */
    [ARM64_REG_B12] = { REG_VEC12 },  /* b12 */
    [ARM64_REG_B13] = { REG_VEC13 },  /* b13 */
    [ARM64_REG_B14] = { REG_VEC14 },  /* b14 */
    [ARM64_REG_B15] = { REG_VEC15 },  /* b15 */
    [ARM64_REG_B16] = { REG_VEC16 },  /* b16 */
    [ARM64_REG_B17] = { REG_VEC17 },  /* b17 */
    [ARM64_REG_B18] = { REG_VEC18 },  /* b18 */
    [ARM64_REG_B19] = { REG_VEC19 },  /* b19 */
    [ARM64_REG_B20] = { REG_VEC20 },  /* b20 */
    [ARM64_REG_B21] = { REG_VEC21 },  /* b21 */
    [ARM64_REG_B22] = { REG_VEC22 },  /* b22 */
    [ARM64_REG_B23] = { REG_VEC23 },  /* b23 */
    [ARM64_REG_B24] = { REG_VEC24 },  /* b24 */
    [ARM64_REG_B25] = { REG_VEC25 },  /* b25 */
    [ARM64_REG_B26] = { REG_VEC26 },  /* b26 */
    [ARM64_REG_B27] = { REG_VEC27 },  /* b27 */
    [ARM64_REG_B28] = { REG_VEC28 },  /* b28 */
    [ARM64_REG_B29] = { REG_VEC29 },  /* b29 */
    [ARM64_REG_B30] = { REG_VEC30 },  /* b30 */
    [ARM64_REG_B31] = { REG_VEC31 },  /* b31 */
    [ARM64_REG_D0] = { REG_VEC0 },  /* d0 */
    [ARM64_REG_D1] = { REG_VEC1 },  /* d1 */
    [ARM64_REG_D2] = { REG_VEC2 },  /* d2 */
    [ARM64_REG_D3] = { REG_VEC3 },  /* d3 */
    [ARM64_REG_D4] = { REG_VEC4 },  /* d4 */
    [ARM64_REG_D5] = { REG_VEC5 },  /* d5 */
    [ARM64_REG_D6] = { REG_VEC6 },  /* d6 */
    [ARM64_REG_D7] = { REG_VEC7 },  /* d7 */
    [ARM64_REG_D8] = { REG_VEC8 },  /* d8 */
    [ARM64_REG_D9] = { REG_VEC9 },  /* d9 */
    [ARM64_REG_D10] = { REG_VEC10 },  /* d10 */
    [ARM64_REG_D11] = { REG_VEC11 },  /* d11 */
    [ARM64_REG_D12] = { REG_VEC12 },  /* d12 */
    [ARM64_REG_D13] = { REG_VEC13 },  /* d13 */
    [ARM64_REG_D14] = { REG_VEC14 },  /* d14 */
    [ARM64_REG_D15] = { REG_VEC15 },  /* d15 */
    [ARM64_REG_D16] = { REG_VEC16 },  /* d16 */
    [ARM64_REG_D17] = { REG_VEC17 },  /* d17 */
    [ARM64_REG_D18] = { REG_VEC18 },  /* d18 */
    [ARM64_REG_D19] = { REG_VEC19 },  /* d19 */
    [ARM64_REG_D20] = { REG_VEC20 },  /* d20 */
    [ARM64_REG_D21] = { REG_VEC21 },  /* d21 */
    [ARM64_REG_D22] = { REG_VEC22 },  /* d22 */
    [ARM64_REG_D23] = { REG_VEC23 },  /* d23 */
    [ARM64_REG_D24] = { REG_VEC24 },  /* d24 */
    [ARM64_REG_D25] = { REG_VEC25 },  /* d25 */
    [ARM64_REG_D26] = { REG_VEC26 },  /* d26 */
    [ARM64_REG_D27] = { REG_VEC27 },  /* d27 */
    [ARM64_REG_D28] = { REG_VEC28 },  /* d28 */
    [ARM64_REG_D29] = { REG_VEC29 },  /* d29 */
    [ARM64_REG_D30] = { REG_VEC30 },  /* d30 */
    [ARM64_REG_D31] = { REG_VEC31 },  /* d31 */
    [ARM64_REG_H0] = { REG_VEC0 },  /* h0 */
    [ARM64_REG_H1] = { REG_VEC1 },  /* h1 */
    [ARM64_REG_H2] = { REG_VEC2 },  /* h2 */
    [ARM64_REG_H3] = { REG_VEC3 },  /* h3 */
    [ARM64_REG_H4] = { REG_VEC4 },  /* h4 */
    [ARM64_REG_H5] = { REG_VEC5 },  /* h5 */
    [ARM64_REG_H6] = { REG_VEC6 },  /* h6 */
    [ARM64_REG_H7] = { REG_VEC7 },  /* h7 */
    [ARM64_REG_H8] = { REG_VEC8 },  /* h8 */
    [ARM64_REG_H9] = { REG_VEC9 },  /* h9 */
    [ARM64_REG_H10] = { REG_VEC10 },  /* h10 */
    [ARM64_REG_H11] = { REG_VEC11 },  /* h11 */
    [ARM64_REG_H12] = { REG_VEC12 },  /* h12 */
    [ARM64_REG_H13] = { REG_VEC13 },  /* h13 */
    [ARM64_REG_H14] = { REG_VEC14 },  /* h14 */
    [ARM64_REG_H15] = { REG_VEC15 },  /* h15 */
    [ARM64_REG_H16] = { REG_VEC16 },  /* h16 */
    [ARM64_REG_H17] = { REG_VEC17 },  /* h17 */
    [ARM64_REG_H18] = { REG_VEC18 },  /* h18 */
    [ARM64_REG_H19] = { REG_VEC19 },  /* h19 */
    [ARM64_REG_H20] = { REG_VEC20 },  /* h20 */
    [ARM64_REG_H21] = { REG_VEC21 },  /* h21 */
    [ARM64_REG_H22] = { REG_VEC22 },  /* h22 */
    [ARM64_REG_H23] = { REG_VEC23 },  /* h23 */
    [ARM64_REG_H24] = { REG_VEC24 },  /* h24 */
    [ARM64_REG_H25] = { REG_VEC25 },  /* h25 */
    [ARM64_REG_H26] = { REG_VEC26 },  /* h26 */
    [ARM64_REG_H27] = { REG_VEC27 },  /* h27 */
    [ARM64_REG_H28] = { REG_VEC28 },  /* h28 */
    [ARM64_REG_H29] = { REG_VEC29 },  /* h29 */
    [ARM64_REG_H30] = { REG_VEC30 },  /* h30 */
    [ARM64_REG_H31] = { REG_VEC31 },  /* h31 */
    [ARM64_REG_Q0] = { REG_VEC0 },  /* q0 */
    [ARM64_REG_Q1] = { REG_VEC1 },  /* q1 */
    [ARM64_REG_Q2] = { REG_VEC2 },  /* q2 */
    [ARM64_REG_Q3] = { REG_VEC3 },  /* q3 */
    [ARM64_REG_Q4] = { REG_VEC4 },  /* q4 */
    [ARM64_REG_Q5] = { REG_VEC5 },  /* q5 */
    [ARM64_REG_Q6] = { REG_VEC6 },  /* q6 */
    [ARM64_REG_Q7] = { REG_VEC7 },  /* q7 */
    [ARM64_REG_Q8] = { REG_VEC8 },  /* q8 */
    [ARM64_REG_Q9] = { REG_VEC9 },  /* q9 */
    [ARM64_REG_Q10] = { REG_VEC10 },  /* q10 */
    [ARM64_REG_Q11] = { REG_VEC11 },  /* q11 */
    [ARM64_REG_Q12] = { REG_VEC12 },  /* q12 */
    [ARM64_REG_Q13] = { REG_VEC13 },  /* q13 */
    [ARM64_REG_Q14] = { REG_VEC14 },  /* q14 */
    [ARM64_REG_Q15] = { REG_VEC15 },  /* q15 */
    [ARM64_REG_Q16] = { REG_VEC16 },  /* q16 */
    [ARM64_REG_Q17] = { REG_VEC17 },  /* q17 */
    [ARM64_REG_Q18] = { REG_VEC18 },  /* q18 */
    [ARM64_REG_Q19] = { REG_VEC19 },  /* q19 */
    [ARM64_REG_Q20] = { REG_VEC20 },  /* q20 */
    [ARM64_REG_Q21] = { REG_VEC21 },  /* q21 */
    [ARM64_REG_Q22] = { REG_VEC22 },  /* q22 */
    [ARM64_REG_Q23] = { REG_VEC23 },  /* q23 */
    [ARM64_REG_Q24] = { REG_VEC24 },  /* q24 */
    [ARM64_REG_Q25] = { REG_VEC25 },  /* q25 */
    [ARM64_REG_Q26] = { REG_VEC26 },  /* q26 */
    [ARM64_REG_Q27] = { REG_VEC27 },  /* q27 */
    [ARM64_REG_Q28] = { REG_VEC28 },  /* q28 */
    [ARM64_REG_Q29] = { REG_VEC29 },  /* q29 */
    [ARM64_REG_Q30] = { REG_VEC30 },  /* q30 */
    [ARM64_REG_Q31] = { REG_VEC31 },  /* q31 */
    [ARM64_REG_S0] = { REG_VEC0 },  /* s0 */
    [ARM64_REG_S1] = { REG_VEC1 },  /* s1 */
    [ARM64_REG_S2] = { REG_VEC2 },  /* s2 */
    [ARM64_REG_S3] = { REG_VEC3 },  /* s3 */
    [ARM64_REG_S4] = { REG_VEC4 },  /* s4 */
    [ARM64_REG_S5] = { REG_VEC5 },  /* s5 */
    [ARM64_REG_S6] = { REG_VEC6 },  /* s6 */
    [ARM64_REG_S7] = { REG_VEC7 },  /* s7 */
    [ARM64_REG_S8] = { REG_VEC8 },  /* s8 */
    [ARM64_REG_S9] = { REG_VEC9 },  /* s9 */
    [ARM64_REG_S10] = { REG_VEC10 },  /* s10 */
    [ARM64_REG_S11] = { REG_VEC11 },  /* s11 */
    [ARM64_REG_S12] = { REG_VEC12 },  /* s12 */
    [ARM64_REG_S13] = { REG_VEC13 },  /* s13 */
    [ARM64_REG_S14] = { REG_VEC14 },  /* s14 */
    [ARM64_REG_S15] = { REG_VEC15 },  /* s15 */
    [ARM64_REG_S16] = { REG_VEC16 },  /* s16 */
    [ARM64_REG_S17] = { REG_VEC17 },  /* s17 */
    [ARM64_REG_S18] = { REG_VEC18 },  /* s18 */
    [ARM64_REG_S19] = { REG_VEC19 },  /* s19 */
    [ARM64_REG_S20] = { REG_VEC20 },  /* s20 */
    [ARM64_REG_S21] = { REG_VEC21 },  /* s21 */
    [ARM64_REG_S22] = { REG_VEC22 },  /* s22 */
    [ARM64_REG_S23] = { REG_VEC23 },  /* s23 */
    [ARM64_REG_S24] = { REG_VEC24 },  /* s24 */
    [ARM64_REG_S25] = { REG_VEC25 },  /* s25 */
    [ARM64_REG_S26] = { REG_VEC26 },  /* s26 */
    [ARM64_REG_S27] = { REG_VEC27 },  /* s27 */
    [ARM64_REG_S28] = { REG_VEC28 },  /* s28 */
    [ARM64_REG_S29] = { REG_VEC29 },  /* s29 */
    [ARM64_REG_S30] = { REG_VEC30 },  /* s30 */
    [ARM64_REG_S31] = { REG_VEC31 },  /* s31 */
    [ARM64_REG_W0] = { REG_GPR0 },  /* w0 */
    [ARM64_REG_W1] = { REG_GPR1 },  /* w1 */
    [ARM64_REG_W2] = { REG_GPR2 },  /* w2 */
    [ARM64_REG_W3] = { REG_GPR3 },  /* w3 */
    [ARM64_REG_W4] = { REG_GPR4 },  /* w4 */
    [ARM64_REG_W5] = { REG_GPR5 },  /* w5 */
    [ARM64_REG_W6] = { REG_GPR6 },  /* w6 */
    [ARM64_REG_W7] = { REG_GPR7 },  /* w7 */
    [ARM64_REG_W8] = { REG_GPR8 },  /* w8 */
    [ARM64_REG_W9] = { REG_GPR9 },  /* w9 */
    [ARM64_REG_W10] = { REG_GPR10 },  /* w10 */
    [ARM64_REG_W11] = { REG_GPR11 },  /* w11 */
    [ARM64_REG_W12] = { REG_GPR12 },  /* w12 */
    [ARM64_REG_W13] = { REG_GPR13 },  /* w13 */
    [ARM64_REG_W14] = { REG_GPR14 },  /* w14 */
    [ARM64_REG_W15] = { REG_GPR15 },  /* w15 */
    [ARM64_REG_W16] = { REG_GPR16 },  /* w16 */
    [ARM64_REG_W17] = { REG_GPR17 },  /* w17 */
    [ARM64_REG_W18] = { REG_GPR18 },  /* w18 */
    [ARM64_REG_W19] = { REG_GPR19 },  /* w19 */
    [ARM64_REG_W20] = { REG_GPR20 },  /* w20 */
    [ARM64_REG_W21] = { REG_GPR21 },  /* w21 */
    [ARM64_REG_W22] = { REG_GPR22 },  /* w22 */
    [ARM64_REG_W23] = { REG_GPR23 },  /* w23 */
    [ARM64_REG_W24] = { REG_GPR24 },  /* w24 */
    [ARM64_REG_W25] = { REG_GPR25 },  /* w25 */
    [ARM64_REG_W26] = { REG_GPR26 },  /* w26 */
    [ARM64_REG_W27] = { REG_GPR27 },  /* w27 */
    [ARM64_REG_W28] = { REG_GPR28 },  /* w28 */
    [ARM64_REG_W29] = { REG_GPR29 },  /* w29 */
    [ARM64_REG_W30] = { REG_GPR30 },  /* w30 */
    [ARM64_REG_X0] = { REG_GPR0 },  /* x0 */
    [ARM64_REG_X1] = { REG_GPR1 },  /* x1 */
    [ARM64_REG_X2] = { REG_GPR2 },  /* x2 */
    [ARM64_REG_X3] = { REG_GPR3 },  /* x3 */
    [ARM64_REG_X4] = { REG_GPR4 },  /* x4 */
    [ARM64_REG_X5] = { REG_GPR5 },  /* x5 */
    [ARM64_REG_X6] = { REG_GPR6 },  /* x6 */
    [ARM64_REG_X7] = { REG_GPR7 },  /* x7 */
    [ARM64_REG_X8] = { REG_GPR8 },  /* x8 */
    [ARM64_REG_X9] = { REG_GPR9 },  /* x9 */
    [ARM64_REG_X10] = { REG_GPR10 },  /* x10 */
    [ARM64_REG_X11] = { REG_GPR11 },  /* x11 */
    [ARM64_REG_X12] = { REG_GPR12 },  /* x12 */
    [ARM64_REG_X13] = { REG_GPR13 },  /* x13 */
    [ARM64_REG_X14] = { REG_GPR14 },  /* x14 */
    [ARM64_REG_X15] = { REG_GPR15 },  /* x15 */
    [ARM64_REG_X16] = { REG_GPR16 },  /* x16 */
    [ARM64_REG_X17] = { REG_GPR17 },  /* x17 */
    [ARM64_REG_X18] = { REG_GPR18 },  /* x18 */
    [ARM64_REG_X19] = { REG_GPR19 },  /* x19 */
    [ARM64_REG_X20] = { REG_GPR20 },  /* x20 */
    [ARM64_REG_X21] = { REG_GPR21 },  /* x21 */
    [ARM64_REG_X22] = { REG_GPR22 },  /* x22 */
    [ARM64_REG_X23] = { REG_GPR23 },  /* x23 */
    [ARM64_REG_X24] = { REG_GPR24 },  /* x24 */
    [ARM64_REG_X25] = { REG_GPR25 },  /* x25 */
    [ARM64_REG_X26] = { REG_GPR26 },  /* x26 */
    [ARM64_REG_X27] = { REG_GPR27 },  /* x27 */
    [ARM64_REG_X28] = { REG_GPR28 },  /* x28 */
    [ARM64_REG_V0] = { REG_VEC0 },  /* v0 */
    [ARM64_REG_V1] = { REG_VEC1 },  /* v1 */
    [ARM64_REG_V2] = { REG_VEC2 },  /* v2 */
    [ARM64_REG_V3] = { REG_VEC3 },  /* v3 */
    [ARM64_REG_V4] = { REG_VEC4 },  /* v4 */
    [ARM64_REG_V5] = { REG_VEC5 },  /* v5 */
    [ARM64_REG_V6] = { REG_VEC6 },  /* v6 */
    [ARM64_REG_V7] = { REG_VEC7 },  /* v7 */
    [ARM64_REG_V8] = { REG_VEC8 },  /* v8 */
    [ARM64_REG_V9] = { REG_VEC9 },  /* v9 */
    [ARM64_REG_V10] = { REG_VEC10 },  /* v10 */
    [ARM64_REG_V11] = { REG_VEC11 },  /* v11 */
    [ARM64_REG_V12] = { REG_VEC12 },  /* v12 */
    [ARM64_REG_V13] = { REG_VEC13 },  /* v13 */
    [ARM64_REG_V14] = { REG_VEC14 },  /* v14 */
    [ARM64_REG_V15] = { REG_VEC15 },  /* v15 */
    [ARM64_REG_V16] = { REG_VEC16 },  /* v16 */
    [ARM64_REG_V17] = { REG_VEC17 },  /* v17 */
    [ARM64_REG_V18] = { REG_VEC18 },  /* v18 */
    [ARM64_REG_V19] = { REG_VEC19 },  /* v19 */
    [ARM64_REG_V20] = { REG_VEC20 },  /* v20 */
    [ARM64_REG_V21] = { REG_VEC21 },  /* v21 */
    [ARM64_REG_V22] = { REG_VEC22 },  /* v22 */
    [ARM64_REG_V23] = { REG_VEC23 },  /* v23 */
    [ARM64_REG_V24] = { REG_VEC24 },  /* v24 */
    [ARM64_REG_V25] = { REG_VEC25 },  /* v25 */
    [ARM64_REG_V26] = { REG_VEC26 },  /* v26 */
    [ARM64_REG_V27] = { REG_VEC27 },  /* v27 */
    [ARM64_REG_V28] = { REG_VEC28 },  /* v28 */
    [ARM64_REG_V29] = { REG_VEC29 },  /* v29 */
    [ARM64_REG_V30] = { REG_VEC30 },  /* v30 */
    [ARM64_REG_V31] = { REG_VEC31 },  /* v31 */
};

/* ARM64: 170/1289 classified, 1119 unknown */
static const InsnClassification arm64_insn_class[ARM64_INS_ENDING] = {
    [ARM64_INS_ADD]                 = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ADDP]                = { GEN_OP_VEC_ADD,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ADDS]                = { GEN_OP_INT_ADD,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ADR]                 = { GEN_OP_LEA,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ADRP]                = { GEN_OP_LEA,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_AND]                 = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ANDS]                = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ASR]                 = { GEN_OP_SAR,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_B]                   = { GEN_OP_BRANCH,    BRANCH_DIRECT_JUMP,   MF_NONE },
    [ARM64_INS_BFI]                 = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_BFXIL]               = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_BIC]                 = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_BICS]                = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_BIT]                 = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [ARM64_INS_BL]                  = { GEN_OP_CALL,      BRANCH_DIRECT_CALL,   MF_NONE },
    [ARM64_INS_BLR]                 = { GEN_OP_CALL,      BRANCH_INDIRECT_CALL, MF_NONE },
    [ARM64_INS_BR]                  = { GEN_OP_BRANCH,    BRANCH_INDIRECT_JUMP, MF_NONE },
    [ARM64_INS_BRK]                 = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [ARM64_INS_BTI]                 = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CAS]                 = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASA]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASAB]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASAH]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASAL]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASALB]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASALH]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASB]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASH]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASL]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASLB]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASLH]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASP]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASPA]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASPAL]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CASPL]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_CBNZ]                = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [ARM64_INS_CBZ]                 = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [ARM64_INS_CCMP]                = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CLZ]                 = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CMEQ]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CMHS]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CMN]                 = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CMP]                 = { GEN_OP_CMP,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CNEG]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CSEL]                = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CSET]                = { GEN_OP_SETCC,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CSINC]               = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CSINV]               = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_CSNEG]               = { GEN_OP_CMOV,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_DC]                  = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_DMB]                 = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_DSB]                 = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_DUP]                 = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_EON]                 = { GEN_OP_XOR,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_EOR]                 = { GEN_OP_XOR,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FADD]                = { GEN_OP_FP_ADD,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FCMP]                = { GEN_OP_FP_CMP,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FCVT]                = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FCVTZS]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FCVTZU]              = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FDIV]                = { GEN_OP_FP_DIV,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FMLS]                = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FMOV]                = { GEN_OP_FP_MOV,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FMUL]                = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FNMLS]               = { GEN_OP_FP_MUL,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FSQRT]               = { GEN_OP_FP_SQRT,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_FSUB]                = { GEN_OP_FP_SUB,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ISB]                 = { GEN_OP_FENCE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LD1]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDADD]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDA]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDAB]             = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDAH]             = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDAL]             = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDALB]            = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDALH]            = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDB]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDH]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDL]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDLB]             = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDADDLH]             = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDAR]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDARB]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDARH]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDAXR]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDAXRB]              = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDAXRH]              = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDNP]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDP]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDPSW]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDR]                 = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDRB]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDRH]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDRSB]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDRSH]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDRSW]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDUR]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDURB]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LDXR]                = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDXRB]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LDXRH]               = { GEN_OP_LOAD,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_LSL]                 = { GEN_OP_SHL,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_LSR]                 = { GEN_OP_SHR,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MADD]                = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MOV]                 = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MOVI]                = { GEN_OP_VEC_MOV,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MOVK]                = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MOVN]                = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MOVZ]                = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MRS]                 = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MSR]                 = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MSUB]                = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MUL]                 = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_MVN]                 = { GEN_OP_NOT,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_NEG]                 = { GEN_OP_NEG,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_NOP]                 = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ORN]                 = { GEN_OP_OR,        BRANCH_NONE,          MF_NONE },
    [ARM64_INS_ORR]                 = { GEN_OP_OR,        BRANCH_NONE,          MF_NONE },
    [ARM64_INS_RBIT]                = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_RET]                 = { GEN_OP_RET,       BRANCH_RETURN,        MF_NONE },
    [ARM64_INS_REV]                 = { GEN_OP_AND,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_SCVTF]               = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_SDIV]                = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STLR]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STLRB]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STLRH]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STLXR]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STLXRB]              = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STLXRH]              = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STNP]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STP]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STR]                 = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STRB]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STRH]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STUR]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STURB]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_STXR]                = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STXRB]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_STXRH]               = { GEN_OP_STORE,     BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SUB]                 = { GEN_OP_INT_SUB,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_SUBS]                = { GEN_OP_INT_SUB,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_SVC]                 = { GEN_OP_SYSCALL,   BRANCH_SYSCALL_TYPE,  MF_NONE },
    [ARM64_INS_SXTW]                = { GEN_OP_MOVSX,     BRANCH_NONE,          MF_NONE },
    [ARM64_INS_SWP]                 = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPA]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPAB]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPAH]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPAL]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPALB]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPALH]              = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPB]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPH]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPL]                = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPLB]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_SWPLH]               = { GEN_OP_XCHG,      BRANCH_NONE,          MF_ATOMIC },
    [ARM64_INS_TBNZ]                = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [ARM64_INS_TBZ]                 = { GEN_OP_BRANCH,    BRANCH_COND_DIRECT,   MF_CONDITIONAL },
    [ARM64_INS_TST]                 = { GEN_OP_TEST,      BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UBFIZ]               = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UBFX]                = { GEN_OP_MOV,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UCVTF]               = { GEN_OP_FP_CVT,    BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UDF]                 = { GEN_OP_NOP,       BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UDIV]                = { GEN_OP_INT_DIV,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UMADDL]              = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UMAX]                = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UMAXP]               = { GEN_OP_VEC_LOGIC, BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UMLAL2]              = { GEN_OP_VEC_MUL,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UMULH]               = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_UMULL]               = { GEN_OP_INT_MUL,   BRANCH_NONE,          MF_NONE },
    [ARM64_INS_USUBL2]              = { GEN_OP_VEC_SUB,   BRANCH_NONE,          MF_NONE },
};

#endif /* WPTRACE_MNEMONICS_AARCH64_H */
