"""
Guests whose WRONG PATH is worth measuring.

The correct-path probe set (``../probes/mkprobes.py``) covers the ISA classes
the validator's generator never reaches, but it covers them on the CORRECT
path: most of those probes are straight-line, so they kick no excursion at all
and the wrong-path leg sees nothing from them.  Measured, at wpdepth=16 over
the seven of them: p_flow contributes 19 excursions, p_atomic 1, and the other
five contribute NONE.

An axis with no instance of its fact in any excursion cannot be proven to
fire, and an unfirable axis agrees forever.  These guests exist so the memory,
FP and vector axes have wrong-path instances to be measured on: every class
sits in the SHADOW of a conditional branch, which is exactly where the tracer's
wrong-path walker goes.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

HEAD = """\
# GENERATED by probes_wp.py -- ARC 3 riscv64 wrong-path probe
.section .data
.balign 64
.globl arena
arena:
"""

TAIL = """
.globl done
done:
  li a7, 93
  li a0, 0
  ecall
"""


def arena(n=96, seed=0x51ED):
    out, v = [], seed
    for _i in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .quad 0x%016x' % v)
    return '\n'.join(out) + '\n'


PROBES = {}

# The loop is taken nine times, so every excursion the walker kicks off the
# `blt` runs the FALL-THROUGH -- which is where every memory, FP and vector
# class below sits.  Sub-word loads and stores are included deliberately: a
# width the wire states wrongly is invisible on a full-width access.
PROBES['p_wpmem'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0
  li    t1, 10
  li    t2, 0
loop:
  ld    t3, 0(t6)
  add   t2, t2, t3
  addi  t0, t0, 1
  blt   t0, t1, loop
shadow:
  lb    a0, 8(t6)
  lh    a1, 10(t6)
  lw    a2, 12(t6)
  lbu   a3, 9(t6)
  lhu   a4, 14(t6)
  lwu   a5, 16(t6)
  sb    a0, 256(t6)
  sh    a1, 258(t6)
  sw    a2, 260(t6)
  sd    a3, 264(t6)
  fld   ft0, 24(t6)
  fld   ft1, 32(t6)
  fadd.d ft2, ft0, ft1
  fmul.d ft3, ft0, ft1
  fsd   ft2, 272(t6)
  flw   fa0, 40(t6)
  fsw   fa0, 280(t6)
  vsetivli t4, 2, e64, m1, ta, ma
  vle64.v v1, (t6)
  vadd.vv v2, v1, v1
  vmul.vv v3, v2, v1
  addi  t5, t6, 288
  vse64.v v3, (t5)
  j     done
"""

# A second shape: the branch is BACKWARD-taken and its shadow is a chain of
# dependent loads, so the excursion's addresses depend on data the trace must
# have reconstructed.  A reconstruction that silently zeroes a register would
# produce a different address here and nowhere else.
PROBES['p_wpchain'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0
  li    t1, 8
  li    t2, 0
  addi  s1, t6, 64
chain:
  ld    t3, 0(s1)
  andi  t3, t3, 0x1f8
  add   t4, t6, t3
  ld    a0, 0(t4)
  addi  t0, t0, 1
  bltu  t0, t1, chain
tail:
  ld    a1, 0(t4)
  add   a2, a1, a0
  sd    a2, 320(t6)
  ld    a3, 320(t6)
  xor   a4, a3, a2
  sd    a4, 328(t6)
  lw    a5, 328(t6)
  sw    a5, 336(t6)
  j     done
"""


def build(outdir, cc='riscv64-linux-gnu-gcc',
          march='rv64gcv_zicsr_zifencei'):
    os.makedirs(outdir, exist_ok=True)
    made = []
    for name, body in sorted(PROBES.items()):
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD)
            fh.write(arena())
            fh.write(body)
            fh.write(TAIL)
        elf = os.path.join(outdir, name)
        cmd = [cc, '-march=' + march, '-mabi=lp64d', '-static', '-nostdlib',
               '-nostartfiles', '-e', '_start', '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            sys.stderr.write('FAILED %s:\n%s\n'
                             % (name, p.stdout.decode('utf-8', 'replace')))
            continue
        made.append(elf)
    return made


if __name__ == '__main__':
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'build')
    for e in build(out):
        print(e)
