"""
Generate the riscv64 EXECUTION probes.

The validator's own riscv64 generator emits a deliberately narrow vocabulary
(add / beqz / ecall / ld / li / lla / ret / sd / xor).  Agreement measured only
over that vocabulary would be a real result about a small part of the ISA, and
quoting it as an ISA-wide one would be the survivorship bias this project has
been caught by before.  These probes execute the classes it never reaches --
sub-word memory, M, A, F/D, V, and the compressed and control-transfer forms --
so the execution leg's numbers cover them too.

Each probe is a static -nostdlib ELF with the same shape as a validator guest,
so nothing in the comparison pipeline needs a special case for it.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

HEAD = """\
# GENERATED by mkprobes.py -- ARC 3 riscv64 execution probe
.section .data
.balign 64
.globl arena
arena:
"""

TAIL = """
.globl done
done:
  li a7, 93
  li a0, 0
  ecall
"""


def arena(n=64, seed=0x1234):
    out = []
    v = seed
    for i in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .quad 0x%016x' % v)
    return '\n'.join(out) + '\n'


PROBES = {}

# ---------------------------------------------------------------- integer
PROBES['p_int'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0x123456789abcdef0
  li    t1, 0x0fedcba987654321
  add   t2, t0, t1
  sub   t3, t0, t1
  and   t4, t0, t1
  or    t5, t0, t1
  xor   a0, t0, t1
  sll   a1, t0, 7
  srl   a2, t0, 9
  sra   a3, t0, 11
  slt   a4, t0, t1
  sltu  a5, t0, t1
  addw  a6, t0, t1
  subw  a7, t0, t1
  sllw  s2, t0, 3
  srlw  s3, t0, 5
  sraw  s4, t0, 6
  slti  s5, t0, 100
  andi  s6, t0, 0x7f
  ori   s7, t0, 0x11
  xori  s8, t0, 0x22
  slli  s9, t0, 13
  srli  s10, t0, 17
  srai  s11, t0, 19
  lui   t0, 0xabcde
  auipc t1, 0x3
  sd    t2, 0(t6)
  sd    t3, 8(t6)
  sd    t4, 16(t6)
"""

# --------------------------------------------------------- sub-word memory
PROBES['p_mem'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0x0123456789abcdef
  sd    t0, 0(t6)
  lb    t1, 0(t6)
  lbu   t2, 1(t6)
  lh    t3, 2(t6)
  lhu   t4, 4(t6)
  lw    t5, 4(t6)
  lwu   a0, 0(t6)
  ld    a1, 0(t6)
  sb    t1, 64(t6)
  sh    t3, 66(t6)
  sw    t5, 68(t6)
  sd    a1, 72(t6)
  lb    a2, 64(t6)
  lh    a3, 66(t6)
  lw    a4, 68(t6)
  ld    a5, 72(t6)
  li    t0, 0xff
  sb    t0, 65(t6)
  lbu   a6, 65(t6)
  # unaligned-capable forms, still naturally aligned here
  lw    a7, 80(t6)
  sw    a7, 84(t6)
"""

# ---------------------------------------------------------------- M and A
PROBES['p_muldiv'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0x00000000deadbeef
  li    t1, 0x0000000000001337
  mul   t2, t0, t1
  mulh  t3, t0, t1
  mulhu t4, t0, t1
  mulhsu t5, t0, t1
  div   a0, t0, t1
  divu  a1, t0, t1
  rem   a2, t0, t1
  remu  a3, t0, t1
  mulw  a4, t0, t1
  divw  a5, t0, t1
  divuw a6, t0, t1
  remw  a7, t0, t1
  remuw s2, t0, t1
  li    t2, -1
  li    t3, 0
  div   s3, t2, t3        # division by zero: architectural, not a trap
  rem   s4, t2, t3
  divu  s5, t2, t3
  remu  s6, t2, t3
  sd    s3, 0(t6)
"""

PROBES['p_atomic'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0x1111222233334444
  sd    t0, 0(t6)
  li    t1, 0x0000000000000007
  amoadd.d  t2, t1, (t6)
  amoswap.d t3, t1, (t6)
  amoor.d   t4, t1, (t6)
  amoand.d  t5, t1, (t6)
  amoxor.d  a0, t1, (t6)
  amomin.d  a1, t1, (t6)
  amomax.d  a2, t1, (t6)
  amominu.d a3, t1, (t6)
  amomaxu.d a4, t1, (t6)
  amoadd.w  a5, t1, (t6)
  amoswap.w a6, t1, (t6)
1:
  lr.d   a7, (t6)
  addi   a7, a7, 1
  sc.d   s2, a7, (t6)
  bnez   s2, 1b
  fence  rw, rw
  fence.i
"""

# ------------------------------------------------------------------ F / D
PROBES['p_fp'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0x3f800000
  li    t1, 0x40400000
  fmv.w.x  ft0, t0
  fmv.w.x  ft1, t1
  fadd.s   ft2, ft0, ft1
  fsub.s   ft3, ft0, ft1
  fmul.s   ft4, ft0, ft1
  fdiv.s   ft5, ft0, ft1      # inexact: sets fflags
  fsqrt.s  ft6, ft1
  fmin.s   ft7, ft0, ft1
  fmax.s   fs0, ft0, ft1
  fmadd.s  fs1, ft0, ft1, ft2
  fmsub.s  fs2, ft0, ft1, ft2
  fnmadd.s fs3, ft0, ft1, ft2
  fsgnj.s  fs4, ft0, ft1
  fsgnjn.s fs5, ft0, ft1
  fsgnjx.s fs6, ft0, ft1
  fcvt.d.s fs7, ft0
  fadd.d   fs8, fs7, fs7
  fdiv.d   fs9, fs7, fs8
  fcvt.w.s a0, ft2
  fcvt.wu.s a1, ft2
  fcvt.l.s a2, ft2
  fcvt.s.w ft8, a0
  fcvt.s.l ft9, a2
  feq.s    a3, ft0, ft1
  flt.s    a4, ft0, ft1
  fle.s    a5, ft0, ft1
  fclass.s a6, ft0
  fmv.x.w  a7, ft2
  fsw   ft2, 0(t6)
  flw   ft10, 0(t6)
  fsd   fs7, 8(t6)
  fld   ft11, 8(t6)
  frflags s2
  frrm    s3
  fsrm    s4, x0
  csrr    s5, fcsr
"""

# ---------------------------------------------------------------------- V
PROBES['p_vec'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 4
  vsetvli t1, t0, e64, m1, ta, ma
  vle64.v v1, (t6)
  addi  t2, t6, 32
  vle64.v v2, (t2)
  vadd.vv  v3, v1, v2
  vsub.vv  v4, v1, v2
  vand.vv  v5, v1, v2
  vor.vv   v6, v1, v2
  vxor.vv  v7, v1, v2
  vmul.vv  v8, v1, v2
  vadd.vi  v9, v1, 5
  vadd.vx  v10, v1, t0
  vsll.vi  v11, v1, 3
  vsrl.vi  v12, v1, 2
  vmseq.vv v0, v1, v2
  vadd.vv  v13, v1, v2, v0.t
  vredsum.vs v14, v1, v2
  addi  t3, t6, 128
  vse64.v v3, (t3)
  addi  t4, t6, 192
  vse64.v v8, (t4)
  vsetvli t5, t0, e32, m1, ta, ma
  vle32.v v15, (t6)
  vadd.vv v16, v15, v15
  vse32.v v16, (t3)
"""

# -------------------------------------------------- fcsr fold, frm non-zero
#
# The tracer folds fflags (0x001), frm (0x002) and fcsr (0x003) onto one
# GenericRegId, REG_FCSR.  Every other probe leaves frm at 0, and while frm is
# 0 the three registers hold the same bits, so a fold that publishes the wrong
# member's value agrees with the reference on every row.  A corpus that cannot
# distinguish them has not tested them.
#
# This probe sets frm to a non-zero value FIRST, so fcsr (0x21) and fflags
# (0x01) and frm (0x01) are three different numbers, and then reads fcsr back
# with csrr after every write.  The readback is the discriminator: the wire's
# REG_FCSR snapshots and the guest's own csrr result must agree, and a
# consumer replaying destination snapshots forward is exactly what checks it.
PROBES['p_fcsr'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0x3f800000
  li    t1, 0x40400000
  fmv.w.x  ft0, t0
  fmv.w.x  ft1, t1
  li    t2, 1
  fsrm  s0, t2            # frm <- 1 (RTZ); s0 = old frm (0)
  csrr  s1, fcsr          # 0x20  -- frm=1, fflags=0
  fdiv.s ft5, ft0, ft1    # inexact: fflags |= NX
  csrr  s2, fcsr          # 0x21
  csrr  s3, fflags        # 0x01
  csrr  s4, frm           # 0x01
  li    t3, 0x18
  csrw  fflags, t3        # fflags <- 0x18
  csrr  s5, fcsr          # 0x38
  csrr  s6, fflags        # 0x18
  li    t4, 0x00
  csrw  fcsr, t4          # fcsr <- 0
  csrr  s7, fcsr          # 0x00
  csrr  s8, frm           # 0x00
"""

# ------------------------------------------- control transfer + compressed
PROBES['p_flow'] = """
.section .text
.globl _start
_start:
  lla   t6, arena
  li    t0, 0
  li    t1, 10
  li    t2, 0
loop:
  ld    t3, 0(t6)
  add   t2, t2, t3
  addi  t0, t0, 1
  blt   t0, t1, loop
  bge   t0, t1, 1f
  li    t4, 0xbad
1:
  beq   t0, t1, 2f
  li    t4, 0xbad
2:
  bne   t0, t2, 3f
  li    t4, 0xbad
3:
  bltu  t0, t1, 4f
  bgeu  t0, t1, 4f
4:
  jal   ra, leaf
  lla   t5, leaf
  jalr  ra, 0(t5)
  c.li  a0, 3
  c.addi a0, 7
  c.slli a0, 2
  c.mv  a1, a0
  c.add a1, a0
  mv    s0, t6            # c.ld/c.sd need an x8-x15 base
  c.ld  a2, 0(s0)
  c.sd  a2, 16(s0)
  c.j   5f
5:
  sd    t2, 24(t6)
  j     done
leaf:
  addi  a3, a3, 1
  ret
"""


def build(outdir, cc='riscv64-linux-gnu-gcc',
          march='rv64gcv_zicsr_zifencei'):
    os.makedirs(outdir, exist_ok=True)
    made = []
    for name, body in sorted(PROBES.items()):
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD)
            fh.write(arena())
            fh.write(body)
            fh.write(TAIL)
        elf = os.path.join(outdir, name)
        cmd = [cc, '-march=' + march, '-mabi=lp64d', '-static', '-nostdlib',
               '-nostartfiles', '-e', '_start', '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            sys.stderr.write('FAILED %s:\n%s\n'
                             % (name, p.stdout.decode('utf-8', 'replace')))
            continue
        made.append(elf)
    return made


if __name__ == '__main__':
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'build')
    for e in build(out):
        print(e)
