"""
Guests whose WRONG PATH is worth measuring, for the mipsel gem5 leg.

The correct-path probe set (``gem5/probes/mkprobes_mipsel.py``) covers ISA
classes on the CORRECT path, and that is a different question: an excursion is
only kicked where a branch's OTHER side was translated and run, so a
straight-line guest contributes nothing at all.  Measured at ``wpdepth=16``
over the four correct-path probes, only ``p_flow`` kicks excursions; ``p_int``,
``p_mem`` and ``p_fp`` kick none, which left the memop, FP and accumulator axes
with NO MUTATION AVAILABLE in the negative control.  An axis with no mutation
is an axis whose zero proves nothing, so these guests exist to put those facts
in a branch shadow.

Construction rule, identical to the correct-path set: static ``-nostdlib``
non-PIE ELFs whose data lives in a fixed-address ``.data`` arena, so an
effective address is a link-time fact both simulators must agree on rather
than a property of how each lays out a process.  ``.set noreorder`` throughout,
because a delay slot the assembler filled is an instruction nobody wrote and
the comparison would have to explain.

WHAT EACH ONE PUTS IN THE SHADOW
================================
``p_wpmem``   sub-word loads and stores, the unaligned ``lwl``/``lwr`` pair,
              and a store whose datum comes from a register the reconstruction
              had to get right.
``p_wpfp``    single- and double-precision arithmetic plus ``lwc1``/``swc1``,
              so the FP file has to survive the injection prologue.
``p_wpacc``   ``mult``/``div``/``madd`` and the ``mfhi``/``mflo`` reads, which
              is where gem5's own accumulator silence shows up.
``p_wpchain`` a DEPENDENT-LOAD chain: the excursion's addresses depend on data
              the reconstruction supplied, so an agreement on ``memop-addr``
              is evidence the state really arrived.
``p_wpll``    ``ll``/``sc``, the store-conditional QEMU lowers onto a
              compare-exchange.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CC = 'mipsel-linux-gnu-gcc'

HEAD = """\
// GENERATED by probes_wp_mipsel.py -- ARC 3 mipsel wrong-path probe
.set noreorder
.set noat
.section .data
.balign 64
.globl arena
arena:
"""

TAIL = """
.globl done
done:
  li   $v0, 4001
  li   $a0, 0
  syscall
  nop
"""

PRO = """
.section .text
.globl _start
_start:
  lui  $s0, %hi(arena)
  addiu $s0, $s0, %lo(arena)
"""


def arena(n=192, seed=0x5eed):
    out, v = [], seed
    for _ in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .word 0x%08x' % (v & 0xffffffff))
    return '\n'.join(out) + '\n'


PROBES = {}

# The shadow of a taken loop branch: the NOT-taken side holds the memory work.
PROBES['p_wpmem'] = """
  li   $t0, 0
  li   $t1, 3
mloop:
  addiu $t0, $t0, 1
  bne  $t0, $t1, mloop
  nop
  lb   $t2, 8($s0)
  lbu  $t3, 9($s0)
  lh   $t4, 10($s0)
  lhu  $t5, 12($s0)
  lwl  $t6, 3($s0)
  lwr  $t6, 0($s0)
  sb   $t2, 260($s0)
  sh   $t4, 262($s0)
  sw   $t6, 264($s0)
  swl  $t6, 271($s0)
  swr  $t6, 268($s0)
  lw   $t7, 264($s0)
  sw   $t7, 276($s0)
  nop
"""

PROBES['p_wpfp'] = """
  li   $t0, 0
  li   $t1, 3
floop:
  addiu $t0, $t0, 1
  bne  $t0, $t1, floop
  nop
  lwc1 $f0, 0($s0)
  lwc1 $f2, 4($s0)
  ldc1 $f4, 8($s0)
  ldc1 $f6, 16($s0)
  add.s $f8, $f0, $f2
  mul.s $f10, $f0, $f2
  sub.s $f12, $f0, $f2
  add.d $f16, $f4, $f6
  mul.d $f18, $f4, $f6
  abs.s $f20, $f0
  neg.s $f22, $f0
  mov.s $f24, $f0
  swc1 $f8, 288($s0)
  sdc1 $f16, 296($s0)
  mfc1 $t2, $f8
  mtc1 $t2, $f26
  nop
"""

PROBES['p_wpacc'] = """
  li   $t0, 0
  li   $t1, 3
aloop:
  addiu $t0, $t0, 1
  bne  $t0, $t1, aloop
  nop
  lw   $t2, 32($s0)
  lw   $t3, 36($s0)
  mult $t2, $t3
  mfhi $t4
  mflo $t5
  multu $t2, $t3
  mfhi $t6
  madd $t2, $t3
  mflo $t7
  msub $t2, $t3
  mfhi $t8
  mthi $t4
  mtlo $t5
  div  $zero, $t2, $t3
  mflo $t9
  mul  $s1, $t2, $t3
  nop
"""

# The excursion's own addresses depend on data the reconstruction supplied:
# an agreement on memop-addr here is evidence the state really arrived.
PROBES['p_wpchain'] = """
  li   $t0, 0
  li   $t1, 3
cloop:
  addiu $t0, $t0, 1
  bne  $t0, $t1, cloop
  nop
  lw   $t2, 64($s0)
  andi $t2, $t2, 0x3c
  addu $t3, $s0, $t2
  lw   $t4, 0($t3)
  andi $t4, $t4, 0x3c
  addu $t5, $s0, $t4
  lw   $t6, 4($t5)
  andi $t6, $t6, 0x38
  addu $t7, $s0, $t6
  sw   $t6, 320($t7)
  lw   $t8, 320($t7)
  nop
"""

PROBES['p_wpll'] = """
  li   $t0, 0
  li   $t1, 3
lloop2:
  addiu $t0, $t0, 1
  bne  $t0, $t1, lloop2
  nop
  ll   $t2, 400($s0)
  addiu $t2, $t2, 1
  sc   $t2, 400($s0)
  lw   $t3, 400($s0)
  pref 0, 416($s0)
  synci 0($s0)
  nop
"""


def build(outdir):
    os.makedirs(outdir, exist_ok=True)
    made, failed = [], []
    for name, body in PROBES.items():
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD + arena() + PRO + body + TAIL)
        elf = os.path.join(outdir, name)
        cmd = [CC, '-EL', '-nostdlib', '-nostartfiles', '-static',
               '-no-pie', '-mno-abicalls', '-fno-pic', '-march=mips32r2',
               '-mfp32', '-Wl,--build-id=none', '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            failed.append((name, p.stdout.decode('utf-8', 'replace')))
        else:
            made.append(elf)
    return made, failed


if __name__ == '__main__':
    made, failed = build(sys.argv[1] if len(sys.argv) > 1
                         else os.path.join(HERE, 'probes'))
    for n, err in failed:
        sys.stderr.write('FAILED %s\n%s\n' % (n, err))
    print('\n'.join(made))
    sys.exit(1 if failed else 0)
