#!/usr/bin/env python3
#
# A target's adjudicated helper-argument directions, as a table the reader
# joins against the compiler's own view of the same helpers.
#
# The reader meets a helper call as one edge and an argument that points into
# CPUArchState as a register it cannot name.  The DECLARED TYPE gives the
# extent -- `Reg *` is one vector register and sizeof says how big -- and the
# compiler produces that half without help.  The DIRECTION is not in the type:
# a pointer is a pointer, and whether the helper reads through it, writes
# through it or both is a fact about the helper's body.  That half is
# adjudicated, one reviewable row per helper, and this script turns the rows
# into the array the target installs.
#
# It refuses rather than emitting a table nobody can check:
#
#   * a row with no reason does not generate -- an adjudication whose ground
#     is not written down is an assertion
#   * a direction string with a character outside "-rwb" does not generate
#   * a duplicated helper name does not generate
#
# The other half of the refusal -- a helper with a register pointer and no
# row, and a row naming no such helper -- cannot be checked here, because
# only the compiler knows which arguments are register pointers.  It is
# checked where both halves meet, in insn_dataflow_declare_helper_usage().
#
# Author: Maccoy Merrell
#
# SPDX-License-Identifier: GPL-2.0-or-later

import argparse
import sys

DIRCHARS = set("-rwb")


def read_rows(path):
    rows = []
    seen = {}
    bad = 0
    with open(path) as f:
        for n, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 3:
                print("%s:%d: a row is name, directions, reason" % (path, n),
                      file=sys.stderr)
                bad += 1
                continue
            name, dirs, reason = parts[0].strip(), parts[1].strip(), \
                "\t".join(parts[2:]).strip()
            if not reason:
                print("%s:%d: %s has no reason; an adjudication whose ground "
                      "is not written down is an assertion"
                      % (path, n, name), file=sys.stderr)
                bad += 1
            if set(dirs) - DIRCHARS or not dirs:
                print("%s:%d: %s: directions %r are not a string over -rwb"
                      % (path, n, name, dirs), file=sys.stderr)
                bad += 1
            if name in seen:
                print("%s:%d: %s already adjudicated at line %d"
                      % (path, n, name, seen[name]), file=sys.stderr)
                bad += 1
            seen[name] = n
            rows.append((name, dirs, reason))
    if bad:
        sys.exit("insn-df-usage: %d refused row(s)" % bad)
    return rows


def main():
    ap = argparse.ArgumentParser(
        description="a target's adjudicated helper-argument directions")
    ap.add_argument("tsv")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--symbol", default="insn_df_helper_dirs")
    args = ap.parse_args()

    rows = sorted(read_rows(args.tsv), key=lambda r: r[0])
    out = ["/* Generated by scripts/insn-df-usage.py from %s.  Do not edit. */"
           % args.tsv,
           "",
           "static const InsnDfHelperDir %s[] = {" % args.symbol]
    for name, dirs, _reason in rows:
        out.append('    { "%s", "%s" },' % (name, dirs))
    out.append("};")
    out.append("")
    with open(args.output, "w") as f:
        f.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
