#!/usr/bin/env python3
#
# Export QEMU's own decode identity from the x87 escape space.
#
# The i386 decode table gives each of the eight escape opcodes 0xD8..0xDF
# ONE X86_OP_ENTRY row, and the identity a plugin sees is that row's
# __LINE__.  gen_x87() then dispatches INTERNALLY, on the modrm byte, to
# well over a hundred architectural instructions.  So eight identities
# answer for the whole x87 instruction set, and a row that names one of
# them names it for all the others too:
#
#     champsim_tracer_qemu_ident_x86.h:1728
#       { 0x00000773u, "x87", QID_OBSERVED, ... .opcode = GEN_OP_FP_ADD }
#
#     -- 0x773 is decode-new.c.inc:1907, the 0xD8 row.  It says FP_ADD
#        because the corpus that promoted it contained an `fadds`.  A
#        held-out program reached the same rule 14 times with `fdivs`.
#
# The row is not wrong about the rule.  The RULE is too coarse to be
# right about the instruction, and no amount of further observation can
# fix that: the discriminator never reaches the decode table at all.
#
# This script states the finer identity in the source, mechanically, the
# way scripts/mips_ident_instrument.py states MIPS's execution hints:
#
#   * it PARSES gen_x87's own switches out of target/i386/tcg/translate.c
#     -- the memory-operand switch under `mod != 3` and the register
#     switch under its `else` -- expands every case label into the op
#     values it covers, and finds the inner `switch (rm)` groups where
#     the encoding's rm field is a further dispatch rather than an ST(i)
#     operand index;
#
#   * it emits target/i386/tcg/x87_ident.c.inc: one identity row per
#     dispatch leaf, named `decode-new/x87@<16 fixed bits>` over the
#     (opcode byte, modrm byte) pair the dispatch reads, with the id the
#     FNV-1a-32 of that name -- the derivation scripts/decodetree.py and
#     the MIPS leg both use;
#
#   * it inserts ONE call into gen_x87, on the path that RETURNS rather
#     than the one that jumps to illegal_op, so an encoding QEMU refused
#     publishes nothing and keeps the escape row's own identity.
#
# THE BASE ROWS DO NOT MOVE.  decode-new.c.inc is not touched, the eight
# escape slots keep their ids and their name "x87", and an encoding that
# matches no leaf still reports them, bit for bit.
#
# ALL FORMS ARE QUALIFIED, not just the ones a corpus happened to reach.
# The OPC_SLL lesson: carving out the observed form alone would leave the
# base row claiming to be an `fadd` for every x87 instruction that is not
# one -- an identity answering confidently and wrongly, which is worse
# than the split it replaces.  The leaves come from QEMU's own switch, so
# the set is complete by construction and the generator refuses any case
# label it cannot model rather than skipping it.
#
# THE NAME'S DON'T-CARE BITS ARE ORDERED, exactly as decodetree's are.
# A memory-operand leaf is reached for mod = 00, 01 and 10 and not for
# 11, which no single mask can say; the register leaves carry `11` in the
# mod field and are matched FIRST, so the memory leaf's `..` means "what
# the more specific rows did not claim".  That is the convention
# `decode_insn16/addi@000...........01` already reads under.  The
# generated selector is checked EXHAUSTIVELY over all 2048 encodings of
# the escape space against the parsed dispatch model, so the ordering is
# proven rather than asserted.
#
# Author: Maccoy Merrell

import argparse
import os
import re
import sys

FUNC = 'static void gen_x87(DisasContext *s, X86DecodedInsn *decode)'
MARK = 'x87_ident_publish(b, modrm);'
FT_TAG = '  /* x87_ident */'
GEN_BY = 'Auto-generated by scripts/x86_x87_ident_instrument.py'

# The escape opcodes the table routes to gen_x87.  Read from the decode
# table rather than hard-coded: a row moving would otherwise be silently
# missed.  See read_escape_bytes().
ESCAPE_RE = re.compile(r'^\s*\[0x([Dd][89A-Fa-f])\]\s*=\s*X86_OP_ENTRY1\(x87,')


def fnv1a32(text):
    """FNV-1a 32 of TEXT, with 0 remapped to 1.

       Identical derivation to scripts/decodetree.py's ident_hash() and to
       the MIPS leg's, so every identity in this tree is made the same
       way.  0 is reserved by the plugin API for 'no identity recorded'."""
    h = 0x811c9dc5
    for byte in text.encode('utf-8'):
        h = ((h ^ byte) * 0x01000193) & 0xffffffff
    return h if h else 1


def strip_for_structure(lines):
    """Blank out comments and string/character literals.

       Returns a parallel list: index i is line i with everything that must
       not be read as C structure removed.  Preprocessor lines come back
       blank -- gen_x87 has none, and a directive that appeared would be
       reported as unmodelled rather than silently read as code."""
    out = []
    in_block = False
    for raw in lines:
        s = raw
        res = []
        i = 0
        if in_block:
            end = s.find('*/')
            if end < 0:
                out.append('')
                continue
            s = s[end + 2:]
            in_block = False
        while i < len(s):
            c = s[i]
            if c == '/' and s[i:i + 2] == '/*':
                end = s.find('*/', i + 2)
                if end < 0:
                    in_block = True
                    break
                i = end + 2
                continue
            if c == '/' and s[i:i + 2] == '//':
                break
            if c in '"\'':
                q = c
                i += 1
                while i < len(s):
                    if s[i] == '\\':
                        i += 2
                        continue
                    if s[i] == q:
                        i += 1
                        break
                    i += 1
                continue
            res.append(c)
            i += 1
        line = ''.join(res)
        if line.lstrip().startswith('#'):
            line = ''
        out.append(line)
    return out


CASE_RE = re.compile(r'^\s*case\s+(.+?)\s*:\s*$')
DEFAULT_RE = re.compile(r'^\s*default\s*:\s*$')
# Several labels may share one line -- `case 0x00: case 0x01: case 0x04 ... 0x07:`
# is one line in gen_x87's register switch.  Reading only the last of them
# would drop two whole instructions from the model, so the line is split.
LINE_LABELS_RE = re.compile(r'\s*(case\s+[^:]+|default)\s*:')
SWITCH_RE = re.compile(r'^\s*switch\s*\((.*)\)\s*\{\s*$')
RANGE_RE = re.compile(r'^(0x[0-9a-fA-F]+|\d+)\s*\.\.\.\s*(0x[0-9a-fA-F]+|\d+)$')
CONST_RE = re.compile(r'^(0x[0-9a-fA-F]+|\d+)$')


def line_labels(clean_line):
    """The case/default labels a line carries, or None if it is not a pure
       label line.  Returns a list whose entries are the label text, or None
       for `default`."""
    if not clean_line.strip():
        return None
    pos = 0
    out = []
    for m in LINE_LABELS_RE.finditer(clean_line):
        if m.start() != pos:
            return None
        pos = m.end()
        tok = m.group(1).strip()
        out.append(None if tok == 'default'
                   else tok[len('case'):].strip())
    if not out or clean_line[pos:].strip():
        return None
    return out


def label_values(label):
    """The integer constants one `case` label covers, or None if it is not
       a plain constant / constant range.  gen_x87 uses nothing else, and
       anything else is reported rather than guessed at."""
    m = RANGE_RE.match(label)
    if m:
        lo, hi = int(m.group(1), 0), int(m.group(2), 0)
        if lo > hi:
            return None
        return list(range(lo, hi + 1))
    m = CONST_RE.match(label)
    if m:
        return [int(m.group(1), 0)]
    return None


def find_function(lines, clean):
    """(first, last) line indices of gen_x87's body braces."""
    start = None
    for i, l in enumerate(lines):
        if l.startswith(FUNC):
            start = i
            break
    if start is None:
        raise SystemExit('gen_x87 not found -- the scanner does not fit this '
                         'source, and an empty model would read as "x87 has '
                         'no internal dispatch"')
    depth = 0
    seen = False
    for i in range(start, len(lines)):
        depth += clean[i].count('{') - clean[i].count('}')
        if clean[i].count('{'):
            seen = True
        if seen and depth == 0:
            return start, i
    raise SystemExit('gen_x87 has no closing brace')


def scan_switch(lines, clean, open_idx, end_idx):
    """Parse ONE switch statement whose `switch (...) {` is at open_idx.

       Returns (expr, groups, close_idx).  A group is
       {'labels': [text...], 'has_default': bool, 'body': (a, b)} where the
       body span is exclusive of the label lines."""
    m = SWITCH_RE.match(clean[open_idx])
    expr = m.group(1).strip()
    depth = 1
    groups = []
    cur = None
    i = open_idx + 1
    while i <= end_idx:
        c = clean[i]
        if depth == 1:
            labs = line_labels(c)
            if labs is not None:
                if cur is None or cur['body_started']:
                    cur = {'labels': [], 'has_default': False,
                           'start': i, 'end': i, 'body_started': False}
                    groups.append(cur)
                for lab in labs:
                    if lab is None:
                        cur['has_default'] = True
                    else:
                        # The LINE is part of the label.  A group's labels
                        # are spread over several lines and each line
                        # carries QEMU's own word for the values on it --
                        # reading only the group's first comment names
                        # `flds` for fsts, fstps, fildl and eleven more.
                        cur['labels'].append((lab, i))
                cur['end'] = i
                i += 1
                continue
            if c.strip() and cur is not None:
                cur['body_started'] = True
        depth += c.count('{') - c.count('}')
        if depth == 0:
            for g in groups:
                g['body'] = (g['end'] + 1,
                             (groups[groups.index(g) + 1]['start'] - 1
                              if groups.index(g) + 1 < len(groups) else i - 1))
            return expr, groups, i
        i += 1
    raise SystemExit('unterminated switch at line %d' % (open_idx + 1))


def body_text(lines, span):
    return '\n'.join(lines[span[0]:span[1] + 1])


def is_illegal_only(lines, clean, span):
    """A group whose whole body is `goto illegal_op;` -- QEMU refuses the
       encoding, so there is no decode to publish."""
    stmts = [c.strip() for c in clean[span[0]:span[1] + 1] if c.strip()]
    return stmts == ['goto illegal_op;']


def inner_rm_switch(lines, clean, span):
    """The line index of a `switch (rm) {` heading this group's body, or
       None.  `switch (op & 7)` / `switch (op >> 4)` are dispatches on the
       SAME value the outer switch already keyed on, so they refine nothing
       the identity does not already carry; `switch (rm)` reads a field the
       outer switch never saw and is the second half of the key."""
    found = None
    for i in range(span[0], span[1] + 1):
        m = SWITCH_RE.match(clean[i])
        if not m:
            continue
        if m.group(1).strip() == 'rm':
            if found is None:
                found = i
            continue
        # An inner switch on something else is fine as long as it is not
        # an rm dispatch we would then mis-model.  Recorded for the report.
    return found


def model(path_c):
    """Parse gen_x87 into leaves.

       A leaf is (mem, op, rm) with rm None where the encoding's rm field
       is an operand rather than a dispatch.  Also returns the residue:
       every case label not modelled, by line."""
    with open(path_c) as f:
        lines = f.read().split('\n')
    lines, _ = strip_instrumentation(lines)
    clean = strip_for_structure(lines)
    fstart, fend = find_function(lines, clean)

    # The two top-level `switch (op)` statements inside gen_x87.
    tops = []
    depth = 0
    for i in range(fstart, fend + 1):
        m = SWITCH_RE.match(clean[i])
        if m and m.group(1).strip() == 'op':
            tops.append(i)
        depth += clean[i].count('{') - clean[i].count('}')
    if len(tops) != 2:
        raise SystemExit('gen_x87: expected exactly two `switch (op)` '
                         'statements (memory path and register path), found '
                         '%d -- the model does not fit this source'
                         % len(tops))

    # QEMU's own naming of the arithmetic families, read once: the
    # `fxxx` leaves resolve through it and nothing else in the file does.
    arith = arith_dispatch_maps(lines, clean)
    leaves = []          # (mem, op, rm_or_None, why, line, word, wsrc)
    residue = []
    for which, open_idx in enumerate(tops):
        mem = (which == 0)
        expr, groups, close_idx = scan_switch(lines, clean, open_idx, fend)
        for g in groups:
            if g['has_default'] and not g['labels']:
                if not is_illegal_only(lines, clean, g['body']):
                    residue.append((g['start'] + 1,
                                    'top-level default is not illegal_op'))
                continue
            if g['has_default']:
                residue.append((g['start'] + 1,
                                'top-level default shares a group with a '
                                'case label'))
                continue
            ops = expand_labels(lines, g['labels'])
            if ops is None:
                residue.append((g['start'] + 1,
                                'a label this model cannot expand'))
                continue
            if is_illegal_only(lines, clean, g['body']):
                continue
            why = comment_of(lines, g['start'])
            gline = g['start'] + 1
            rmsw = inner_rm_switch(lines, clean, g['body'])
            if rmsw is None:
                for o, ow in ops:
                    word, wsrc, bad = leaf_word(lines, clean, o,
                                                ow or why, g['body'], arith)
                    if bad:
                        residue.append((gline, bad))
                    leaves.append((mem, o, None, ow or why, gline,
                                   word, wsrc))
                continue
            if len(ops) != 1:
                residue.append((g['start'] + 1,
                                'a `switch (rm)` group covers %d op values; '
                                'the model keys rm per op' % len(ops)))
                continue
            op0, op0w = ops[0]
            _, rgroups, _ = scan_switch(lines, clean, rmsw, g['body'][1])
            taken = set()
            defgroup = None
            for rg in rgroups:
                rms = expand_labels(lines, rg['labels'])
                if rms is None:
                    residue.append((rg['start'] + 1,
                                    'an rm label this model cannot expand'))
                    continue
                if rg['has_default']:
                    defgroup = (rg, rms)
                    taken.update(r for r, _ in rms)
                    continue
                taken.update(r for r, _ in rms)
                if is_illegal_only(lines, clean, rg['body']):
                    continue
                rwhy = comment_of(lines, rg['start'])
                for r, rw in rms:
                    # The WORD may only come from the rm level.  A group
                    # comment (`grp d9/5`, `df/4`) names the DISPATCH the
                    # leaves hang off, not any of them, and reading it
                    # would give seven leaves one word that is not an
                    # instruction at all.
                    w = rw or rwhy
                    word, wsrc, bad = leaf_word(lines, clean, op0, w,
                                                rg['body'], arith)
                    w = w or op0w or why
                    if bad:
                        residue.append((rg['start'] + 1, bad))
                    leaves.append((mem, op0, r, w, rg['start'] + 1,
                                   word, wsrc))
            if defgroup is not None:
                rg, rms = defgroup
                if is_illegal_only(lines, clean, rg['body']):
                    continue
                rwhy = comment_of(lines, rg['start'])
                named = dict(rms)
                for r in range(8):
                    if r in taken and r not in named:
                        continue
                    w = named.get(r) or rwhy
                    word, wsrc, bad = leaf_word(lines, clean, op0, w,
                                                rg['body'], arith)
                    w = w or op0w or why
                    if bad:
                        residue.append((rg['start'] + 1, bad))
                    leaves.append((mem, op0, r, w, rg['start'] + 1,
                                   word, wsrc))
    return lines, leaves, residue


def expand_labels(lines, labels):
    """[(value, QEMU's own word for it)] over a group's case labels.

       ONE WORD PER LINE, and positionally where the line covers several
       values.  `case 0x18 ... 0x1b: /* fildl, fisttpl, fistl, fistpl */`
       is four values and a comment naming four instructions in order,
       which is QEMU writing one word per value; a comment whose comma
       count does not match the label's span is prose about the family
       (`fxxx st, sti`) and stands for all of them.
    """
    out = []
    for lab, li in labels:
        vals = label_values(lab)
        if vals is None:
            return None
        parts = [w.strip() for w in comment_of(lines, li).split(',')]
        parts = [w for w in parts if w]
        if len(parts) == len(vals) and len(vals) > 1:
            out.extend(zip(vals, parts))
        else:
            whole = comment_of(lines, li)
            out.extend((v, whole) for v in vals)
    return out


# A family word: QEMU writes the operation as a run of `x` because the
# switch it is on does not distinguish them -- `fxxxs`, `fixxxl`,
# `fxxxp sti, st`, `fcmovxx`.  The word is a placeholder and may not be
# classified as one.
PLACEHOLDER_RE = re.compile(r'xx+')

# The operand-form suffixes QEMU appends to an x87 helper's name.  They
# say where the operands come from, not what the operation is:
# `fadd_ST0_FT0` and `fadd_STN_ST0` are one operation written twice.
HELPER_FORMS = ('ST0', 'FT0', 'STN')

HELPER_CALL_RE = re.compile(r'\bgen_helper_([A-Za-z0-9_]+)\s*\(')
ARITH_CALL_RE = re.compile(r'\bgen_helper_(fp_arith_[A-Za-z0-9_]+)\s*\(')
IF_OP_RE = re.compile(
    r'^if\s*\(\s*op\s*(>=|<=|==|!=|>|<)\s*(0x[0-9a-fA-F]+|\d+)\s*\)\s*\{$')
ELSE_RE = re.compile(r'^\}\s*else\s*\{$')


def helper_stem(name):
    """An x87 helper's name with its operand-form suffix peeled."""
    parts = name.split('_')
    while len(parts) > 1 and parts[-1] in HELPER_FORMS:
        parts.pop()
    return '_'.join(parts)


def op_reachable(clean, span, op):
    """The lines of a leaf body this OP value actually reaches.

       gen_x87 folds three architectural forms into one group and splits
       them again with `if (op >= 0x20)`, so which helper a leaf emits is
       a function of its own op.  The guard is read rather than guessed:
       only `if (op <rel> <constant>)` is understood, every other brace is
       carried through unchanged, and a body whose guards this cannot read
       simply yields all its lines -- which the caller then refuses if it
       leaves the operation ambiguous.
    """
    frames = []          # [open_depth, active, is_op_if, parent_active, cond]
    depth = 0
    out = []
    for i in range(span[0], span[1] + 1):
        st = clean[i].strip()
        if (ELSE_RE.match(st) and frames
                and frames[-1][0] == depth - 1 and frames[-1][2]):
            f = frames[-1]
            f[4] = not f[4]
            f[1] = f[3] and f[4]
            continue
        active = all(f[1] for f in frames)
        m = IF_OP_RE.match(st)
        if m:
            k = int(m.group(2), 0)
            rel = m.group(1)
            cond = {'>=': op >= k, '<=': op <= k, '==': op == k,
                    '!=': op != k, '>': op > k, '<': op < k}[rel]
            frames.append([depth, active and cond, True, active, cond])
            depth += 1
            continue
        if active:
            out.append(clean[i])
        nd = depth + st.count('{') - st.count('}')
        if nd > depth:
            for _ in range(nd - depth):
                frames.append([depth, active, False, active, True])
        elif nd < depth:
            while frames and frames[-1][0] >= nd:
                frames.pop()
        depth = nd
    return out


def arith_dispatch_maps(lines, clean):
    """QEMU's own naming of the x87 arithmetic ops, per dispatch function.

       `gen_helper_fp_arith_ST0_FT0(op & 7)` and its STN_ST0 twin are
       where the `fxxx` families resolve: each is a switch over the same
       three bits naming one helper per value, in QEMU's source, and that
       naming is the statement the family leaves are short of.
    """
    out = {}
    for i, l in enumerate(lines):
        if not l.startswith('static void gen_helper_fp_arith_'):
            continue
        fname = l[len('static void gen_helper_'):].split('(')[0]
        depth = 0
        seen = False
        table = {}
        cur = []
        for j in range(i, len(lines)):
            c = clean[j]
            labs = line_labels(c)
            if labs is not None and depth == 2:
                cur = [int(v, 0) for v in labs if v and CONST_RE.match(v)]
            else:
                m = HELPER_CALL_RE.search(c)
                if m and cur:
                    for v in cur:
                        table[v] = helper_stem(m.group(1))
                    cur = []
            depth += c.count('{') - c.count('}')
            if c.count('{'):
                seen = True
            if seen and depth == 0:
                break
        out[fname] = table
    return out


def leaf_word(lines, clean, op, why, body, arith):
    """QEMU's own word for one dispatch leaf, and where it came from.

       Three sources, and nothing else is offered:

         label    the comment on the leaf's own `case` line.
         arith    where that word carries an `x` placeholder, the operation
                  the `gen_helper_fp_arith_*` dispatch the leaf reaches
                  names for `op & 7` -- QEMU resolving its own family.
                  A placeholder whose leaf reaches no such dispatch is a
                  family the switch does not split at all (`fcmovxx` is
                  one operation under sixteen conditions), and the
                  placeholder is dropped rather than resolved.
         helper   where the leaf has no comment, the operation helper its
                  body emits, form suffix peeled.  QEMU names the
                  operation last and stages its operands before it.

       Returns (word, source, refusal) -- refusal non-empty means the leaf
       states nothing, which the caller turns into a build error.
    """
    first = why.split(',')[0].strip().split()
    word = first[0].lower() if first else ''
    if word and not PLACEHOLDER_RE.search(word):
        return word, 'label', ''
    body_lines = op_reachable(clean, body, op)
    if word:
        names = set()
        for c in body_lines:
            for m in ARITH_CALL_RE.finditer(c):
                names.add(m.group(1))
        if len(names) > 1:
            return '', 'arith', (
                'leaf op=0x%02x reaches %d fp_arith dispatches (%s); the '
                'family word %r cannot be resolved'
                % (op, len(names), ', '.join(sorted(names)), word))
        if names:
            fname = names.pop()
            table = arith.get(fname)
            if table is None:
                return '', 'arith', (
                    'leaf op=0x%02x calls gen_helper_%s, which this model '
                    'did not parse' % (op, fname))
            stem = table.get(op & 7)
            if stem is None:
                return '', 'arith', (
                    'gen_helper_%s names no operation for op & 7 = %d'
                    % (fname, op & 7))
            return stem, 'arith', ''
        stripped = PLACEHOLDER_RE.sub('', word)
        if not stripped:
            return '', 'arith', (
                'leaf op=0x%02x has the family word %r and reaches no '
                'fp_arith dispatch' % (op, word))
        return stripped, 'family', ''
    stems = [helper_stem(m.group(1))
             for c in body_lines for m in HELPER_CALL_RE.finditer(c)]
    if not stems:
        return '', 'helper', (
            'leaf op=0x%02x carries no comment and emits no helper -- '
            'nothing in the source names it' % op)
    return stems[-1], 'helper', ''


def comment_of(lines, idx):
    """The trailing /* ... */ on a case-label line -- QEMU's own word for
       the leaf.  Used only in the generated file's comments; the identity
       is the bits."""
    m = re.search(r'/\*\s*(.*?)\s*\*/', lines[idx])
    return m.group(1) if m else ''


def bits_of(mem, op, rm):
    """The 16 fixed bits of (opcode byte << 8) | modrm this leaf matches."""
    b = 0xD8 | ((op >> 3) & 7)
    out = format(b, '08b')
    out += '..' if mem else '11'
    out += format(op & 7, '03b')
    out += '...' if rm is None else format(rm, '03b')
    assert len(out) == 16
    return out


def mask_value(bits):
    m = v = 0
    for ch in bits:
        m <<= 1
        v <<= 1
        if ch == '.':
            continue
        m |= 1
        v |= int(ch)
    return m, v


def strip_instrumentation(lines):
    out = []
    removed = 0
    for l in lines:
        if l.lstrip().startswith(MARK) or l.endswith(FT_TAG):
            removed += 1
            continue
        out.append(l)
    return out, removed


def read_escape_bytes(path_inc):
    """The escape opcodes whose table row routes to gen_x87.

       Read rather than assumed: if a row moved, a hard-coded 0xD8..0xDF
       would keep emitting leaves for an opcode that no longer reaches this
       decoder."""
    got = []
    with open(path_inc) as f:
        for line in f:
            m = ESCAPE_RE.match(line)
            if m:
                got.append(int(m.group(1), 16))
    return sorted(set(got))


def read_slot_universe(path_inc):
    """Every __LINE__ slot decode-new.c.inc can hand out.

       A qualified id is an FNV hash in the same uint32_t space, so it must
       be proven not to collide with one."""
    with open(path_inc) as f:
        return set(range(1, len(f.read().splitlines()) + 2))


def build(path_c, path_dec, path_inc, report):
    lines, leaves, residue = model(path_c)
    if residue:
        for (ln, why) in residue:
            print('ERROR: %s:%d not modelled -- %s'
                  % (os.path.basename(path_c), ln, why), file=sys.stderr)
        return 1
    if not leaves:
        print('ERROR: gen_x87 produced no leaves -- an empty model would '
              'read as "the escape space has no internal dispatch"',
              file=sys.stderr)
        return 1

    escapes = read_escape_bytes(path_dec)
    if escapes != list(range(0xD8, 0xE0)):
        print('ERROR: the decode table routes %s to gen_x87, not 0xD8..0xDF'
              % ', '.join('0x%02x' % b for b in escapes), file=sys.stderr)
        return 1

    # Order: mod == 11 rows first, memory rows after.  See the header.
    reg = [l for l in leaves if not l[0]]
    memo = [l for l in leaves if l[0]]
    ordered = (sorted(reg, key=lambda l: (l[1], -1 if l[2] is None else l[2]))
               + sorted(memo, key=lambda l: l[1]))

    rows = []
    byname = {}
    for (mem, op, rm, why, gline, word, wsrc) in ordered:
        bits = bits_of(mem, op, rm)
        name = 'decode-new/x87@' + bits
        if name in byname:
            print('ERROR: two leaves produce the identity %s' % name,
                  file=sys.stderr)
            return 1
        byname[name] = True
        rows.append((name, fnv1a32(name), bits, mem, op, rm, why, gline,
                     word, wsrc))

    byhash = {}
    for row in rows:
        name, h = row[0], row[1]
        if h in byhash:
            print('ERROR: decode identity hash collision between %s and %s'
                  % (byhash[h], name), file=sys.stderr)
            return 1
        byhash[h] = name
    slots = read_slot_universe(path_dec)
    clash = [(r[0], r[1]) for r in rows if r[1] in slots]
    if clash:
        for (n, h) in clash:
            print('ERROR: %s hashes to 0x%08x, which is also a '
                  'decode-new.c.inc __LINE__ slot' % (n, h), file=sys.stderr)
        return 1

    # EXHAUSTIVE CHECK.  Every encoding of the escape space, resolved by
    # the ordered mask/value chain the generated selector will run, must
    # equal the leaf the parsed dispatch model says it reaches.  This is
    # what makes the memory rows' `..` mod field honest rather than a
    # claim: the ordering is measured over all 2048, not asserted.
    want = {}
    for (mem, op, rm, _, _, _, _) in leaves:
        b = 0xD8 | ((op >> 3) & 7)
        for modrm in range(256):
            m_mod = (modrm >> 6) & 3
            if mem and m_mod == 3:
                continue
            if (not mem) and m_mod != 3:
                continue
            if ((modrm >> 3) & 7) != (op & 7):
                continue
            if rm is not None and (modrm & 7) != rm:
                continue
            key = (b, modrm)
            if key in want:
                print('ERROR: encoding %02x %02x reaches two leaves'
                      % key, file=sys.stderr)
                return 1
            want[key] = bits_of(mem, op, rm)
    regchain = [(mask_value(r[2]), r[2]) for r in rows if not r[3]]
    memchain = [(mask_value(r[2]), r[2]) for r in rows if r[3]]
    checked = 0
    for b in range(0xD8, 0xE0):
        for modrm in range(256):
            insn = (b << 8) | modrm
            got = None
            chain = regchain if ((modrm >> 6) & 3) == 3 else memchain
            for ((m, v), bits) in chain:
                if (insn & m) == v:
                    got = bits
                    break
            exp = want.get((b, modrm))
            if got != exp:
                print('ERROR: encoding %02x %02x -- chain says %s, dispatch '
                      'model says %s' % (b, modrm, got, exp), file=sys.stderr)
                return 1
            checked += 1

    with open(path_inc, 'w') as f:
        f.write(
            '/*\n'
            ' * %s -- do not edit.\n'
            ' *\n'
            " * QEMU's own identity for each leaf of gen_x87's INTERNAL\n"
            ' * dispatch.  The i386 decode table gives the whole escape\n'
            ' * space 0xD8..0xDF eight rows, one per opcode byte, and\n'
            ' * gen_x87 then switches on the modrm byte; without these rows\n'
            ' * eight identities answer for every x87 instruction there is,\n'
            ' * and the one that names an operation names it for all the\n'
            ' * others too.\n'
            ' *\n'
            ' * The name is `decode-new/x87@<bits>`: the 16 fixed bits of\n'
            ' * (opcode byte << 8) | modrm that select this leaf, MSB first,\n'
            " * '.' for a bit the dispatch does not read.  The id is FNV-1a\n"
            ' * 32 of that name, the derivation scripts/decodetree.py uses,\n'
            ' * so every identity in this tree is made the same way.\n'
            ' *\n'
            ' * THE PROVENANCE LINE CARRIES QEMU\'S OWN WORD for the\n'
            ' * leaf, because the leaf has no other name: every one of\n'
            ' * these rules is spelled `x87` in the decode table, and the\n'
            ' * `case` line inside gen_x87 is where the instruction is\n'
            ' * named.  `word=<w>(<where>)`, and <where> is one of three:\n'
            ' *   label   the comment on the leaf\'s OWN case line, read\n'
            ' *           positionally where one line covers several\n'
            ' *           values and names one instruction per value.\n'
            ' *   arith   where that comment carries an `x` placeholder,\n'
            ' *           the operation gen_helper_fp_arith_ST0_FT0 or\n'
            ' *           _STN_ST0 names for this leaf\'s `op & 7` -- QEMU\n'
            ' *           resolving its own family, with the `if (op >=\n'
            ' *           0x20)` guard read rather than guessed.\n'
            ' *   helper  where the leaf has no comment at all, the\n'
            ' *           operation helper its body emits, operand-form\n'
            ' *           suffix peeled: gen_helper_fldz_ST0 is `fldz`.\n'
            ' * A leaf that reaches none of the three is REFUSED, so the\n'
            ' * word is present on every row or the generator does not\n'
            ' * write the file.\n'
            ' *\n'
            " * THE ROWS ARE ORDERED and the don't-care bits read under that\n"
            ' * order, exactly as decodetree\'s @-suffixed pattern names do.\n'
            ' * A memory-operand leaf is reached for mod = 00, 01 and 10 and\n'
            ' * not for 11, which no single mask states; the register leaves\n'
            ' * carry `11` in the mod field and are consulted on their\n'
            ' * own arm of the selector -- the same `if (mod != 3)` split\n'
            " * gen_x87 makes -- so a memory leaf's `..` means the\n"
            ' * encodings that arm never sees.  The generator checks\n'
            ' * that resolution over ALL %d encodings of the escape\n'
            ' * space against the dispatch it parsed out of gen_x87, so\n'
            ' * the split is measured rather than asserted.\n'
            ' *\n'
            ' * THE ESCAPE ROWS THEMSELVES DO NOT MOVE.  decode-new.c.inc is\n'
            ' * untouched and an encoding matching no leaf -- one gen_x87\n'
            ' * sends to illegal_op -- publishes nothing and keeps the escape\n'
            ' * row\'s own id and name, bit for bit.\n'
            ' */\n\n' % (GEN_BY, checked))
        f.write('static const struct {\n'
                '    uint32_t id;\n'
                '    const char *name;\n'
                '} x87_ident_tab[] = {\n')
        f.write('    { 0, NULL },\n')
        base = os.path.basename(path_c)
        for (name, h, bits, mem, op, rm, why, gline, word, wsrc) in rows:
            # Two comment lines, the second in the shape the
            # MIPS table uses, because a 51-character identity
            # plus a trailing provenance comment does not fit
            # 80 columns and the consumer reads the lifted form.
            #
            # The WORD rides on the provenance line, because it is
            # the half of the provenance a consumer needs and a
            # word left in prose is a word nothing reads.
            f.write('    /* %-3s op=0x%02x %-6s %s */\n'
                    % ('mem' if mem else 'reg', op,
                       'rm=%d' % rm if rm is not None else '',
                       why))
            f.write('    /* %s:%d word=%s(%s) */\n'
                    % (base, gline, word, wsrc))
            f.write('    { 0x%08xu, "%s" },\n' % (h, name))
        f.write('};\n\n')
        f.write('/*\n'
                ' * The leaf an encoding reaches, or 0 for one gen_x87\n'
                ' * refuses.  Ordered; see the header.\n'
                ' */\n')
        f.write('static inline uint16_t x87_ident_of(int b, int modrm)\n'
                '{\n'
                '    uint32_t insn = ((uint32_t)(b & 0xff) << 8) '
                '| (uint32_t)(modrm & 0xff);\n\n'
                '    if (((modrm >> 6) & 3) == 3) {\n')
        for idx, r in enumerate(rows, 1):
            if r[3]:
                continue
            m, v = mask_value(r[2])
            f.write('        if ((insn & 0x%04xu) == 0x%04xu) {\n'
                    '            return %d;\n'
                    '        }\n' % (m, v, idx))
        f.write('        return 0;\n'
                '    }\n\n')
        for idx, r in enumerate(rows, 1):
            if not r[3]:
                continue
            m, v = mask_value(r[2])
            f.write('    if ((insn & 0x%04xu) == 0x%04xu) {\n'
                    '        return %d;\n'
                    '    }\n' % (m, v, idx))
        f.write('    return 0;\n}\n\n')
        f.write('static inline void x87_ident_publish(int b, int modrm)\n'
                '{\n'
                '    uint16_t idx = x87_ident_of(b, modrm);\n\n'
                '    if (idx) {\n'
                '        plugin_gen_record_insn_identity('
                'x87_ident_tab[idx].id,\n'
                '                                       '
                ' x87_ident_tab[idx].name);\n'
                '    }\n'
                '}\n')

    # Insert the publish, on the path that RETURNS.  gen_x87 reaches its
    # trailing `return;` only when a leaf generated code: the CR0.EM/TS
    # arm returns before any decode and every refusal jumps to illegal_op
    # past this point, so publishing here publishes a decision QEMU took.
    with open(path_c) as f:
        src = f.read().split('\n')
    src, removed = strip_instrumentation(src)
    clean = strip_for_structure(src)
    fstart, fend = find_function(src, clean)
    ret = None
    for i in range(fend, fstart, -1):
        if clean[i].strip() == 'return;':
            ret = i
            break
    if ret is None:
        print('ERROR: gen_x87 has no trailing `return;` to publish before',
              file=sys.stderr)
        return 1
    indent = re.match(r'^(\s*)', src[ret]).group(1)
    # Exactly one inserted line, and strip_instrumentation() removes
    # exactly that line: re-running the generator on an already
    # instrumented tree must reproduce it byte for byte, and a blank
    # line inserted beside it would accumulate one per run.
    out = src[:ret] + ['%s%s%s' % (indent, MARK, FT_TAG)] + src[ret:]
    with open(path_c, 'w') as f:
        f.write('\n'.join(out))

    with open(report, 'w') as f:
        f.write('x86_x87_ident_instrument residue report\n')
        f.write('=======================================\n\n')
        f.write('source            : %s\n' % path_c)
        f.write('decode table      : %s\n' % path_dec)
        f.write('previous inserts stripped: %d\n' % removed)
        f.write('escape opcodes    : %s\n'
                % ', '.join('0x%02x' % b for b in escapes))
        f.write('dispatch leaves   : %d  (register %d, memory %d)\n'
                % (len(rows), len(reg), len(memo)))
        f.write('encodings checked : %d\n' % checked)
        f.write('unmodelled labels : %d\n\n' % len(residue))
        f.write('every leaf, in the order the selector matches them\n')
        f.write('-------------------------------------------------\n')
        for (name, h, bits, mem, op, rm, why, gline, word, wsrc) in rows:
            f.write('0x%08x  %s  %s op=0x%02x%s  %s:%d  word=%s(%s)  %s\n'
                    % (h, name, 'mem' if mem else 'reg', op,
                       ' rm=%d' % rm if rm is not None else '',
                       os.path.basename(path_c), gline, word, wsrc, why))
    print('x87: %d dispatch leaves, %d encodings checked, %d unmodelled'
          % (len(rows), checked, len(residue)))
    return 0


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument('--source',
                    default=os.path.join(here, 'target/i386/tcg/translate.c'))
    ap.add_argument('--decode-table',
                    default=os.path.join(here,
                                         'target/i386/tcg/decode-new.c.inc'))
    ap.add_argument('--table',
                    default=os.path.join(here,
                                         'target/i386/tcg/x87_ident.c.inc'))
    ap.add_argument('--report',
                    default=os.path.join(
                        here,
                        'contrib/plugins/champsim_tracer/tools/arc3_qemuid/'
                        'X87_IDENT_RESIDUE.txt'))
    args = ap.parse_args()
    return build(args.source, args.decode_table, args.table, args.report)


if __name__ == '__main__':
    sys.exit(main())
