#!/usr/bin/env python3
#
# Qualify the i386 `multi0F` rows -- five decode-table sites that answer
# for forty-one different instructions through forty-two arms.
#
# THE PROBLEM.  QEMU's new i386 decoder has not converted the 0F 00,
# 0F 01, 0F 1A, 0F 1B and 0F C7-group spaces, so each is one X86_OP_*
# site dispatching to one C function, gen_multi0F(), which then switches
# on the opcode and the modrm byte itself:
#
#     decode-new.c.inc  [0x00] = X86_OP_ENTRY1(multi0F, nop,v, nolea)
#     decode-new.c.inc  [0x01] = X86_OP_ENTRY1(multi0F, nop,v, nolea)
#     ...
#     translate.c       gen_multi0F()  switch (b) { ... switch (modrm) { ...
#
# One __LINE__ slot, one identity, for `sgdt`, `monitor`, `xgetbv`,
# `swapgs`, `rdtscp`, `invlpg` and the rest of the forty-one.  A consumer keyed on
# that identity cannot tell any of them apart, and the class the shared
# row states is the class of NONE of them: exec96 measured `xgetbv`
# published as GEN_OP_FENCE on its live encoding, because the word the
# generator has to work with is the placeholder name `multi0F`.
#
# THE DISCRIMINATOR IS NOT MISSING.  gen_multi0F() reads `b`, `s->modrm`
# and `s->prefix` and dispatches on exactly those; every arm below is one
# of ITS OWN case labels, and the word is the one QEMU wrote in the
# comment beside it.  This script carries those three facts into the
# identity, in the shape scripts/x86_x87_ident_instrument.py,
# scripts/x86_vex_ident_instrument.py and scripts/x86_cet_ident_instrument.py
# established:
#
#   * every arm's ANCHOR -- the QEMU source text that names it -- is
#     located in gen_multi0F()'s own body, and the script REFUSES if an
#     anchor is missing or matches twice.  The line it is found at is the
#     row's provenance, so a row can never outlive the arm it describes;
#
#   * the name is `translate.c/multi0F@b=<hex>,modrm=<bits>[,pfx=<name>]`
#     and the id is FNV-1a-32 of the NAME ALONE -- the derivation
#     scripts/x86_x87_ident_instrument.py and scripts/mips_ident_instrument.py
#     use, and for their reason: these arms share one X86_OP_ENTRY slot, so
#     there is no runtime __LINE__ to append, and appending the ANCHOR line
#     instead made every id a function of where translate.c happens to hold
#     the case label.  The anchor is still located, still refused when it is
#     missing or doubled, and still printed as the row's provenance;
#
#   * the selector is checked EXHAUSTIVELY over the whole (b, prefix,
#     modrm) space this function can be entered with -- not sampled -- and
#     the residual is reported beside the hits, because a selector that
#     answered for everything would pass a hits-only check;
#
#   * THE BASE ROWS DO NOT MOVE.  decode-new.c.inc is not touched at all.
#     translate.c gains an include and one call, both placed BELOW every
#     x87 leaf anchor and ABOVE gen_multi0F, and the script refuses if
#     that placement would renumber an x87 row.
#
# MACHINE STATE IS NOT A DISCRIMINATOR AND IS NOT USED AS ONE (R16).  The
# MPX arms are gated at run time on HF_MPX_EN_MASK, and a machine with
# MPX off executes `bndcl` as a no-op; the ENCODING still names `bndcl`,
# so the arms are keyed on prefix and mod alone and a disabled machine
# publishes the same identity as an enabled one.
#
# Author: Maccoy Merrell.
import argparse
import re
import sys

FUNC_RE = re.compile(r'^static void gen_multi0F\(')
INCLUDE_TAG = '/* multi0f_ident */'
# The FIRST line of the inserted block carries a marker of its own, so
# strip_instrumentation() can find the block's start as well as its end.
# A stripper that can only see the end leaves the prose behind and the
# next run inserts a second copy -- measured, not imagined.
INCLUDE_MARK = 'multi0f_ident: ENCODING-QUALIFIED IDENTITY'
INCLUDE_BLOCK = (
    '/*\n'
    ' * ' + INCLUDE_MARK + ' for the unconverted 0F spaces.\n'
    ' *\n'
    ' * gen_multi0F() is reached from five decode-table rows and\n'
    ' * dispatches on `b`, `s->modrm` and `s->prefix` to forty-one\n'
    ' * different instructions.  The table below states each arm as its\n'
    ' * own identity, so a consumer can tell `xgetbv` from `swapgs`.\n'
    ' * Generated by scripts/x86_multi0f_ident_instrument.py.\n'
    ' */\n'
    '#include "multi0f_ident.c.inc"  ' + INCLUDE_TAG)
CALL_TAG = '/* multi0f_ident */'
CALL = '    multi0f_ident_publish(b, modrm, prefixes);  ' + CALL_TAG

# Prefix classes, as gen_multi0F itself tests them.
PFX_ANY = 'any'      # the arm does not look at a prefix
PFX_NONE = 'none'    # none of REPZ / REPNZ / DATA
PFX_REPZ = 'repz'
PFX_REPNZ = 'repnz'
PFX_DATA = 'data'

# (b, pfx, modrm_mask, modrm_value, mem_only, word, anchor)
#
# `mem_only` is QEMU's CASE_MODRM_MEM_OP: the arm is reached for mod 0, 1
# and 2 and not for mod 3.  A mask of 0x38 is CASE_MODRM_OP / a reg-field
# switch; 0xff is an exact modrm case label.
#
# The ANCHOR is the source text of the case label or, where the arm has no
# label of its own, of the comment QEMU names it with.  It is what makes
# this table a reading of gen_multi0F rather than a copy of it.
ARMS = (
    # 0F 00 -- switch on (modrm >> 3) & 7
    (0x100, PFX_ANY, 0x38, 0 << 3, False, 'sldt',  'case 0: /* sldt */'),
    (0x100, PFX_ANY, 0x38, 1 << 3, False, 'str',   'case 1: /* str */'),
    (0x100, PFX_ANY, 0x38, 2 << 3, False, 'lldt',  'case 2: /* lldt */'),
    (0x100, PFX_ANY, 0x38, 3 << 3, False, 'ltr',   'case 3: /* ltr */'),
    (0x100, PFX_ANY, 0x38, 4 << 3, False, 'verr',  'case 4: /* verr */'),
    (0x100, PFX_ANY, 0x38, 5 << 3, False, 'verw',  'case 5: /* verw */'),
    # 0F 01 -- switch on the whole modrm byte
    (0x101, PFX_ANY, 0x38, 0 << 3, True,  'sgdt',
     'CASE_MODRM_MEM_OP(0): /* sgdt */'),
    (0x101, PFX_ANY, 0x38, 1 << 3, True,  'sidt',
     'CASE_MODRM_MEM_OP(1): /* sidt */'),
    (0x101, PFX_ANY, 0x38, 2 << 3, True,  'lgdt',
     'CASE_MODRM_MEM_OP(2): /* lgdt */'),
    (0x101, PFX_ANY, 0x38, 3 << 3, True,  'lidt',
     'CASE_MODRM_MEM_OP(3): /* lidt */'),
    (0x101, PFX_ANY, 0x38, 7 << 3, True,  'invlpg',
     'CASE_MODRM_MEM_OP(7): /* invlpg */'),
    (0x101, PFX_ANY, 0xff, 0xc8, False, 'monitor', 'case 0xc8: /* monitor */'),
    (0x101, PFX_ANY, 0xff, 0xc9, False, 'mwait',   'case 0xc9: /* mwait */'),
    (0x101, PFX_ANY, 0xff, 0xca, False, 'clac',    'case 0xca: /* clac */'),
    (0x101, PFX_ANY, 0xff, 0xcb, False, 'stac',    'case 0xcb: /* stac */'),
    (0x101, PFX_ANY, 0xff, 0xd0, False, 'xgetbv',  'case 0xd0: /* xgetbv */'),
    (0x101, PFX_ANY, 0xff, 0xd1, False, 'xsetbv',  'case 0xd1: /* xsetbv */'),
    (0x101, PFX_ANY, 0xff, 0xd8, False, 'vmrun',   'case 0xd8: /* VMRUN */'),
    (0x101, PFX_ANY, 0xff, 0xd9, False, 'vmmcall', 'case 0xd9: /* VMMCALL */'),
    (0x101, PFX_ANY, 0xff, 0xda, False, 'vmload',  'case 0xda: /* VMLOAD */'),
    (0x101, PFX_ANY, 0xff, 0xdb, False, 'vmsave',  'case 0xdb: /* VMSAVE */'),
    (0x101, PFX_ANY, 0xff, 0xdc, False, 'stgi',    'case 0xdc: /* STGI */'),
    (0x101, PFX_ANY, 0xff, 0xdd, False, 'clgi',    'case 0xdd: /* CLGI */'),
    (0x101, PFX_ANY, 0xff, 0xde, False, 'skinit',  'case 0xde: /* SKINIT */'),
    (0x101, PFX_ANY, 0xff, 0xdf, False, 'invlpga', 'case 0xdf: /* INVLPGA */'),
    (0x101, PFX_ANY, 0xff, 0xee, False, 'rdpkru',  'case 0xee: /* rdpkru */'),
    (0x101, PFX_ANY, 0xff, 0xef, False, 'wrpkru',  'case 0xef: /* wrpkru */'),
    (0x101, PFX_ANY, 0xff, 0xf8, False, 'swapgs',  'case 0xf8: /* swapgs */'),
    (0x101, PFX_ANY, 0xff, 0xf9, False, 'rdtscp',  'case 0xf9: /* rdtscp */'),
    (0x101, PFX_ANY, 0x38, 4 << 3, False, 'smsw',
     'CASE_MODRM_OP(4): /* smsw */'),
    (0x101, PFX_ANY, 0x38, 6 << 3, False, 'lmsw',
     'CASE_MODRM_OP(6): /* lmsw */'),
    # 0F C7 /6, /7 -- the group-9 register forms
    (0x1c7, PFX_ANY,  0x38, 6 << 3, False, 'rdrand', 'case 6: /* RDRAND */'),
    (0x1c7, PFX_REPZ, 0x38, 7 << 3, False, 'rdpid',
     'CPUID_7_0_ECX_RDPID'),
    (0x1c7, PFX_NONE, 0x38, 7 << 3, False, 'rdseed',
     'CPUID_7_0_EBX_RDSEED'),
    # 0F 1A / 0F 1B -- MPX, selected by prefix and by mod
    (0x11a, PFX_REPZ,  0x00, 0x00, False, 'bndcl',  '/* bndcl */'),
    (0x11a, PFX_REPNZ, 0x00, 0x00, False, 'bndcu',  '/* bndcu */'),
    (0x11a, PFX_DATA,  0x00, 0x00, False, 'bndmov',
     '/* bndmov -- from reg/mem */'),
    (0x11a, PFX_NONE,  0x00, 0x00, True,  'bndldx', '/* bndldx */'),
    (0x11b, PFX_REPZ,  0x00, 0x00, True,  'bndmk',  '/* bndmk */'),
    (0x11b, PFX_REPNZ, 0x00, 0x00, False, 'bndcn',  '/* bndcn */'),
    (0x11b, PFX_DATA,  0x00, 0x00, False, 'bndmov',
     '/* bndmov -- to reg/mem */'),
    (0x11b, PFX_NONE,  0x00, 0x00, True,  'bndstx', '/* bndstx */'),
)

# The `b` values gen_multi0F is entered with, i.e. the whole space the
# exhaustive check has to cover.  Read from the function's own outer
# switch rather than written down twice.
OUTER_RE = re.compile(r'^\s*case (0x1[0-9a-f]{2}):')


def fnv1a32(text):
    """FNV-1a 32 of TEXT, with 0 remapped to 1 -- the derivation
       scripts/decodetree.py's ident_hash() and the x87, VEX and CET legs
       all use, so every identity in this tree is made the same way."""
    h = 0x811c9dc5
    for byte in text.encode('utf-8'):
        h = ((h ^ byte) * 0x01000193) & 0xffffffff
    return h if h else 1


def bits_name(mask, value, mem_only):
    """The 8 modrm bits, MSB first, '.' where the arm does not look.

       mem_only is QEMU's CASE_MODRM_MEM_OP, which excludes mod 3 without
       pinning mod to any one value, so it cannot be spelled as a bit
       pattern and rides as its own suffix."""
    body = ''.join('.' if not (mask >> b) & 1 else str((value >> b) & 1)
                   for b in range(7, -1, -1))
    return body + (',mem' if mem_only else '')


def strip_instrumentation(lines):
    """Remove a previous run's insertions, WHOLE.

       Both insertions are removed by their own markers, and the include
       block by its FIRST line as well as its last -- a stripper that
       finds only the trailing `#include` leaves the prose above it in
       place and the next run appends a second copy."""
    out, removed, skip = [], 0, False
    for l in lines:
        if skip:
            if l.rstrip().endswith(INCLUDE_TAG):
                skip = False
                removed += 1
            continue
        if INCLUDE_MARK in l:
            # the block opened with a bare `/*` already appended
            while out and out[-1].strip() in ('/*', ''):
                out.pop()
            skip = True
            continue
        if l.rstrip().endswith(CALL_TAG):
            removed += 1
            continue
        out.append(l)
    if skip:
        raise SystemExit('the include block has no terminating #include -- '
                         'refusing to strip half of it')
    return out, removed


def func_span(lines):
    """(first, last) 1-based line numbers of gen_multi0F's body."""
    start = None
    for n, l in enumerate(lines, 1):
        if FUNC_RE.match(l):
            start = n
            break
    if start is None:
        return None, None
    for n in range(start, len(lines) + 1):
        if lines[n - 1] == '}':
            return start, n
    return start, None


def matches_arm(arm, b, pfx_bits, modrm):
    ab, apfx, amask, aval, amem, _, _ = arm
    if b != ab:
        return False
    repz, repnz, data = pfx_bits
    if apfx == PFX_REPZ and not repz:
        return False
    if apfx == PFX_REPNZ and not repnz:
        return False
    if apfx == PFX_DATA and not data:
        return False
    if apfx == PFX_NONE and (repz or repnz or data):
        return False
    if amem and (modrm >> 6) == 3:
        return False
    return (modrm & amask) == aval


def check_exhaustive(outer_bs):
    """Every (b, prefix, modrm) gen_multi0F can be entered with, against
       the emitted selector's own model.  Reports hits AND residual, and
       refuses on any encoding that reaches two arms."""
    hits = residual = 0
    reached = {}
    for b in outer_bs:
        for repz in (0, 1):
            for repnz in (0, 1):
                for data in (0, 1):
                    for modrm in range(256):
                        hit = [i for i, arm in enumerate(ARMS, 1)
                               if matches_arm(arm, b, (repz, repnz, data),
                                              modrm)]
                        # FIRST WINS, because gen_multi0F's own if-chain
                        # tests REPZ, then REPNZ, then DATA, then the
                        # unprefixed arm, and the emitted selector scans in
                        # the same order.  What may NOT happen is two arms
                        # of the SAME prefix class matching one encoding:
                        # there the order would be arbitrary and the
                        # identity would depend on table position.
                        for a in range(len(hit)):
                            for c in range(a + 1, len(hit)):
                                if ARMS[hit[a] - 1][1] == ARMS[hit[c] - 1][1]:
                                    return None, (
                                        'b=0x%x pfx=%d%d%d modrm=0x%02x '
                                        'reaches arms %d and %d, both prefix '
                                        'class %s' % (b, repz, repnz, data,
                                                      modrm, hit[a], hit[c],
                                                      ARMS[hit[a] - 1][1]))
                        idx = hit[0] if hit else 0
                        if idx:
                            hits += 1
                            reached[idx] = reached.get(idx, 0) + 1
                        else:
                            residual += 1
    missing = [ARMS[i - 1][5] for i in range(1, len(ARMS) + 1)
               if i not in reached]
    if missing:
        return None, 'unreachable arm(s): ' + ', '.join(missing)
    return (hits, residual, reached), None


def build(path_tr, path_out, path_x87, report):
    with open(path_tr) as f:
        src = f.read().split('\n')
    src, removed = strip_instrumentation(src)

    start, end = func_span(src)
    if start is None or end is None:
        print('ERROR: gen_multi0F() not found in %s' % path_tr, file=sys.stderr)
        return 1

    # The include goes directly above gen_multi0F, which is below every
    # x87 leaf anchor.  Refuse if that is not true: moving an x87 anchor
    # would renumber identities this script does not own.
    try:
        with open(path_x87) as f:
            x87 = f.read()
    except OSError:
        x87 = ''
    x87_lines = [int(m) for m in
                 re.findall(r'/\* translate\.c:(\d+) word=', x87)]
    if x87_lines and max(x87_lines) >= start:
        print('ERROR: an x87 anchor is at line %d, at or below the include '
              'insertion point %d -- inserting there would renumber it'
              % (max(x87_lines), start), file=sys.stderr)
        return 1

    # INSERT FIRST, THEN READ THE ANCHORS.  The rows' provenance is a line
    # number in the file as it will be built, so anchors must be located
    # in the final text, not in the text before the two insertions.
    src = src[:start - 1] + INCLUDE_BLOCK.split('\n') + [''] + src[start - 1:]
    start, end = func_span(src)
    ret = None
    for n in range(end, start, -1):
        if src[n - 1] == ' illegal_op:':
            for m in range(n - 1, start, -1):
                if src[m - 1].strip() == 'return;':
                    ret = m
                    break
            break
    if ret is None:
        print('ERROR: no trailing `return;` before gen_multi0F\'s illegal_op '
              'label -- the publish has no place that every legal arm '
              'reaches', file=sys.stderr)
        return 1
    src.insert(ret - 1, CALL)
    start, end = func_span(src)

    body = src[start - 1:end]
    rows = []
    for arm in ARMS:
        b, pfx, mask, value, mem, word, anchor = arm
        found = [i for i, l in enumerate(body, start) if anchor in l]
        if len(found) != 1:
            print('ERROR: anchor %r for %s matched %d line(s) in '
                  'gen_multi0F -- an arm this script cannot find in QEMU\'s '
                  'own source is one it may not state'
                  % (anchor, word, len(found)), file=sys.stderr)
            return 1
        name = 'translate.c/multi0F@b=%03x,modrm=%s' % (
            b, bits_name(mask, value, mem))
        if pfx != PFX_ANY:
            name += ',pfx=%s' % pfx
        # THE IDENTITY IS THE NAME ALONE, AND THE LINE IS PROVENANCE ONLY.
        #
        # It used to be fnv1a32('<name>#<anchor line>'), and that made every
        # one of these forty-two ids a function of where gen_multi0F()'s case
        # labels happen to sit in translate.c.  Adding lines ABOVE them --
        # which a QEMU-side dataflow declaration does routinely -- renumbered
        # all forty-two at once, so the shipped table stopped regenerating
        # from its own tree: verify48 measured 42 rows, names identical as a
        # set, and ZERO ids in common with a fresh emit, the anchors having
        # moved by a uniform +349.
        #
        # That is exactly the fragility scripts/decodetree.py:ident_hash()
        # gives as its reason for being a hash rather than a table ordinal --
        # "an ordinal renumbers whenever a pattern is added to or removed
        # from the .decode file, which would silently invalidate any table a
        # consumer had keyed on it".  A source line number IS an ordinal.
        #
        # THE OTHER LEGS ARE NOT WRONG AND ARE NOT CHANGED.  3DNow!, PREFETCH,
        # CET and VEX append decode-new.c.inc's own __LINE__, which is the
        # slot QEMU STAMPS at run time: their id SHOULD move when that moves,
        # because the thing they qualify moved.  gen_multi0F's arms have no
        # such slot -- all five X86_OP_ENTRY sites share one -- so the anchor
        # line was never the runtime identity here, only a citation.  The x87
        # and MIPS legs, whose arms are likewise located by anchor, already
        # key on the name alone; this joins them.
        #
        # Uniqueness is not weakened: the name carries b, the modrm bits and
        # the prefix, and the assertion below still refuses two arms that
        # share one.  The anchor is still LOCATED, still refused when missing
        # or doubled, and still printed beside each row -- so a row still
        # cannot outlive the arm it describes.
        rows.append((name, fnv1a32(name), found[0], arm))

    ids = [r[1] for r in rows]
    if len(set(ids)) != len(ids):
        print('ERROR: two arms hash to the same id', file=sys.stderr)
        return 1
    names = [r[0] for r in rows]
    if len(set(names)) != len(names):
        dup = sorted({n for n in names if names.count(n) > 1})
        print('ERROR: two arms share the name(s) %s -- an identity that does '
              'not separate them is not a qualification' % ', '.join(dup),
              file=sys.stderr)
        return 1

    outer_bs = sorted({int(m.group(1), 16) for l in body
                       for m in [OUTER_RE.match(l)] if m
                       and int(m.group(1), 16) >= 0x100})
    declared = sorted({a[0] for a in ARMS})
    if not set(declared) <= set(outer_bs):
        print('ERROR: arms declared for b values gen_multi0F does not switch '
              'on: %s' % sorted(set(declared) - set(outer_bs)),
              file=sys.stderr)
        return 1

    got, err = check_exhaustive(outer_bs)
    if err:
        print('ERROR: ' + err, file=sys.stderr)
        return 1
    hits, residual, reached = got

    out = []
    w = out.append
    w('/*')
    w(' * Auto-generated by scripts/x86_multi0f_ident_instrument.py'
      ' -- do not edit.')
    w(' *')
    w(' * %d DECODE-TABLE OPCODES, %d ARMS, %d INSTRUCTIONS.  QEMU has not'
      % (len(outer_bs), len(rows), len({a[5] for a in ARMS})))
    w(' * converted the 0F 00, 0F 01, 0F 1A, 0F 1B and 0F C7-group')
    w(' * spaces to the new decoder, so each is one X86_OP_* site -- one')
    w(' * __LINE__ slot, one identity -- dispatching to gen_multi0F(),')
    w(' * which switches on the opcode and the modrm byte itself.  A')
    w(' * consumer keyed on that identity cannot tell `xgetbv` from')
    w(' * `swapgs`, and the class the shared row states is the class of')
    w(' * none of them: the only word the row offers is the placeholder')
    w(' * name `multi0F`.')
    w(' *')
    w(' * The discriminator is not missing.  gen_multi0F() reads `b`,')
    w(' * `s->modrm` and `s->prefix` and dispatches on exactly those.')
    w(' * Every row below is one of ITS OWN case labels, located in its')
    w(' * body at generation time -- the line beside each row is where')
    w(' * QEMU names the arm -- and the word is the one QEMU wrote in')
    w(' * the comment there.')
    w(' *')
    w(' * MACHINE STATE IS NOT A DISCRIMINATOR (R16).  The MPX arms are')
    w(' * gated at run time on HF_MPX_EN_MASK and a machine with MPX off')
    w(' * executes `bndcl` as a no-op; the ENCODING still names `bndcl`,')
    w(' * so the arms are keyed on prefix and mod alone and a disabled')
    w(' * machine publishes the same identity as an enabled one.')
    w(' *')
    w(' * The id is FNV-1a-32 of the NAME ALONE.  These arms share one')
    w(' * X86_OP_ENTRY slot, so there is no runtime __LINE__ to append;')
    w(' * appending the anchor line instead made every id a function of')
    w(' * where translate.c holds the case label, and a declaration added')
    w(' * above them renumbered all forty-two at once.  The anchor is')
    w(' * still located and still printed beside each row, as the row\'s')
    w(' * provenance and not as part of its identity.')
    w(' *')
    w(' * THE BASE ROWS DO NOT MOVE.  decode-new.c.inc is not edited at')
    w(' * all; an encoding that reaches no arm publishes nothing here and')
    w(' * keeps its X86_OP_* row\'s own id and name bit for bit.')
    w(' *')
    w(' * EXHAUSTIVE, not sampled: %d (b, prefix, modrm) triples over the'
      % (hits + residual))
    w(' * %d opcodes this function is entered with, times all eight'
      % len(outer_bs))
    w(' * REPZ/REPNZ/DATA prefix states, times all 256 modrm bytes -- and')
    w(' * FIRST MATCH WINS, because gen_multi0F\'s own if-chain tests REPZ,')
    w(' * then REPNZ, then DATA, then the unprefixed arm, so an encoding')
    w(' * carrying two prefix bytes gets the arm QEMU generates for it.  %d'
      % hits)
    w(' * reach a qualified identity, %d do not, no triple reaches two,'
      % residual)
    w(' * and every arm is reachable.')
    w(' */')
    w('')
    w('static const struct {')
    w('    uint32_t id;')
    w('    const char *name;')
    w('} multi0f_ident_tab[] = {')
    w('    { 0, NULL },')
    for name, ident, line, arm in rows:
        b, pfx, mask, value, mem, word, anchor = arm
        # The anchor is QEMU's own source text and several arms are named
        # only by a comment, so it can carry a `/*` of its own; printing it
        # raw would open a comment inside a comment and fail the build.
        w('    /* %s: %s */'
          % (word, anchor.strip().replace('/*', '').replace('*/', '').strip()))
        w('    /* translate.c:%d word=%s(arm) */' % (line, word))
        w('    { 0x%08xu, "%s" },' % (ident, name))
    w('};')
    w('')
    w('/* Prefix requirement, as gen_multi0F itself tests it. */')
    w('#define M0F_PFX_ANY   0')
    w('#define M0F_PFX_NONE  1')
    w('#define M0F_PFX_REPZ  2')
    w('#define M0F_PFX_REPNZ 3')
    w('#define M0F_PFX_DATA  4')
    w('')
    w('static const struct {')
    w('    uint16_t b;')
    w('    uint8_t  pfx;')
    w('    uint8_t  mask;')
    w('    uint8_t  value;')
    w('    bool     mem_only;')
    w('    uint16_t idx;')
    w('} multi0f_ident_arms[] = {')
    pfxc = {PFX_ANY: 'M0F_PFX_ANY', PFX_NONE: 'M0F_PFX_NONE',
            PFX_REPZ: 'M0F_PFX_REPZ', PFX_REPNZ: 'M0F_PFX_REPNZ',
            PFX_DATA: 'M0F_PFX_DATA'}
    for i, (name, ident, line, arm) in enumerate(rows, 1):
        b, pfx, mask, value, mem, word, anchor = arm
        w('    { 0x%03x, %-13s 0x%02x, 0x%02x, %-5s %2d },   /* %s */'
          % (b, pfxc[pfx] + ',', mask, value,
             'true,' if mem else 'false,', i, word))
    w('};')
    w('')
    w('static inline uint16_t multi0f_ident_of(int b, int modrm,')
    w('                                        int prefixes)')
    w('{')
    w('    bool repz  = (prefixes & PREFIX_REPZ) != 0;')
    w('    bool repnz = (prefixes & PREFIX_REPNZ) != 0;')
    w('    bool data  = (prefixes & PREFIX_DATA) != 0;')
    w('')
    w('    for (size_t i = 0; i < ARRAY_SIZE(multi0f_ident_arms); i++) {')
    w('        if (multi0f_ident_arms[i].b != b) {')
    w('            continue;')
    w('        }')
    w('        switch (multi0f_ident_arms[i].pfx) {')
    w('        case M0F_PFX_NONE:')
    w('            if (repz || repnz || data) {')
    w('                continue;')
    w('            }')
    w('            break;')
    w('        case M0F_PFX_REPZ:')
    w('            if (!repz) {')
    w('                continue;')
    w('            }')
    w('            break;')
    w('        case M0F_PFX_REPNZ:')
    w('            if (!repnz) {')
    w('                continue;')
    w('            }')
    w('            break;')
    w('        case M0F_PFX_DATA:')
    w('            if (!data) {')
    w('                continue;')
    w('            }')
    w('            break;')
    w('        default:')
    w('            break;')
    w('        }')
    w('        if (multi0f_ident_arms[i].mem_only && ((modrm >> 6) & 3) == 3) {')
    w('            continue;')
    w('        }')
    w('        if ((modrm & multi0f_ident_arms[i].mask) ==')
    w('            multi0f_ident_arms[i].value) {')
    w('            return multi0f_ident_arms[i].idx;')
    w('        }')
    w('    }')
    w('    return 0;')
    w('}')
    w('')
    w('/*')
    w(' * Publish the encoding-qualified identity for an arm that has one.')
    w(' * An encoding that reaches no arm publishes nothing and keeps what')
    w(' * the decode table\'s own row recorded.  Called on the path every')
    w(' * legal arm reaches and no illegal one does, so a #UD never gets an')
    w(' * identity for the instruction it was not.')
    w(' */')
    w('static inline void multi0f_ident_publish(int b, int modrm,')
    w('                                         int prefixes)')
    w('{')
    w('    uint16_t idx = multi0f_ident_of(b, modrm, prefixes);')
    w('')
    w('    if (idx) {')
    w('        plugin_gen_record_insn_identity(multi0f_ident_tab[idx].id,')
    w('                                        multi0f_ident_tab[idx].name);')
    w('    }')
    w('}')
    w('')
    with open(path_out, 'w') as f:
        f.write('\n'.join(out))
    with open(path_tr, 'w') as f:
        f.write('\n'.join(src))

    if report:
        print('multi0f_ident: %d arm(s) over %d opcode(s); %d triples '
              'checked, %d qualified, %d residual; %d stale insertion(s) '
              'removed' % (len(rows), len(outer_bs), hits + residual, hits,
                           residual, removed))
        for i, (name, ident, line, arm) in enumerate(rows, 1):
            print('  0x%08x  %-46s %-8s line %5d  %d encoding(s)'
                  % (ident, name, arm[5], line, reached[i]))
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--translate', default='target/i386/tcg/translate.c')
    ap.add_argument('--x87', default='target/i386/tcg/x87_ident.c.inc')
    ap.add_argument('-o', default='target/i386/tcg/multi0f_ident.c.inc')
    ap.add_argument('-q', action='store_true')
    a = ap.parse_args()
    return build(a.translate, a.o, a.x87, not a.q)


if __name__ == '__main__':
    sys.exit(main())
