#ifndef CHAMPSIM_TRACER_ENC_FORMATS_MIPS_H
#define CHAMPSIM_TRACER_ENC_FORMATS_MIPS_H

/*
 * THE MIPS ENCODING FORMATS, and which of wt/ws/wd each one
 * carries a VECTOR REGISTER in -- auto-generated by
 * tools/gen_enc_formats.py.  Do not hand-edit a row.
 *
 * Read from QEMU's own target/mips/tcg/msa.decode
 *   md5 cfbd3c7d828aafe861000c63629dfff0, 180 patterns over 18 formats
 * whose header cites MSA32 revision 1.12 (MD00866), the same
 * document champsim_tracer_enc_fields.h cites for the offsets.
 *
 * WHAT A ROW ANSWERS.  champsim_tracer_enc_fields.h says where
 * `wt`, `ws` and `wd` sit in a 32-bit MIPS word.  It cannot say
 * whether the word in hand PUTS A REGISTER THERE: every MSA
 * instruction decodes through one rule, and across the I5, I8,
 * I10, BIT, ELM, 2R and MI10 formats bits 20:16 hold an
 * immediate, a df selector or an opcode subfield.  A register
 * number read out of those bits is a fabrication that no
 * measurement over encodings can detect -- an I8 immediate that
 * spells 14 is bit-for-bit a 3R naming $w14 -- so the answer is
 * a FORMAT fact and it is taken from the format table.
 *
 * .legal carries one bit per SrcEncFieldId: field `f` is a
 * vector register in this pattern iff (legal >> f) & 1.  A word
 * matching NO row is legal in nothing: an encoding whose format
 * this table cannot name is one no field can be read out of.
 *
 * Rows are in DECODETREE ORDER and the first match wins, which
 * is decodetree's own rule inside an overlap group -- `ctcmsa`
 * precedes `sldi` there and must here.
 *
 * A row marked STATED carries a bank the decodetree cannot
 * state: decodetree names bits, and five MSA instructions put a
 * GPR or an MSA control register in a position the format calls
 * ws or wd.  The QEMU translator that proves each is named.
 */

typedef struct {
    uint32_t    mask;   /* the bits this pattern fixes         */
    uint32_t    value;  /* what it fixes them to               */
    uint8_t     legal;  /* 1u << SrcEncFieldId, per field      */
    const char *name;   /* the decodetree pattern's own name   */
} SrcEncFormatRow;

static const SrcEncFormatRow g_src_enc_formats_mips[] = {
    { 0xfc00073fu, 0x00000005u, 0u,                                                        "LSA" },
        /* target/mips/tcg/msa.decode:51  @lsa */
    { 0xfc00073fu, 0x00000015u, 0u,                                                        "DLSA" },
        /* target/mips/tcg/msa.decode:52  @lsa */
    { 0xffe00000u, 0x45600000u, (1u << SRC_ENC_FIELD_MIPS_WT),                             "BZ_V" },
        /* target/mips/tcg/msa.decode:54  @bz_v */
    { 0xffe00000u, 0x45e00000u, (1u << SRC_ENC_FIELD_MIPS_WT),                             "BNZ_V" },
        /* target/mips/tcg/msa.decode:55  @bz_v */
    { 0xff800000u, 0x47000000u, (1u << SRC_ENC_FIELD_MIPS_WT),                             "BZ" },
        /* target/mips/tcg/msa.decode:56  @bz */
    { 0xff800000u, 0x47800000u, (1u << SRC_ENC_FIELD_MIPS_WT),                             "BNZ" },
        /* target/mips/tcg/msa.decode:57  @bz */
    { 0xff00003fu, 0x78000000u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "ANDI" },
        /* target/mips/tcg/msa.decode:59  @i8 */
    { 0xff00003fu, 0x79000000u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "ORI" },
        /* target/mips/tcg/msa.decode:60  @i8 */
    { 0xff00003fu, 0x7a000000u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "NORI" },
        /* target/mips/tcg/msa.decode:61  @i8 */
    { 0xff00003fu, 0x7b000000u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "XORI" },
        /* target/mips/tcg/msa.decode:62  @i8 */
    { 0xff00003fu, 0x78000001u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BMNZI" },
        /* target/mips/tcg/msa.decode:63  @i8 */
    { 0xff00003fu, 0x79000001u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BMZI" },
        /* target/mips/tcg/msa.decode:64  @i8 */
    { 0xff00003fu, 0x7a000001u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BSELI" },
        /* target/mips/tcg/msa.decode:65  @i8 */
    { 0xfc00003fu, 0x78000002u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SHF" },
        /* target/mips/tcg/msa.decode:66  @i8_df */
    { 0xff80003fu, 0x78000006u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "ADDVI" },
        /* target/mips/tcg/msa.decode:68  @u5 */
    { 0xff80003fu, 0x78800006u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SUBVI" },
        /* target/mips/tcg/msa.decode:69  @u5 */
    { 0xff80003fu, 0x79000006u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "MAXI_S" },
        /* target/mips/tcg/msa.decode:70  @s5 */
    { 0xff80003fu, 0x79800006u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "MAXI_U" },
        /* target/mips/tcg/msa.decode:71  @u5 */
    { 0xff80003fu, 0x7a000006u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "MINI_S" },
        /* target/mips/tcg/msa.decode:72  @s5 */
    { 0xff80003fu, 0x7a800006u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "MINI_U" },
        /* target/mips/tcg/msa.decode:73  @u5 */
    { 0xff80003fu, 0x78000007u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "CEQI" },
        /* target/mips/tcg/msa.decode:75  @s5 */
    { 0xff80003fu, 0x79000007u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "CLTI_S" },
        /* target/mips/tcg/msa.decode:76  @s5 */
    { 0xff80003fu, 0x79800007u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "CLTI_U" },
        /* target/mips/tcg/msa.decode:77  @u5 */
    { 0xff80003fu, 0x7a000007u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "CLEI_S" },
        /* target/mips/tcg/msa.decode:78  @s5 */
    { 0xff80003fu, 0x7a800007u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "CLEI_U" },
        /* target/mips/tcg/msa.decode:79  @u5 */
    { 0xff80003fu, 0x7b000007u, (1u << SRC_ENC_FIELD_MIPS_WD),                             "LDI" },
        /* target/mips/tcg/msa.decode:81  @ldi */
    { 0xff80003fu, 0x78000009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SLLI" },
        /* target/mips/tcg/msa.decode:83  @bit */
    { 0xff80003fu, 0x78800009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SRAI" },
        /* target/mips/tcg/msa.decode:84  @bit */
    { 0xff80003fu, 0x79000009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SRLI" },
        /* target/mips/tcg/msa.decode:85  @bit */
    { 0xff80003fu, 0x79800009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BCLRI" },
        /* target/mips/tcg/msa.decode:86  @bit */
    { 0xff80003fu, 0x7a000009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BSETI" },
        /* target/mips/tcg/msa.decode:87  @bit */
    { 0xff80003fu, 0x7a800009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BNEGI" },
        /* target/mips/tcg/msa.decode:88  @bit */
    { 0xff80003fu, 0x7b000009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BINSLI" },
        /* target/mips/tcg/msa.decode:89  @bit */
    { 0xff80003fu, 0x7b800009u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "BINSRI" },
        /* target/mips/tcg/msa.decode:90  @bit */
    { 0xff80003fu, 0x7800000au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SAT_S" },
        /* target/mips/tcg/msa.decode:92  @bit */
    { 0xff80003fu, 0x7880000au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SAT_U" },
        /* target/mips/tcg/msa.decode:93  @bit */
    { 0xff80003fu, 0x7900000au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SRARI" },
        /* target/mips/tcg/msa.decode:94  @bit */
    { 0xff80003fu, 0x7980000au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SRLRI" },
        /* target/mips/tcg/msa.decode:95  @bit */
    { 0xff80003fu, 0x7800000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SLL" },
        /* target/mips/tcg/msa.decode:97  @3r */
    { 0xff80003fu, 0x7880000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SRA" },
        /* target/mips/tcg/msa.decode:98  @3r */
    { 0xff80003fu, 0x7900000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SRL" },
        /* target/mips/tcg/msa.decode:99  @3r */
    { 0xff80003fu, 0x7980000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BCLR" },
        /* target/mips/tcg/msa.decode:100  @3r */
    { 0xff80003fu, 0x7a00000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BSET" },
        /* target/mips/tcg/msa.decode:101  @3r */
    { 0xff80003fu, 0x7a80000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BNEG" },
        /* target/mips/tcg/msa.decode:102  @3r */
    { 0xff80003fu, 0x7b00000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BINSL" },
        /* target/mips/tcg/msa.decode:103  @3r */
    { 0xff80003fu, 0x7b80000du, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BINSR" },
        /* target/mips/tcg/msa.decode:104  @3r */
    { 0xff80003fu, 0x7800000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ADDV" },
        /* target/mips/tcg/msa.decode:106  @3r */
    { 0xff80003fu, 0x7880000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SUBV" },
        /* target/mips/tcg/msa.decode:107  @3r */
    { 0xff80003fu, 0x7900000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MAX_S" },
        /* target/mips/tcg/msa.decode:108  @3r */
    { 0xff80003fu, 0x7980000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MAX_U" },
        /* target/mips/tcg/msa.decode:109  @3r */
    { 0xff80003fu, 0x7a00000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MIN_S" },
        /* target/mips/tcg/msa.decode:110  @3r */
    { 0xff80003fu, 0x7a80000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MIN_U" },
        /* target/mips/tcg/msa.decode:111  @3r */
    { 0xff80003fu, 0x7b00000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MAX_A" },
        /* target/mips/tcg/msa.decode:112  @3r */
    { 0xff80003fu, 0x7b80000eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MIN_A" },
        /* target/mips/tcg/msa.decode:113  @3r */
    { 0xff80003fu, 0x7800000fu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "CEQ" },
        /* target/mips/tcg/msa.decode:115  @3r */
    { 0xff80003fu, 0x7900000fu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "CLT_S" },
        /* target/mips/tcg/msa.decode:116  @3r */
    { 0xff80003fu, 0x7980000fu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "CLT_U" },
        /* target/mips/tcg/msa.decode:117  @3r */
    { 0xff80003fu, 0x7a00000fu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "CLE_S" },
        /* target/mips/tcg/msa.decode:118  @3r */
    { 0xff80003fu, 0x7a80000fu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "CLE_U" },
        /* target/mips/tcg/msa.decode:119  @3r */
    { 0xff80003fu, 0x78000010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ADD_A" },
        /* target/mips/tcg/msa.decode:121  @3r */
    { 0xff80003fu, 0x78800010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ADDS_A" },
        /* target/mips/tcg/msa.decode:122  @3r */
    { 0xff80003fu, 0x79000010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ADDS_S" },
        /* target/mips/tcg/msa.decode:123  @3r */
    { 0xff80003fu, 0x79800010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ADDS_U" },
        /* target/mips/tcg/msa.decode:124  @3r */
    { 0xff80003fu, 0x7a000010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "AVE_S" },
        /* target/mips/tcg/msa.decode:125  @3r */
    { 0xff80003fu, 0x7a800010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "AVE_U" },
        /* target/mips/tcg/msa.decode:126  @3r */
    { 0xff80003fu, 0x7b000010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "AVER_S" },
        /* target/mips/tcg/msa.decode:127  @3r */
    { 0xff80003fu, 0x7b800010u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "AVER_U" },
        /* target/mips/tcg/msa.decode:128  @3r */
    { 0xff80003fu, 0x78000011u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SUBS_S" },
        /* target/mips/tcg/msa.decode:130  @3r */
    { 0xff80003fu, 0x78800011u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SUBS_U" },
        /* target/mips/tcg/msa.decode:131  @3r */
    { 0xff80003fu, 0x79000011u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SUBSUS_U" },
        /* target/mips/tcg/msa.decode:132  @3r */
    { 0xff80003fu, 0x79800011u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SUBSUU_S" },
        /* target/mips/tcg/msa.decode:133  @3r */
    { 0xff80003fu, 0x7a000011u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ASUB_S" },
        /* target/mips/tcg/msa.decode:134  @3r */
    { 0xff80003fu, 0x7a800011u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ASUB_U" },
        /* target/mips/tcg/msa.decode:135  @3r */
    { 0xff80003fu, 0x78000012u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MULV" },
        /* target/mips/tcg/msa.decode:137  @3r */
    { 0xff80003fu, 0x78800012u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MADDV" },
        /* target/mips/tcg/msa.decode:138  @3r */
    { 0xff80003fu, 0x79000012u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MSUBV" },
        /* target/mips/tcg/msa.decode:139  @3r */
    { 0xff80003fu, 0x7a000012u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DIV_S" },
        /* target/mips/tcg/msa.decode:140  @3r */
    { 0xff80003fu, 0x7a800012u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DIV_U" },
        /* target/mips/tcg/msa.decode:141  @3r */
    { 0xff80003fu, 0x7b000012u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MOD_S" },
        /* target/mips/tcg/msa.decode:142  @3r */
    { 0xff80003fu, 0x7b800012u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MOD_U" },
        /* target/mips/tcg/msa.decode:143  @3r */
    { 0xff80003fu, 0x78000013u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DOTP_S" },
        /* target/mips/tcg/msa.decode:145  @3r */
    { 0xff80003fu, 0x78800013u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DOTP_U" },
        /* target/mips/tcg/msa.decode:146  @3r */
    { 0xff80003fu, 0x79000013u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DPADD_S" },
        /* target/mips/tcg/msa.decode:147  @3r */
    { 0xff80003fu, 0x79800013u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DPADD_U" },
        /* target/mips/tcg/msa.decode:148  @3r */
    { 0xff80003fu, 0x7a000013u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DPSUB_S" },
        /* target/mips/tcg/msa.decode:149  @3r */
    { 0xff80003fu, 0x7a800013u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "DPSUB_U" },
        /* target/mips/tcg/msa.decode:150  @3r */
    { 0xff80003fu, 0x78000014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SLD" },
        /* target/mips/tcg/msa.decode:152  STATED: helper_msa_sld_df: msa_sld_df(..., env->active_tc.gpr[rt]) -- wt is rt */
    { 0xff80003fu, 0x78800014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SPLAT" },
        /* target/mips/tcg/msa.decode:153  STATED: helper_msa_splat_df: msa_splat_df(..., env->active_tc.gpr[rt]) -- wt is rt */
    { 0xff80003fu, 0x79000014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "PCKEV" },
        /* target/mips/tcg/msa.decode:154  @3r */
    { 0xff80003fu, 0x79800014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "PCKOD" },
        /* target/mips/tcg/msa.decode:155  @3r */
    { 0xff80003fu, 0x7a000014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ILVL" },
        /* target/mips/tcg/msa.decode:156  @3r */
    { 0xff80003fu, 0x7a800014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ILVR" },
        /* target/mips/tcg/msa.decode:157  @3r */
    { 0xff80003fu, 0x7b000014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ILVEV" },
        /* target/mips/tcg/msa.decode:158  @3r */
    { 0xff80003fu, 0x7b800014u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "ILVOD" },
        /* target/mips/tcg/msa.decode:159  @3r */
    { 0xff80003fu, 0x78000015u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "VSHF" },
        /* target/mips/tcg/msa.decode:161  @3r */
    { 0xff80003fu, 0x78800015u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SRAR" },
        /* target/mips/tcg/msa.decode:162  @3r */
    { 0xff80003fu, 0x79000015u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "SRLR" },
        /* target/mips/tcg/msa.decode:163  @3r */
    { 0xff80003fu, 0x7a000015u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "HADD_S" },
        /* target/mips/tcg/msa.decode:164  @3r */
    { 0xff80003fu, 0x7a800015u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "HADD_U" },
        /* target/mips/tcg/msa.decode:165  @3r */
    { 0xff80003fu, 0x7b000015u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "HSUB_S" },
        /* target/mips/tcg/msa.decode:166  @3r */
    { 0xff80003fu, 0x7b800015u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "HSUB_U" },
        /* target/mips/tcg/msa.decode:167  @3r */
    { 0xffff003fu, 0x783e0019u, 0u,                                                        "CTCMSA" },
        /* target/mips/tcg/msa.decode:170  STATED: trans_CTCMSA: gen_load_gpr(a->ws); wd is the control index */
    { 0xffc0003fu, 0x78000019u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SLDI" },
        /* target/mips/tcg/msa.decode:171  @elm_df */
    { 0xffff003fu, 0x787e0019u, 0u,                                                        "CFCMSA" },
        /* target/mips/tcg/msa.decode:174  STATED: trans_CFCMSA: a->ws is the control index; gen_store_gpr(a->wd) */
    { 0xffc0003fu, 0x78400019u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "SPLATI" },
        /* target/mips/tcg/msa.decode:175  @elm_df */
    { 0xffff003fu, 0x78be0019u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "MOVE_V" },
        /* target/mips/tcg/msa.decode:178  @elm */
    { 0xffc0003fu, 0x78800019u, (1u << SRC_ENC_FIELD_MIPS_WS),                             "COPY_S" },
        /* target/mips/tcg/msa.decode:179  STATED: trans_COPY_S -> trans_msa_elm_fn: wd is the GPR destination */
    { 0xffc0003fu, 0x78c00019u, (1u << SRC_ENC_FIELD_MIPS_WS),                             "COPY_U" },
        /* target/mips/tcg/msa.decode:181  STATED: trans_COPY_U -> trans_msa_elm_fn: wd is the GPR destination */
    { 0xffc0003fu, 0x79000019u, (1u << SRC_ENC_FIELD_MIPS_WD),                             "INSERT" },
        /* target/mips/tcg/msa.decode:182  STATED: trans_INSERT -> trans_msa_elm_fn: ws is the GPR source */
    { 0xffc0003fu, 0x79400019u, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "INSVE" },
        /* target/mips/tcg/msa.decode:183  @elm_df */
    { 0xffc0003fu, 0x7800001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCAF" },
        /* target/mips/tcg/msa.decode:185  @3rf_w */
    { 0xffc0003fu, 0x7840001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCUN" },
        /* target/mips/tcg/msa.decode:186  @3rf_w */
    { 0xffc0003fu, 0x7880001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCEQ" },
        /* target/mips/tcg/msa.decode:187  @3rf_w */
    { 0xffc0003fu, 0x78c0001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCUEQ" },
        /* target/mips/tcg/msa.decode:188  @3rf_w */
    { 0xffc0003fu, 0x7900001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCLT" },
        /* target/mips/tcg/msa.decode:189  @3rf_w */
    { 0xffc0003fu, 0x7940001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCULT" },
        /* target/mips/tcg/msa.decode:190  @3rf_w */
    { 0xffc0003fu, 0x7980001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCLE" },
        /* target/mips/tcg/msa.decode:191  @3rf_w */
    { 0xffc0003fu, 0x79c0001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCULE" },
        /* target/mips/tcg/msa.decode:192  @3rf_w */
    { 0xffc0003fu, 0x7a00001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSAF" },
        /* target/mips/tcg/msa.decode:193  @3rf_w */
    { 0xffc0003fu, 0x7a40001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSUN" },
        /* target/mips/tcg/msa.decode:194  @3rf_w */
    { 0xffc0003fu, 0x7a80001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSEQ" },
        /* target/mips/tcg/msa.decode:195  @3rf_w */
    { 0xffc0003fu, 0x7ac0001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSUEQ" },
        /* target/mips/tcg/msa.decode:196  @3rf_w */
    { 0xffc0003fu, 0x7b00001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSLT" },
        /* target/mips/tcg/msa.decode:197  @3rf_w */
    { 0xffc0003fu, 0x7b40001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSULT" },
        /* target/mips/tcg/msa.decode:198  @3rf_w */
    { 0xffc0003fu, 0x7b80001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSLE" },
        /* target/mips/tcg/msa.decode:199  @3rf_w */
    { 0xffc0003fu, 0x7bc0001au, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSULE" },
        /* target/mips/tcg/msa.decode:200  @3rf_w */
    { 0xffc0003fu, 0x7800001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FADD" },
        /* target/mips/tcg/msa.decode:202  @3rf_w */
    { 0xffc0003fu, 0x7840001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSUB" },
        /* target/mips/tcg/msa.decode:203  @3rf_w */
    { 0xffc0003fu, 0x7880001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FMUL" },
        /* target/mips/tcg/msa.decode:204  @3rf_w */
    { 0xffc0003fu, 0x78c0001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FDIV" },
        /* target/mips/tcg/msa.decode:205  @3rf_w */
    { 0xffc0003fu, 0x7900001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FMADD" },
        /* target/mips/tcg/msa.decode:206  @3rf_w */
    { 0xffc0003fu, 0x7940001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FMSUB" },
        /* target/mips/tcg/msa.decode:207  @3rf_w */
    { 0xffc0003fu, 0x79c0001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FEXP2" },
        /* target/mips/tcg/msa.decode:208  @3rf_w */
    { 0xffc0003fu, 0x7a00001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FEXDO" },
        /* target/mips/tcg/msa.decode:209  @3rf_w */
    { 0xffc0003fu, 0x7a80001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FTQ" },
        /* target/mips/tcg/msa.decode:210  @3rf_w */
    { 0xffc0003fu, 0x7b00001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FMIN" },
        /* target/mips/tcg/msa.decode:211  @3rf_w */
    { 0xffc0003fu, 0x7b40001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FMIN_A" },
        /* target/mips/tcg/msa.decode:212  @3rf_w */
    { 0xffc0003fu, 0x7b80001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FMAX" },
        /* target/mips/tcg/msa.decode:213  @3rf_w */
    { 0xffc0003fu, 0x7bc0001bu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FMAX_A" },
        /* target/mips/tcg/msa.decode:214  @3rf_w */
    { 0xffc0003fu, 0x7840001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCOR" },
        /* target/mips/tcg/msa.decode:216  @3rf_w */
    { 0xffc0003fu, 0x7880001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCUNE" },
        /* target/mips/tcg/msa.decode:217  @3rf_w */
    { 0xffc0003fu, 0x78c0001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FCNE" },
        /* target/mips/tcg/msa.decode:218  @3rf_w */
    { 0xffc0003fu, 0x7900001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MUL_Q" },
        /* target/mips/tcg/msa.decode:219  @3rf_h */
    { 0xffc0003fu, 0x7940001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MADD_Q" },
        /* target/mips/tcg/msa.decode:220  @3rf_h */
    { 0xffc0003fu, 0x7980001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MSUB_Q" },
        /* target/mips/tcg/msa.decode:221  @3rf_h */
    { 0xffc0003fu, 0x7a40001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSOR" },
        /* target/mips/tcg/msa.decode:222  @3rf_w */
    { 0xffc0003fu, 0x7a80001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSUNE" },
        /* target/mips/tcg/msa.decode:223  @3rf_w */
    { 0xffc0003fu, 0x7ac0001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "FSNE" },
        /* target/mips/tcg/msa.decode:224  @3rf_w */
    { 0xffc0003fu, 0x7b00001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MULR_Q" },
        /* target/mips/tcg/msa.decode:225  @3rf_h */
    { 0xffc0003fu, 0x7b40001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MADDR_Q" },
        /* target/mips/tcg/msa.decode:226  @3rf_h */
    { 0xffc0003fu, 0x7b80001cu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "MSUBR_Q" },
        /* target/mips/tcg/msa.decode:227  @3rf_h */
    { 0xffe0003fu, 0x7800001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "AND_V" },
        /* target/mips/tcg/msa.decode:229  @vec */
    { 0xffe0003fu, 0x7820001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "OR_V" },
        /* target/mips/tcg/msa.decode:230  @vec */
    { 0xffe0003fu, 0x7840001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "NOR_V" },
        /* target/mips/tcg/msa.decode:231  @vec */
    { 0xffe0003fu, 0x7860001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "XOR_V" },
        /* target/mips/tcg/msa.decode:232  @vec */
    { 0xffe0003fu, 0x7880001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BMNZ_V" },
        /* target/mips/tcg/msa.decode:233  @vec */
    { 0xffe0003fu, 0x78a0001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BMZ_V" },
        /* target/mips/tcg/msa.decode:234  @vec */
    { 0xffe0003fu, 0x78c0001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS) | (1u << SRC_ENC_FIELD_MIPS_WT), "BSEL_V" },
        /* target/mips/tcg/msa.decode:235  @vec */
    { 0xfffc003fu, 0x7b00001eu, (1u << SRC_ENC_FIELD_MIPS_WD),                             "FILL" },
        /* target/mips/tcg/msa.decode:236  STATED: helper_msa_fill_df: pwd->b[i] = env->active_tc.gpr[rs] -- ws is rs */
    { 0xfffc003fu, 0x7b04001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "PCNT" },
        /* target/mips/tcg/msa.decode:237  @2r */
    { 0xfffc003fu, 0x7b08001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "NLOC" },
        /* target/mips/tcg/msa.decode:238  @2r */
    { 0xfffc003fu, 0x7b0c001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "NLZC" },
        /* target/mips/tcg/msa.decode:239  @2r */
    { 0xfffe003fu, 0x7b20001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FCLASS" },
        /* target/mips/tcg/msa.decode:240  @2rf */
    { 0xfffe003fu, 0x7b22001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FTRUNC_S" },
        /* target/mips/tcg/msa.decode:241  @2rf */
    { 0xfffe003fu, 0x7b24001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FTRUNC_U" },
        /* target/mips/tcg/msa.decode:242  @2rf */
    { 0xfffe003fu, 0x7b26001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FSQRT" },
        /* target/mips/tcg/msa.decode:243  @2rf */
    { 0xfffe003fu, 0x7b28001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FRSQRT" },
        /* target/mips/tcg/msa.decode:244  @2rf */
    { 0xfffe003fu, 0x7b2a001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FRCP" },
        /* target/mips/tcg/msa.decode:245  @2rf */
    { 0xfffe003fu, 0x7b2c001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FRINT" },
        /* target/mips/tcg/msa.decode:246  @2rf */
    { 0xfffe003fu, 0x7b2e001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FLOG2" },
        /* target/mips/tcg/msa.decode:247  @2rf */
    { 0xfffe003fu, 0x7b30001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FEXUPL" },
        /* target/mips/tcg/msa.decode:248  @2rf */
    { 0xfffe003fu, 0x7b32001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FEXUPR" },
        /* target/mips/tcg/msa.decode:249  @2rf */
    { 0xfffe003fu, 0x7b34001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FFQL" },
        /* target/mips/tcg/msa.decode:250  @2rf */
    { 0xfffe003fu, 0x7b36001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FFQR" },
        /* target/mips/tcg/msa.decode:251  @2rf */
    { 0xfffe003fu, 0x7b38001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FTINT_S" },
        /* target/mips/tcg/msa.decode:252  @2rf */
    { 0xfffe003fu, 0x7b3a001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FTINT_U" },
        /* target/mips/tcg/msa.decode:253  @2rf */
    { 0xfffe003fu, 0x7b3c001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FFINT_S" },
        /* target/mips/tcg/msa.decode:254  @2rf */
    { 0xfffe003fu, 0x7b3e001eu, (1u << SRC_ENC_FIELD_MIPS_WD) | (1u << SRC_ENC_FIELD_MIPS_WS), "FFINT_U" },
        /* target/mips/tcg/msa.decode:255  @2rf */
    { 0xfc00003cu, 0x78000020u, (1u << SRC_ENC_FIELD_MIPS_WD),                             "LD" },
        /* target/mips/tcg/msa.decode:257  STATED: trans_msa_ldst: gen_base_offset_addr(a->ws) -- ws is the base GPR */
    { 0xfc00003cu, 0x78000024u, (1u << SRC_ENC_FIELD_MIPS_WD),                             "ST" },
        /* target/mips/tcg/msa.decode:258  STATED: trans_msa_ldst: gen_base_offset_addr(a->ws) -- ws is the base GPR */
};

/*
 * The fields @word may be read as a register out of, or 0.
 * Linear and first-match: the table is a few hundred rows, this
 * runs at TRANSLATION time only, and a bisect would have to
 * reorder rows whose order is the decode semantics.
 */
static inline uint8_t src_enc_format_legal_mips(uint32_t word)
{
    for (unsigned i = 0; i < G_N_ELEMENTS(g_src_enc_formats_mips);
         i++) {
        const SrcEncFormatRow *r = &g_src_enc_formats_mips[i];

        if ((word & r->mask) == r->value) {
            return r->legal;
        }
    }
    return 0;
}

#endif /* CHAMPSIM_TRACER_ENC_FORMATS_MIPS_H */
