#ifndef CHAMPSIM_TRACER_QEMU_REGS_AARCH64_H
#define CHAMPSIM_TRACER_QEMU_REGS_AARCH64_H

/*
 * QEMU-indexed register table for aarch64 -- auto-generated by
 * champsim_tracer_mnemonic_audit.py --qemu-regs.  Do not hand-edit a row.
 *
 * One row per register QEMU can NAME: its GDB-stub
 * namespace -- what qemu_plugin_get_registers() reports --
 * plus the register files the target DECLARES to the
 * dataflow extractor (insn_dataflow_declare_regfile), which
 * insn_dataflow_field_reg() answers in and the stub need not
 * carry.  Sorted by (feature, name) so a consumer can
 * bisect.  This is the
 * authority for what generic dependency slot a register is;
 * the Capstone-keyed table is a route to these rows and is
 * cross-checked against them at install.
 *
 * .tier says whether the Capstone key can reach the row:
 *   QREG_ROUTED   at least one Capstone register id maps here
 *   QREG_UNNAMED  QEMU carries the register and Capstone's enum
 *                 has no id for it, so no Capstone-fed operand
 *                 can ever name it.  These rows are reachable
 *                 only by QEMU identity.
 *   QREG_PREDICATED  QEMU carries it only when a run-time
 *                 predicate admits it (the RISC-V CSR space,
 *                 filtered through csr_ops[].predicate).  The
 *                 row answers what generic word the NAME is;
 *                 it does not stand for its class's VALUE.
 *   QREG_DECLARED  QEMU names it only through a target
 *                 declaration and its GDB stub does not carry
 *                 it, so no handle can read the register.
 *                 Same division as QREG_PREDICATED: the row
 *                 answers the NAME, never the VALUE.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * Author: Maccoy Merrell
 */

/* aarch64: 131 QEMU registers, 116 reachable from
 * Capstone, 15 reachable only by QEMU identity,
 * 13 of those named by a target declaration rather than by
 * the GDB stub, 130 carrying a generic id. */
static const QemuRegRow qemu_regs_aarch64[] = {
    { .feature = "org.gnu.gdb.aarch64.core", .name = "cpsr", .reg_id = REG_FLAGS, .is_int_flags = true, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "pc", .reg_id = REG_NONE, .cap_rows = 0, .tier = QREG_UNNAMED },
    { .feature = "org.gnu.gdb.aarch64.core", .name = "sp", .reg_id = REG_SP, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x0", .reg_id = REG_GPR0, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x1", .reg_id = REG_GPR1, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x10", .reg_id = REG_GPR10, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x11", .reg_id = REG_GPR11, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x12", .reg_id = REG_GPR12, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x13", .reg_id = REG_GPR13, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x14", .reg_id = REG_GPR14, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x15", .reg_id = REG_GPR15, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x16", .reg_id = REG_GPR16, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x17", .reg_id = REG_GPR17, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x18", .reg_id = REG_GPR18, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x19", .reg_id = REG_GPR19, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x2", .reg_id = REG_GPR2, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x20", .reg_id = REG_GPR20, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x21", .reg_id = REG_GPR21, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x22", .reg_id = REG_GPR22, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x23", .reg_id = REG_GPR23, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x24", .reg_id = REG_GPR24, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x25", .reg_id = REG_GPR25, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x26", .reg_id = REG_GPR26, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x27", .reg_id = REG_GPR27, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x28", .reg_id = REG_GPR28, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x29", .reg_id = REG_FP_REG, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x3", .reg_id = REG_GPR3, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x30", .reg_id = REG_LR, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x4", .reg_id = REG_GPR4, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x5", .reg_id = REG_GPR5, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x6", .reg_id = REG_GPR6, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x7", .reg_id = REG_GPR7, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x8", .reg_id = REG_GPR8, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.core", .name = "x9", .reg_id = REG_GPR9, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "fpcr", .reg_id = REG_FPCW, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "fpsr", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* AArch64 FP STATUS word S3_3_C4_C4_1 (env->vfp.fpsr); OBSERVED as the destination of every FP arithmetic decode -- the control half is fpcr/REG_FPCW */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v0", .reg_id = REG_VEC0, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v1", .reg_id = REG_VEC1, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v10", .reg_id = REG_VEC10, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v11", .reg_id = REG_VEC11, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v12", .reg_id = REG_VEC12, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v13", .reg_id = REG_VEC13, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v14", .reg_id = REG_VEC14, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v15", .reg_id = REG_VEC15, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v16", .reg_id = REG_VEC16, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v17", .reg_id = REG_VEC17, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v18", .reg_id = REG_VEC18, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v19", .reg_id = REG_VEC19, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v2", .reg_id = REG_VEC2, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v20", .reg_id = REG_VEC20, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v21", .reg_id = REG_VEC21, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v22", .reg_id = REG_VEC22, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v23", .reg_id = REG_VEC23, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v24", .reg_id = REG_VEC24, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v25", .reg_id = REG_VEC25, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v26", .reg_id = REG_VEC26, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v27", .reg_id = REG_VEC27, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v28", .reg_id = REG_VEC28, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v29", .reg_id = REG_VEC29, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v3", .reg_id = REG_VEC3, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v30", .reg_id = REG_VEC30, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v31", .reg_id = REG_VEC31, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v4", .reg_id = REG_VEC4, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v5", .reg_id = REG_VEC5, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v6", .reg_id = REG_VEC6, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v7", .reg_id = REG_VEC7, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v8", .reg_id = REG_VEC8, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.fpu", .name = "v9", .reg_id = REG_VEC9, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "ffr", .reg_id = REG_PRED16, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p0", .reg_id = REG_PRED0, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p1", .reg_id = REG_PRED1, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p10", .reg_id = REG_PRED10, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p11", .reg_id = REG_PRED11, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p12", .reg_id = REG_PRED12, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p13", .reg_id = REG_PRED13, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p14", .reg_id = REG_PRED14, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p15", .reg_id = REG_PRED15, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p2", .reg_id = REG_PRED2, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p3", .reg_id = REG_PRED3, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p4", .reg_id = REG_PRED4, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p5", .reg_id = REG_PRED5, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p6", .reg_id = REG_PRED6, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p7", .reg_id = REG_PRED7, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p8", .reg_id = REG_PRED8, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "p9", .reg_id = REG_PRED9, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "vg", .reg_id = REG_VCTRL, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z0", .reg_id = REG_VEC0, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z1", .reg_id = REG_VEC1, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z10", .reg_id = REG_VEC10, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z11", .reg_id = REG_VEC11, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z12", .reg_id = REG_VEC12, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z13", .reg_id = REG_VEC13, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z14", .reg_id = REG_VEC14, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z15", .reg_id = REG_VEC15, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z16", .reg_id = REG_VEC16, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z17", .reg_id = REG_VEC17, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z18", .reg_id = REG_VEC18, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z19", .reg_id = REG_VEC19, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z2", .reg_id = REG_VEC2, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z20", .reg_id = REG_VEC20, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z21", .reg_id = REG_VEC21, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z22", .reg_id = REG_VEC22, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z23", .reg_id = REG_VEC23, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z24", .reg_id = REG_VEC24, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z25", .reg_id = REG_VEC25, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z26", .reg_id = REG_VEC26, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z27", .reg_id = REG_VEC27, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z28", .reg_id = REG_VEC28, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z29", .reg_id = REG_VEC29, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z3", .reg_id = REG_VEC3, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z30", .reg_id = REG_VEC30, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z31", .reg_id = REG_VEC31, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z4", .reg_id = REG_VEC4, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z5", .reg_id = REG_VEC5, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z6", .reg_id = REG_VEC6, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z7", .reg_id = REG_VEC7, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z8", .reg_id = REG_VEC8, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.aarch64.sve", .name = "z9", .reg_id = REG_VEC9, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "qemu.declared-regfile", .name = "cpacr_el1", .reg_id = REG_SYSFPEN, .cap_rows = 0, .tier = QREG_DECLARED },  /* the FP/SIMD EXECUTION-ENABLE GATE, a source of every instruction it gates (R7.4).  REG_SYSFPEN is the vocabulary's word for it and names it in those terms; CPTR_EL2/EL3 are the same gate at the higher exception levels and the declaration names EL1 alone */
    { .feature = "qemu.declared-regfile", .name = "fp_status0", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fp_status1", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fp_status2", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fp_status3", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fp_status4", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fp_status5", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fp_status6", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fp_status7", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* the SOFTFLOAT STATUS FILE: QEMU's split of the architectural FP control-and-status file by operating regime.  The generator's standing rule for a control-and-status file that cannot be split into control and status halves is REG_FCSR, and the element number is a storage fact, not an architectural one */
    { .feature = "qemu.declared-regfile", .name = "fpsr_qc", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_DECLARED },  /* FPSR.QC, the cumulative saturation bit, held in vfp.qc[] so a gvec op can OR into it.  The SAME architectural register as the status file above -- FPSR bit 27 -- reaching the same word by the same rule; the two spellings exist because the two byte ranges do */
    { .feature = "qemu.declared-regfile", .name = "gcr_el1", .reg_id = REG_SYS, .cap_rows = 0, .tier = QREG_DECLARED },  /* the tag-generation control `irg` reads.  REG_SYS is the vocabulary's residual privileged-file word, it has no finer class for a tag-generation control, and REG_SYS is what the wire already publishes for this register */
    { .feature = "qemu.declared-regfile", .name = "svcr", .reg_id = REG_VCTRL, .cap_rows = 0, .tier = QREG_DECLARED },  /* SME's streaming-mode and ZA-enable control.  REG_VCTRL is the word for the state that says how wide a vector operation is and how much of it is active -- SVE's `vg` and RISC-V's `vl`/`vtype` seat there -- and SVCR.SM selects between the non-streaming and the streaming vector length while SVCR.ZA gates the ZA array.  BY ROLE, not by elimination, and it is what the boundary already publishes from the AARCH64_OP_SVCR sysop operand */
    { .feature = "qemu.declared-regfile", .name = "tpidr_el0", .reg_id = REG_TLS, .cap_rows = 0, .tier = QREG_DECLARED },  /* the THREAD POINTER, cp15.tpidr_el[0].  REG_TLS is the vocabulary's own word for this register and names it outright ("AArch64 TPIDR_EL0 / MIPS CP0_UserLocal") */
};

static const size_t qemu_regs_aarch64_count =
    sizeof(qemu_regs_aarch64) / sizeof(qemu_regs_aarch64[0]);

#endif /* CHAMPSIM_TRACER_QEMU_REGS_AARCH64_H */
