#ifndef CHAMPSIM_TRACER_MNEMONICS_X86_H
#define CHAMPSIM_TRACER_MNEMONICS_X86_H

/*
 * ISA-specific classification tables for champsim_tracer — x86.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include <capstone/capstone.h>
#include <capstone/x86.h>

static unsigned int cap_mode_x86(const char *target_name)
{
    (void)target_name;
    /*
     * The Capstone decode of i386 instructions in 64-bit mode covers
     * the same encodings; we don't currently distinguish 32-vs-64-bit
     * instruction streams here.
     */
    return CS_MODE_64;
}

/*
 * x86 system-register operand name -> the name QEMU's register list
 * uses for the same register.
 *
 * The boundary names these registers architecturally (Intel's `fpcw`
 * and `fptag`); QEMU inherited GDB's i386 spelling (`fctrl`, `ftag`)
 * for the same two.  Everything else on the boundary's list --
 * gdtr/idtr/ldtr/tr, the MSR window, tsc/tscaux, xcr0, ssp -- has no
 * entry in the descriptor list at all, and NULL here says so
 * explicitly rather than letting a near-miss spelling resolve to some
 * other register's value.
 */
static const char *x86_sysreg_qemu_name(const char *name)
{
    if (!name || !name[0]) {
        return NULL;
    }
    if (cst_str_eq(name, "mxcsr")) {
        return "mxcsr";
    }
    if (cst_str_eq(name, "fpcw")) {
        return "fctrl";
    }
    if (cst_str_eq(name, "fptag")) {
        return "ftag";
    }
    return NULL;
}

/*
 * x86 EFLAGS → canonical CST_METAFLAGS layout.  Mapping table:
 *   bit  0  CF -> CST_METAFLAGS_C
 *   bit  2  PF -> CST_METAFLAGS_P
 *   bit  6  ZF -> CST_METAFLAGS_Z
 *   bit  7  SF -> CST_METAFLAGS_N
 *   bit 11  OF -> CST_METAFLAGS_V
 * System bits (TF, IF, DF, IOPL, NT, RF, VM, AC, VIF, VIP, ID) and
 * the rest of RFLAGS are not exposed in the canonical view; consumers
 * that need them can keep reading the architectural REG_FLAGS slot.
 */
static uint8_t x86_flags_to_metaflags(uint64_t raw)
{
    uint8_t mf = 0;
    if (raw & (1u << 0))  mf |= CST_METAFLAGS_C;
    if (raw & (1u << 2))  mf |= CST_METAFLAGS_P;
    if (raw & (1u << 6))  mf |= CST_METAFLAGS_Z;
    if (raw & (1u << 7))  mf |= CST_METAFLAGS_N;
    if (raw & (1u << 11)) mf |= CST_METAFLAGS_V;
    return mf;
}

/*
 * x86-64 address canonicalization.  A valid virtual address is in
 * 48-bit canonical form: bits [63:48] replicate bit 47.  The MMU
 * faults a non-canonical address, so a genuine stored pointer and
 * the effective address that dereferences it are both already
 * canonical; sign-extending bit 47 normalises either form to the
 * same value and is the natural home for a future Linear Address
 * Masking (LAM) tag strip.  x86 carries no address tagging today.
 */
static uint64_t x86_canonicalize_addr(uint64_t a)
{
    return (uint64_t)(((int64_t)(a << 16)) >> 16);
}


/* Register classification table. */
static const RegClassification x86_reg_class[X86_REG_ENDING] = {
    /* Auto-generated by champsim_tracer_mnemonic_audit.py. */
    /* x86 regs: 243/246 mapped, 2 intentionally ignored */
    [X86_REG_INVALID] = {},
    [X86_REG_AH] = { .reg_id = REG_GPR0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rax" } },  /* ah */
    [X86_REG_AL] = { .reg_id = REG_GPR0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rax" } },  /* al */
    [X86_REG_AX] = { .reg_id = REG_GPR0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rax" } },  /* ax */
    [X86_REG_BH] = { .reg_id = REG_GPR3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbx" } },  /* bh */
    [X86_REG_BL] = { .reg_id = REG_GPR3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbx" } },  /* bl */
    [X86_REG_BP] = { .reg_id = REG_FP_REG, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbp" } },  /* bp */
    [X86_REG_BPL] = { .reg_id = REG_FP_REG, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbp" } },  /* bpl */
    [X86_REG_BX] = { .reg_id = REG_GPR3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbx" } },  /* bx */
    [X86_REG_CH] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rcx" } },  /* ch */
    [X86_REG_CL] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rcx" } },  /* cl */
    [X86_REG_CS] = { .reg_id = REG_SEG0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "cs" } },  /* cs */
    [X86_REG_CX] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rcx" } },  /* cx */
    [X86_REG_DH] = { .reg_id = REG_GPR2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdx" } },  /* dh */
    [X86_REG_DI] = { .reg_id = REG_GPR5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdi" } },  /* di */
    [X86_REG_DIL] = { .reg_id = REG_GPR5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdi" } },  /* dil */
    [X86_REG_DL] = { .reg_id = REG_GPR2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdx" } },  /* dl */
    [X86_REG_DS] = { .reg_id = REG_SEG1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "ds" } },  /* ds */
    [X86_REG_DX] = { .reg_id = REG_GPR2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdx" } },  /* dx */
    [X86_REG_EAX] = { .reg_id = REG_GPR0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rax" } },  /* eax */
    [X86_REG_EBP] = { .reg_id = REG_FP_REG, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbp" } },  /* ebp */
    [X86_REG_EBX] = { .reg_id = REG_GPR3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbx" } },  /* ebx */
    [X86_REG_ECX] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rcx" } },  /* ecx */
    [X86_REG_EDI] = { .reg_id = REG_GPR5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdi" } },  /* edi */
    [X86_REG_EDX] = { .reg_id = REG_GPR2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdx" } },  /* edx */
    [X86_REG_EFLAGS] = { .reg_id = REG_FLAGS, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "eflags" }, .is_int_flags = true },  /* eflags */
    [X86_REG_EIP] = { .reg_id = REG_PC, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rip" } },  /* eip */
    [X86_REG_EIZ] = {},
    [X86_REG_ES] = { .reg_id = REG_SEG2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "es" } },  /* es */
    [X86_REG_ESI] = { .reg_id = REG_GPR4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsi" } },  /* esi */
    [X86_REG_ESP] = { .reg_id = REG_SP, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsp" } },  /* esp */
    [X86_REG_FPSW] = { .reg_id = REG_FCSR, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "fstat" } },  /* fpsw */
    [X86_REG_FS] = { .reg_id = REG_SEG3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "fs" } },  /* fs */
    [X86_REG_GS] = { .reg_id = REG_SEG4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "gs" } },  /* gs */
    [X86_REG_IP] = { .reg_id = REG_PC, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rip" } },  /* ip */
    [X86_REG_RAX] = { .reg_id = REG_GPR0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rax" } },  /* rax */
    [X86_REG_RBP] = { .reg_id = REG_FP_REG, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbp" } },  /* rbp */
    [X86_REG_RBX] = { .reg_id = REG_GPR3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rbx" } },  /* rbx */
    [X86_REG_RCX] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rcx" } },  /* rcx */
    [X86_REG_RDI] = { .reg_id = REG_GPR5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdi" } },  /* rdi */
    [X86_REG_RDX] = { .reg_id = REG_GPR2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rdx" } },  /* rdx */
    [X86_REG_RIP] = { .reg_id = REG_PC, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rip" } },  /* rip */
    [X86_REG_RIZ] = {},
    [X86_REG_RSI] = { .reg_id = REG_GPR4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsi" } },  /* rsi */
    [X86_REG_RSP] = { .reg_id = REG_SP, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsp" } },  /* rsp */
    [X86_REG_SI] = { .reg_id = REG_GPR4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsi" } },  /* si */
    [X86_REG_SIL] = { .reg_id = REG_GPR4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsi" } },  /* sil */
    [X86_REG_SP] = { .reg_id = REG_SP, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsp" } },  /* sp */
    [X86_REG_SPL] = { .reg_id = REG_SP, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "rsp" } },  /* spl */
    [X86_REG_SS] = { .reg_id = REG_SEG5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "ss" } },  /* ss */
    [X86_REG_CR0] = { .reg_id = REG_CTRL0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "cr0" } },  /* cr0 */
    [X86_REG_CR1] = { .reg_id = REG_CTRL1 },  /* cr1 */
    [X86_REG_CR2] = { .reg_id = REG_CTRL2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "cr2" } },  /* cr2 */
    [X86_REG_CR3] = { .reg_id = REG_CTRL3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "cr3" } },  /* cr3 */
    [X86_REG_CR4] = { .reg_id = REG_CTRL4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "cr4" } },  /* cr4 */
    [X86_REG_CR5] = { .reg_id = REG_CTRL5 },  /* cr5 */
    [X86_REG_CR6] = { .reg_id = REG_CTRL6 },  /* cr6 */
    [X86_REG_CR7] = { .reg_id = REG_CTRL7 },  /* cr7 */
    [X86_REG_CR8] = { .reg_id = REG_CTRL8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "cr8" } },  /* cr8 */
    [X86_REG_CR9] = { .reg_id = REG_CTRL9 },  /* cr9 */
    [X86_REG_CR10] = { .reg_id = REG_CTRL10 },  /* cr10 */
    [X86_REG_CR11] = { .reg_id = REG_CTRL11 },  /* cr11 */
    [X86_REG_CR12] = { .reg_id = REG_CTRL12 },  /* cr12 */
    [X86_REG_CR13] = { .reg_id = REG_CTRL13 },  /* cr13 */
    [X86_REG_CR14] = { .reg_id = REG_CTRL14 },  /* cr14 */
    [X86_REG_CR15] = { .reg_id = REG_CTRL15 },  /* cr15 */
    [X86_REG_DR0] = { .reg_id = REG_DEBUG0 },  /* dr0 */
    [X86_REG_DR1] = { .reg_id = REG_DEBUG1 },  /* dr1 */
    [X86_REG_DR2] = { .reg_id = REG_DEBUG2 },  /* dr2 */
    [X86_REG_DR3] = { .reg_id = REG_DEBUG3 },  /* dr3 */
    [X86_REG_DR4] = { .reg_id = REG_DEBUG6 },  /* dr4 */
    [X86_REG_DR5] = { .reg_id = REG_DEBUG7 },  /* dr5 */
    [X86_REG_DR6] = { .reg_id = REG_DEBUG6 },  /* dr6 */
    [X86_REG_DR7] = { .reg_id = REG_DEBUG7 },  /* dr7 */
    [X86_REG_DR8] = { .reg_id = REG_DEBUG8 },  /* dr8 */
    [X86_REG_DR9] = { .reg_id = REG_DEBUG9 },  /* dr9 */
    [X86_REG_DR10] = { .reg_id = REG_DEBUG10 },  /* dr10 */
    [X86_REG_DR11] = { .reg_id = REG_DEBUG11 },  /* dr11 */
    [X86_REG_DR12] = { .reg_id = REG_DEBUG12 },  /* dr12 */
    [X86_REG_DR13] = { .reg_id = REG_DEBUG13 },  /* dr13 */
    [X86_REG_DR14] = { .reg_id = REG_DEBUG14 },  /* dr14 */
    [X86_REG_DR15] = { .reg_id = REG_DEBUG15 },  /* dr15 */
    [X86_REG_FP0] = { .reg_id = REG_FPR0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st0" } },  /* fp0 */
    [X86_REG_FP1] = { .reg_id = REG_FPR1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st1" } },  /* fp1 */
    [X86_REG_FP2] = { .reg_id = REG_FPR2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st2" } },  /* fp2 */
    [X86_REG_FP3] = { .reg_id = REG_FPR3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st3" } },  /* fp3 */
    [X86_REG_FP4] = { .reg_id = REG_FPR4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st4" } },  /* fp4 */
    [X86_REG_FP5] = { .reg_id = REG_FPR5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st5" } },  /* fp5 */
    [X86_REG_FP6] = { .reg_id = REG_FPR6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st6" } },  /* fp6 */
    [X86_REG_FP7] = { .reg_id = REG_FPR7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st7" } },  /* fp7 */
    [X86_REG_K0] = { .reg_id = REG_PRED0 },  /* k0 */
    [X86_REG_K1] = { .reg_id = REG_PRED1 },  /* k1 */
    [X86_REG_K2] = { .reg_id = REG_PRED2 },  /* k2 */
    [X86_REG_K3] = { .reg_id = REG_PRED3 },  /* k3 */
    [X86_REG_K4] = { .reg_id = REG_PRED4 },  /* k4 */
    [X86_REG_K5] = { .reg_id = REG_PRED5 },  /* k5 */
    [X86_REG_K6] = { .reg_id = REG_PRED6 },  /* k6 */
    [X86_REG_K7] = { .reg_id = REG_PRED7 },  /* k7 */
    [X86_REG_MM0] = { .reg_id = REG_FPR0 },  /* mm0 */
    [X86_REG_MM1] = { .reg_id = REG_FPR1 },  /* mm1 */
    [X86_REG_MM2] = { .reg_id = REG_FPR2 },  /* mm2 */
    [X86_REG_MM3] = { .reg_id = REG_FPR3 },  /* mm3 */
    [X86_REG_MM4] = { .reg_id = REG_FPR4 },  /* mm4 */
    [X86_REG_MM5] = { .reg_id = REG_FPR5 },  /* mm5 */
    [X86_REG_MM6] = { .reg_id = REG_FPR6 },  /* mm6 */
    [X86_REG_MM7] = { .reg_id = REG_FPR7 },  /* mm7 */
    [X86_REG_R8] = { .reg_id = REG_GPR6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r8" } },  /* r8 */
    [X86_REG_R9] = { .reg_id = REG_GPR7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r9" } },  /* r9 */
    [X86_REG_R10] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r10" } },  /* r10 */
    [X86_REG_R11] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r11" } },  /* r11 */
    [X86_REG_R12] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r12" } },  /* r12 */
    [X86_REG_R13] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r13" } },  /* r13 */
    [X86_REG_R14] = { .reg_id = REG_GPR12, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r14" } },  /* r14 */
    [X86_REG_R15] = { .reg_id = REG_GPR13, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r15" } },  /* r15 */
    [X86_REG_ST0] = { .reg_id = REG_FPR0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st0" } },  /* st0 */
    [X86_REG_ST1] = { .reg_id = REG_FPR1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st1" } },  /* st1 */
    [X86_REG_ST2] = { .reg_id = REG_FPR2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st2" } },  /* st2 */
    [X86_REG_ST3] = { .reg_id = REG_FPR3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st3" } },  /* st3 */
    [X86_REG_ST4] = { .reg_id = REG_FPR4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st4" } },  /* st4 */
    [X86_REG_ST5] = { .reg_id = REG_FPR5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st5" } },  /* st5 */
    [X86_REG_ST6] = { .reg_id = REG_FPR6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st6" } },  /* st6 */
    [X86_REG_ST7] = { .reg_id = REG_FPR7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "st7" } },  /* st7 */
    [X86_REG_XMM0] = { .reg_id = REG_VEC0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm0" } },  /* xmm0 */
    [X86_REG_XMM1] = { .reg_id = REG_VEC1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm1" } },  /* xmm1 */
    [X86_REG_XMM2] = { .reg_id = REG_VEC2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm2" } },  /* xmm2 */
    [X86_REG_XMM3] = { .reg_id = REG_VEC3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm3" } },  /* xmm3 */
    [X86_REG_XMM4] = { .reg_id = REG_VEC4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm4" } },  /* xmm4 */
    [X86_REG_XMM5] = { .reg_id = REG_VEC5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm5" } },  /* xmm5 */
    [X86_REG_XMM6] = { .reg_id = REG_VEC6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm6" } },  /* xmm6 */
    [X86_REG_XMM7] = { .reg_id = REG_VEC7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm7" } },  /* xmm7 */
    [X86_REG_XMM8] = { .reg_id = REG_VEC8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm8" } },  /* xmm8 */
    [X86_REG_XMM9] = { .reg_id = REG_VEC9, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm9" } },  /* xmm9 */
    [X86_REG_XMM10] = { .reg_id = REG_VEC10, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm10" } },  /* xmm10 */
    [X86_REG_XMM11] = { .reg_id = REG_VEC11, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm11" } },  /* xmm11 */
    [X86_REG_XMM12] = { .reg_id = REG_VEC12, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm12" } },  /* xmm12 */
    [X86_REG_XMM13] = { .reg_id = REG_VEC13, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm13" } },  /* xmm13 */
    [X86_REG_XMM14] = { .reg_id = REG_VEC14, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm14" } },  /* xmm14 */
    [X86_REG_XMM15] = { .reg_id = REG_VEC15, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm15" } },  /* xmm15 */
    [X86_REG_XMM16] = { .reg_id = REG_VEC16 },  /* xmm16 */
    [X86_REG_XMM17] = { .reg_id = REG_VEC17 },  /* xmm17 */
    [X86_REG_XMM18] = { .reg_id = REG_VEC18 },  /* xmm18 */
    [X86_REG_XMM19] = { .reg_id = REG_VEC19 },  /* xmm19 */
    [X86_REG_XMM20] = { .reg_id = REG_VEC20 },  /* xmm20 */
    [X86_REG_XMM21] = { .reg_id = REG_VEC21 },  /* xmm21 */
    [X86_REG_XMM22] = { .reg_id = REG_VEC22 },  /* xmm22 */
    [X86_REG_XMM23] = { .reg_id = REG_VEC23 },  /* xmm23 */
    [X86_REG_XMM24] = { .reg_id = REG_VEC24 },  /* xmm24 */
    [X86_REG_XMM25] = { .reg_id = REG_VEC25 },  /* xmm25 */
    [X86_REG_XMM26] = { .reg_id = REG_VEC26 },  /* xmm26 */
    [X86_REG_XMM27] = { .reg_id = REG_VEC27 },  /* xmm27 */
    [X86_REG_XMM28] = { .reg_id = REG_VEC28 },  /* xmm28 */
    [X86_REG_XMM29] = { .reg_id = REG_VEC29 },  /* xmm29 */
    [X86_REG_XMM30] = { .reg_id = REG_VEC30 },  /* xmm30 */
    [X86_REG_XMM31] = { .reg_id = REG_VEC31 },  /* xmm31 */
    [X86_REG_YMM0] = { .reg_id = REG_VEC0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm0" } },  /* ymm0 */
    [X86_REG_YMM1] = { .reg_id = REG_VEC1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm1" } },  /* ymm1 */
    [X86_REG_YMM2] = { .reg_id = REG_VEC2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm2" } },  /* ymm2 */
    [X86_REG_YMM3] = { .reg_id = REG_VEC3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm3" } },  /* ymm3 */
    [X86_REG_YMM4] = { .reg_id = REG_VEC4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm4" } },  /* ymm4 */
    [X86_REG_YMM5] = { .reg_id = REG_VEC5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm5" } },  /* ymm5 */
    [X86_REG_YMM6] = { .reg_id = REG_VEC6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm6" } },  /* ymm6 */
    [X86_REG_YMM7] = { .reg_id = REG_VEC7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm7" } },  /* ymm7 */
    [X86_REG_YMM8] = { .reg_id = REG_VEC8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm8" } },  /* ymm8 */
    [X86_REG_YMM9] = { .reg_id = REG_VEC9, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm9" } },  /* ymm9 */
    [X86_REG_YMM10] = { .reg_id = REG_VEC10, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm10" } },  /* ymm10 */
    [X86_REG_YMM11] = { .reg_id = REG_VEC11, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm11" } },  /* ymm11 */
    [X86_REG_YMM12] = { .reg_id = REG_VEC12, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm12" } },  /* ymm12 */
    [X86_REG_YMM13] = { .reg_id = REG_VEC13, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm13" } },  /* ymm13 */
    [X86_REG_YMM14] = { .reg_id = REG_VEC14, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm14" } },  /* ymm14 */
    [X86_REG_YMM15] = { .reg_id = REG_VEC15, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm15" } },  /* ymm15 */
    [X86_REG_YMM16] = { .reg_id = REG_VEC16 },  /* ymm16 */
    [X86_REG_YMM17] = { .reg_id = REG_VEC17 },  /* ymm17 */
    [X86_REG_YMM18] = { .reg_id = REG_VEC18 },  /* ymm18 */
    [X86_REG_YMM19] = { .reg_id = REG_VEC19 },  /* ymm19 */
    [X86_REG_YMM20] = { .reg_id = REG_VEC20 },  /* ymm20 */
    [X86_REG_YMM21] = { .reg_id = REG_VEC21 },  /* ymm21 */
    [X86_REG_YMM22] = { .reg_id = REG_VEC22 },  /* ymm22 */
    [X86_REG_YMM23] = { .reg_id = REG_VEC23 },  /* ymm23 */
    [X86_REG_YMM24] = { .reg_id = REG_VEC24 },  /* ymm24 */
    [X86_REG_YMM25] = { .reg_id = REG_VEC25 },  /* ymm25 */
    [X86_REG_YMM26] = { .reg_id = REG_VEC26 },  /* ymm26 */
    [X86_REG_YMM27] = { .reg_id = REG_VEC27 },  /* ymm27 */
    [X86_REG_YMM28] = { .reg_id = REG_VEC28 },  /* ymm28 */
    [X86_REG_YMM29] = { .reg_id = REG_VEC29 },  /* ymm29 */
    [X86_REG_YMM30] = { .reg_id = REG_VEC30 },  /* ymm30 */
    [X86_REG_YMM31] = { .reg_id = REG_VEC31 },  /* ymm31 */
    [X86_REG_ZMM0] = { .reg_id = REG_VEC0, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm0" } },  /* zmm0 */
    [X86_REG_ZMM1] = { .reg_id = REG_VEC1, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm1" } },  /* zmm1 */
    [X86_REG_ZMM2] = { .reg_id = REG_VEC2, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm2" } },  /* zmm2 */
    [X86_REG_ZMM3] = { .reg_id = REG_VEC3, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm3" } },  /* zmm3 */
    [X86_REG_ZMM4] = { .reg_id = REG_VEC4, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm4" } },  /* zmm4 */
    [X86_REG_ZMM5] = { .reg_id = REG_VEC5, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm5" } },  /* zmm5 */
    [X86_REG_ZMM6] = { .reg_id = REG_VEC6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm6" } },  /* zmm6 */
    [X86_REG_ZMM7] = { .reg_id = REG_VEC7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm7" } },  /* zmm7 */
    [X86_REG_ZMM8] = { .reg_id = REG_VEC8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm8" } },  /* zmm8 */
    [X86_REG_ZMM9] = { .reg_id = REG_VEC9, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm9" } },  /* zmm9 */
    [X86_REG_ZMM10] = { .reg_id = REG_VEC10, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm10" } },  /* zmm10 */
    [X86_REG_ZMM11] = { .reg_id = REG_VEC11, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm11" } },  /* zmm11 */
    [X86_REG_ZMM12] = { .reg_id = REG_VEC12, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm12" } },  /* zmm12 */
    [X86_REG_ZMM13] = { .reg_id = REG_VEC13, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm13" } },  /* zmm13 */
    [X86_REG_ZMM14] = { .reg_id = REG_VEC14, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm14" } },  /* zmm14 */
    [X86_REG_ZMM15] = { .reg_id = REG_VEC15, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "xmm15" } },  /* zmm15 */
    [X86_REG_ZMM16] = { .reg_id = REG_VEC16 },  /* zmm16 */
    [X86_REG_ZMM17] = { .reg_id = REG_VEC17 },  /* zmm17 */
    [X86_REG_ZMM18] = { .reg_id = REG_VEC18 },  /* zmm18 */
    [X86_REG_ZMM19] = { .reg_id = REG_VEC19 },  /* zmm19 */
    [X86_REG_ZMM20] = { .reg_id = REG_VEC20 },  /* zmm20 */
    [X86_REG_ZMM21] = { .reg_id = REG_VEC21 },  /* zmm21 */
    [X86_REG_ZMM22] = { .reg_id = REG_VEC22 },  /* zmm22 */
    [X86_REG_ZMM23] = { .reg_id = REG_VEC23 },  /* zmm23 */
    [X86_REG_ZMM24] = { .reg_id = REG_VEC24 },  /* zmm24 */
    [X86_REG_ZMM25] = { .reg_id = REG_VEC25 },  /* zmm25 */
    [X86_REG_ZMM26] = { .reg_id = REG_VEC26 },  /* zmm26 */
    [X86_REG_ZMM27] = { .reg_id = REG_VEC27 },  /* zmm27 */
    [X86_REG_ZMM28] = { .reg_id = REG_VEC28 },  /* zmm28 */
    [X86_REG_ZMM29] = { .reg_id = REG_VEC29 },  /* zmm29 */
    [X86_REG_ZMM30] = { .reg_id = REG_VEC30 },  /* zmm30 */
    [X86_REG_ZMM31] = { .reg_id = REG_VEC31 },  /* zmm31 */
    [X86_REG_R8B] = { .reg_id = REG_GPR6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r8" } },  /* r8b */
    [X86_REG_R9B] = { .reg_id = REG_GPR7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r9" } },  /* r9b */
    [X86_REG_R10B] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r10" } },  /* r10b */
    [X86_REG_R11B] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r11" } },  /* r11b */
    [X86_REG_R12B] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r12" } },  /* r12b */
    [X86_REG_R13B] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r13" } },  /* r13b */
    [X86_REG_R14B] = { .reg_id = REG_GPR12, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r14" } },  /* r14b */
    [X86_REG_R15B] = { .reg_id = REG_GPR13, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r15" } },  /* r15b */
    [X86_REG_R8D] = { .reg_id = REG_GPR6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r8" } },  /* r8d */
    [X86_REG_R9D] = { .reg_id = REG_GPR7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r9" } },  /* r9d */
    [X86_REG_R10D] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r10" } },  /* r10d */
    [X86_REG_R11D] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r11" } },  /* r11d */
    [X86_REG_R12D] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r12" } },  /* r12d */
    [X86_REG_R13D] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r13" } },  /* r13d */
    [X86_REG_R14D] = { .reg_id = REG_GPR12, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r14" } },  /* r14d */
    [X86_REG_R15D] = { .reg_id = REG_GPR13, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r15" } },  /* r15d */
    [X86_REG_R8W] = { .reg_id = REG_GPR6, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r8" } },  /* r8w */
    [X86_REG_R9W] = { .reg_id = REG_GPR7, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r9" } },  /* r9w */
    [X86_REG_R10W] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r10" } },  /* r10w */
    [X86_REG_R11W] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r11" } },  /* r11w */
    [X86_REG_R12W] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r12" } },  /* r12w */
    [X86_REG_R13W] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r13" } },  /* r13w */
    [X86_REG_R14W] = { .reg_id = REG_GPR12, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r14" } },  /* r14w */
    [X86_REG_R15W] = { .reg_id = REG_GPR13, .qemu_reg = { .feature = "org.gnu.gdb.i386.core", .name = "r15" } },  /* r15w */
    [X86_REG_BND0] = { .reg_id = REG_BOUND0 },  /* bnd0 */
    [X86_REG_BND1] = { .reg_id = REG_BOUND1 },  /* bnd1 */
    [X86_REG_BND2] = { .reg_id = REG_BOUND2 },  /* bnd2 */
    [X86_REG_BND3] = { .reg_id = REG_BOUND3 },  /* bnd3 */
};

/*
 * THREE EMPTY REFINERS USED TO LIVE HERE -- refine_x86_implicit_stack_store,
 * refine_x86_implicit_stack_load and refine_x86_sse_mov_access -- and they
 * were not free.  Memory counts are runtime fields derived from QEMU memory
 * callbacks rather than from opcode semantics, so the three bodies had been
 * emptied and kept only so the rows naming them stayed valid; the wire could
 * not tell them from no refiner at all, because calling a function that
 * writes nothing and not calling one are the same instruction.
 *
 * The identity tables COULD tell them apart, and that was the defect.  A row
 * carrying an empty refiner and a row carrying none compare unequal, so a
 * decode rule observed decoding both spellings -- `decode-new/MOVD_to@vex=0`
 * and `decode-new/MOVD_from@vex=0`, `movd` against `movq`, both GEN_OP_MOV --
 * was tiered QID_SPLIT, published nothing, and left the enum table as the
 * answer on the wire for every one of those instructions.
 *
 * champsim_tracer_mnemonic_audit.py now proves emptiness FROM THE BODY, per
 * name, and drops a proven-empty refiner where it would otherwise be carried
 * forward; with no row left referencing these three, the compiler's own
 * unused-function error is what removed them.  A refiner added here with a
 * real body is unaffected: the proof is one-sided and can only fail to fire.
 */
static void refine_x86_call_branch(
    const struct qemu_plugin_insn_info *info, InsnFields *f)
{
    /* X86_INS_CALL is classified BRANCH_DIRECT_CALL in the table; a
     * register/memory target makes it an indirect call. */
    if (info && info->n_operands > 0 &&
        info->operands[0].type != QEMU_PLUGIN_OP_IMM) {
        f->branch_type = BRANCH_INDIRECT_CALL;
    }
    f->branch_conditional = false;
}

static void refine_x86_jump_branch(
    const struct qemu_plugin_insn_info *info, InsnFields *f)
{
    if (info && info->n_operands > 0 &&
        info->operands[0].type != QEMU_PLUGIN_OP_IMM) {
        f->branch_type = BRANCH_INDIRECT_JUMP;
    }
    f->branch_conditional = false;
}

/*
 * `x86_insn_class[]` STOOD HERE, AND IS RETIRED (ruling R14).
 *
 * One row per Capstone instruction id, carrying the opcode,
 * branch class, flags, `.refine`, `.dep_refine` and the lane pair.
 * It was the wire's classification key until QEMU's own decode
 * identity replaced it, and after that it answered only where the
 * identity said nothing.  `enumocc.py` counted that population
 * over the whole enumerated encoding space -- four ISAs, wp0 and
 * wp16 -- and read `ENUM-OCCUPANCY total=0 key=STATED`.
 *
 * WHAT STAYS IN THIS FILE, and why it is not the table: the
 * Capstone arch/mode derivation, the register-classification
 * table, the address canonicaliser, the flags mapper and the
 * per-instance `.refine` callbacks.  The refiners in particular
 * are LIVE CODE ON THE IDENTITY KEY -- champsim_tracer_qemu_ident_
 * aarch64.h alone names refine_arm64_ldst_access on 218 rows --
 * so they retire with the operand walk, not with the table.
 */

#endif /* CHAMPSIM_TRACER_MNEMONICS_X86_H */
