#ifndef CHAMPSIM_TRACER_QEMU_REGS_X86_H
#define CHAMPSIM_TRACER_QEMU_REGS_X86_H

/*
 * QEMU-indexed register table for x86 -- auto-generated by
 * champsim_tracer_mnemonic_audit.py --qemu-regs.  Do not hand-edit a row.
 *
 * One row per register in QEMU's GDB-stub namespace -- the
 * namespace qemu_plugin_get_registers() reports -- sorted by
 * (feature, name) so a consumer can bisect.  This is the
 * authority for what generic dependency slot a register is;
 * the Capstone-keyed table is a route to these rows and is
 * cross-checked against them at install.
 *
 * .tier says whether the Capstone key can reach the row:
 *   QREG_ROUTED   at least one Capstone register id maps here
 *   QREG_UNNAMED  QEMU carries the register and Capstone's enum
 *                 has no id for it, so no Capstone-fed operand
 *                 can ever name it.  These rows are reachable
 *                 only by QEMU identity.
 *   QREG_PREDICATED  QEMU carries it only when a run-time
 *                 predicate admits it (the RISC-V CSR space,
 *                 filtered through csr_ops[].predicate).  The
 *                 row answers what generic word the NAME is;
 *                 it does not stand for its class's VALUE.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * Author: Maccoy Merrell
 */

/* x86: 66 QEMU registers, 54 reachable from
 * Capstone, 12 reachable only by QEMU identity,
 * 64 carrying a generic id. */
static const QemuRegRow qemu_regs_x86[] = {
    { .feature = "org.gnu.gdb.i386.core", .name = "cr0", .reg_id = REG_CTRL0, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "cr2", .reg_id = REG_CTRL2, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "cr3", .reg_id = REG_CTRL3, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "cr4", .reg_id = REG_CTRL4, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "cr8", .reg_id = REG_CTRL8, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "cs", .reg_id = REG_SEG0, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "ds", .reg_id = REG_SEG1, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "efer", .reg_id = REG_NONE, .cap_rows = 0, .tier = QREG_UNNAMED },
    { .feature = "org.gnu.gdb.i386.core", .name = "eflags", .reg_id = REG_FLAGS, .is_int_flags = true, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "es", .reg_id = REG_SEG2, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "fctrl", .reg_id = REG_FPCW, .cap_rows = 0, .tier = QREG_UNNAMED },  /* x87 control word (env->fpuc); OBSERVED via the declared env range -- fnstcw's store-data provenance */
    { .feature = "org.gnu.gdb.i386.core", .name = "fioff", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* x87 last-instruction offset, saved FP environment.  UNREACHABLE -- gdbstub.c returns 0; QEMU has no field */
    { .feature = "org.gnu.gdb.i386.core", .name = "fiseg", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* x87 last-instruction selector, saved FP environment.  UNREACHABLE -- gdbstub.c returns 0; QEMU has no field */
    { .feature = "org.gnu.gdb.i386.core", .name = "fooff", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* x87 last-data offset, saved FP environment.  UNREACHABLE -- gdbstub.c returns 0; QEMU has no field */
    { .feature = "org.gnu.gdb.i386.core", .name = "fop", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* x87 last-opcode, part of the saved FP environment.  UNREACHABLE -- gdbstub.c returns 0; QEMU has no field */
    { .feature = "org.gnu.gdb.i386.core", .name = "foseg", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* x87 last-data selector, saved FP environment.  UNREACHABLE -- gdbstub.c returns 0; QEMU has no field */
    { .feature = "org.gnu.gdb.i386.core", .name = "fs", .reg_id = REG_SEG3, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "fs_base", .reg_id = REG_SEG3, .cap_rows = 0, .tier = QREG_UNNAMED },  /* the FS segment register's hidden base (env->segs[R_FS].base); OBSERVED via the declared env range -- the address provenance of every FS-overridden access */
    { .feature = "org.gnu.gdb.i386.core", .name = "fstat", .reg_id = REG_FCSR, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "ftag", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* x87 tag word: status.  UNREACHABLE -- QEMU keeps the unpacked env->fptags[8] and gdbstub.c returns 0 for the packed word */
    { .feature = "org.gnu.gdb.i386.core", .name = "gs", .reg_id = REG_SEG4, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "gs_base", .reg_id = REG_SEG4, .cap_rows = 0, .tier = QREG_UNNAMED },  /* the GS segment register's hidden base (env->segs[R_GS].base); same role as fs_base above */
    { .feature = "org.gnu.gdb.i386.core", .name = "k_gs_base", .reg_id = REG_NONE, .cap_rows = 0, .tier = QREG_UNNAMED },
    { .feature = "org.gnu.gdb.i386.core", .name = "mxcsr", .reg_id = REG_FCSR, .cap_rows = 0, .tier = QREG_UNNAMED },  /* SSE control AND status in one register (env->mxcsr); generic_ids.h names it REG_FCSR explicitly */
    { .feature = "org.gnu.gdb.i386.core", .name = "r10", .reg_id = REG_GPR8, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "r11", .reg_id = REG_GPR9, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "r12", .reg_id = REG_GPR10, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "r13", .reg_id = REG_GPR11, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "r14", .reg_id = REG_GPR12, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "r15", .reg_id = REG_GPR13, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "r8", .reg_id = REG_GPR6, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "r9", .reg_id = REG_GPR7, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rax", .reg_id = REG_GPR0, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rbp", .reg_id = REG_FP_REG, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rbx", .reg_id = REG_GPR3, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rcx", .reg_id = REG_GPR1, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rdi", .reg_id = REG_GPR5, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rdx", .reg_id = REG_GPR2, .cap_rows = 5, .tier = QREG_ROUTED },  /* 5 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rip", .reg_id = REG_PC, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rsi", .reg_id = REG_GPR4, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "rsp", .reg_id = REG_SP, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "ss", .reg_id = REG_SEG5, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.i386.core", .name = "st0", .reg_id = REG_FPR0, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "st1", .reg_id = REG_FPR1, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "st2", .reg_id = REG_FPR2, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "st3", .reg_id = REG_FPR3, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "st4", .reg_id = REG_FPR4, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "st5", .reg_id = REG_FPR5, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "st6", .reg_id = REG_FPR6, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "st7", .reg_id = REG_FPR7, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm0", .reg_id = REG_VEC0, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm1", .reg_id = REG_VEC1, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm10", .reg_id = REG_VEC10, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm11", .reg_id = REG_VEC11, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm12", .reg_id = REG_VEC12, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm13", .reg_id = REG_VEC13, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm14", .reg_id = REG_VEC14, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm15", .reg_id = REG_VEC15, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm2", .reg_id = REG_VEC2, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm3", .reg_id = REG_VEC3, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm4", .reg_id = REG_VEC4, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm5", .reg_id = REG_VEC5, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm6", .reg_id = REG_VEC6, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm7", .reg_id = REG_VEC7, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm8", .reg_id = REG_VEC8, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.i386.core", .name = "xmm9", .reg_id = REG_VEC9, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
};

static const size_t qemu_regs_x86_count =
    sizeof(qemu_regs_x86) / sizeof(qemu_regs_x86[0]);

#endif /* CHAMPSIM_TRACER_QEMU_REGS_X86_H */
