#ifndef CHAMPSIM_TRACER_MNEMONICS_MIPS_H
#define CHAMPSIM_TRACER_MNEMONICS_MIPS_H

/*
 * ISA-specific classification tables for champsim_tracer — mips.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include <capstone/capstone.h>
#include <capstone/mips.h>
#include "elf.h"
#include <qemu-plugin.h>

#include "champsim_tracer_elf_attrs.h"

/*
 * Pick the Capstone MIPS arch level from EF_MIPS_ARCH bits.  If the ELF
 * cannot be loaded (e.g. statically-linked test runner that hides the
 * guest binary path), fall back to MIPS32R2 — a strict superset of
 * MIPS32R1 and the GNU toolchain default for mips/mipsel.
 *
 * Note: Capstone 6 modes are NOT strict supersets of each other (e.g.
 * MIPS32R2 does not include all MIPS32R6-only encodings), so we honour
 * the binary's declared level rather than OR'ing everything together.
 */
static unsigned int cs_mips_mode_from_eflags(uint32_t eflags, bool is64)
{
    unsigned int mode;

    switch (eflags & EF_MIPS_ARCH) {
    case EF_MIPS_ARCH_64R6:
    case EF_MIPS_ARCH_32R6:
        mode = CS_MODE_MIPS32R6;
        break;
    case EF_MIPS_ARCH_64R2:
    case EF_MIPS_ARCH_32R2:
        mode = CS_MODE_MIPS32R2;
        break;
    case EF_MIPS_ARCH_64:
        mode = CS_MODE_MIPS64;
        break;
    case EF_MIPS_ARCH_32:
        mode = CS_MODE_MIPS32;
        break;
    default:
        /* Pre-R2 / unknown: pick the widest level that still decodes
         * the older binary cleanly. */
        mode = is64 ? CS_MODE_MIPS64 : CS_MODE_MIPS32R2;
        break;
    }

    if ((eflags & EF_MIPS_ARCH_ASE) == EF_MIPS_ARCH_ASE_MICROMIPS) {
        mode |= CS_MODE_MICRO;
    }
    return mode;
}

static unsigned int cap_mode_mips(const char *target_name)
{
    /*
     * Resolve arch level from the guest binary's e_flags.  This avoids
     * the cs6 pitfall where modes are not strict supersets — using
     * e.g. MIPS32R2 against an R6-only binary mis-decodes the new R6
     * branches, and using R6 against an R1/R2 binary mis-decodes the
     * branch-likely instructions removed in R6.
     */
    unsigned int mode;
    bool is64 = (g_str_has_prefix(target_name, "mips64")
              || g_str_has_prefix(target_name, "mipsn32"));

    const char *bin = qemu_plugin_path_to_binary();
    CsElfInfo info;
    if (cs_elf_load(bin, &info)) {
        mode = cs_mips_mode_from_eflags(info.e_flags, info.is64 || is64);
        cs_elf_unload(&info);
    } else {
        /* No ELF available: MIPS32R2 covers R1+R2 binaries. */
        mode = is64 ? CS_MODE_MIPS64 : CS_MODE_MIPS32R2;
    }

    mode |= g_str_has_suffix(target_name, "el")
          ? CS_MODE_LITTLE_ENDIAN
          : CS_MODE_BIG_ENDIAN;
    return mode;
}

/*
 * MIPS address canonicalization.  MIPS defines no address tagging;
 * a stored pointer and the effective address dereferencing it share
 * one form (a MIPS32 address sign-extended into the 64-bit register
 * file, or a flat MIPS64 address).  No transform is needed —
 * identity.  The profiler's data-is-address test already masks a
 * sub-8-byte access to its captured width, which covers the MIPS32
 * pointer case.
 */
static uint64_t mips_canonicalize_addr(uint64_t a)
{
    return a;
}


/* Register classification table. */
static const RegClassification mips_reg_class[MIPS_REG_ENDING] = {
    /* Auto-generated by champsim_tracer_mnemonic_audit.py. */
    /* mips regs: 628/635 mapped, 6 intentionally ignored */
    [MIPS_REG_INVALID] = {},
    [MIPS_REG_AT] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "at" } },  /* at */
    [MIPS_REG_AT_NM] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "at" } },  /* at_nm */
    [MIPS_REG_DSPCCOND] = { .reg_id = REG_FLAGS },  /* dspccond */
    [MIPS_REG_DSPCARRY] = { .reg_id = REG_FLAGS },  /* dspcarry */
    [MIPS_REG_DSPEFI] = { .reg_id = REG_FLAGS },  /* dspefi */
    [MIPS_REG_DSPOUTFLAG] = { .reg_id = REG_FLAGS },  /* dspoutflag */
    [MIPS_REG_DSPPOS] = { .reg_id = REG_FLAGS },  /* dsppos */
    [MIPS_REG_DSPSCOUNT] = { .reg_id = REG_FLAGS },  /* dspscount */
    [MIPS_REG_FP] = { .reg_id = REG_FP_REG, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s8" } },  /* fp */
    [MIPS_REG_FP_NM] = { .reg_id = REG_FP_REG, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s8" } },  /* fp_nm */
    [MIPS_REG_GP] = { .reg_id = REG_GPR28, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "gp" } },  /* gp */
    [MIPS_REG_GP_NM] = { .reg_id = REG_GPR28, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "gp" } },  /* gp_nm */
    [MIPS_REG_MSAACCESS] = { .reg_id = REG_SYS },  /* msaaccess */
    [MIPS_REG_MSACSR] = { .reg_id = REG_FCSR },  /* msacsr */
    [MIPS_REG_MSAIR] = { .reg_id = REG_SYSID },  /* msair */
    [MIPS_REG_MSAMAP] = { .reg_id = REG_SYS },  /* msamap */
    [MIPS_REG_MSAMODIFY] = { .reg_id = REG_SYS },  /* msamodify */
    [MIPS_REG_MSAREQUEST] = { .reg_id = REG_SYS },  /* msarequest */
    [MIPS_REG_MSASAVE] = { .reg_id = REG_SYS },  /* msasave */
    [MIPS_REG_MSAUNMAP] = { .reg_id = REG_SYS },  /* msaunmap */
    [MIPS_REG_PC] = { .reg_id = REG_PC, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "pc" } },  /* pc */
    [MIPS_REG_RA] = { .reg_id = REG_LR, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "ra" } },  /* ra */
    [MIPS_REG_RA_NM] = { .reg_id = REG_LR, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "ra" } },  /* ra_nm */
    [MIPS_REG_SP] = { .reg_id = REG_SP, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "sp" } },  /* sp */
    [MIPS_REG_SP_NM] = { .reg_id = REG_SP, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "sp" } },  /* sp_nm */
    [MIPS_REG_ZERO] = { .reg_id = REG_ZERO, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "zero" } },  /* zero */
    [MIPS_REG_ZERO_NM] = { .reg_id = REG_ZERO, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "zero" } },  /* zero_nm */
    [MIPS_REG_A0] = { .reg_id = REG_GPR4, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a0" } },  /* a0 */
    [MIPS_REG_A1] = { .reg_id = REG_GPR5, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a1" } },  /* a1 */
    [MIPS_REG_A2] = { .reg_id = REG_GPR6, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a2" } },  /* a2 */
    [MIPS_REG_A3] = { .reg_id = REG_GPR7, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a3" } },  /* a3 */
    [MIPS_REG_AC0] = { .reg_id = REG_ACC0, .n_regs = 2, .regs = { REG_ACC0, REG_ACCHI0 } },  /* ac0 */
    [MIPS_REG_AC1] = { .reg_id = REG_ACC1, .n_regs = 2, .regs = { REG_ACC1, REG_ACCHI1 } },  /* ac1 */
    [MIPS_REG_AC2] = { .reg_id = REG_ACC2, .n_regs = 2, .regs = { REG_ACC2, REG_ACCHI2 } },  /* ac2 */
    [MIPS_REG_AC3] = { .reg_id = REG_ACC3, .n_regs = 2, .regs = { REG_ACC3, REG_ACCHI3 } },  /* ac3 */
    [MIPS_REG_AT_64] = { .reg_id = REG_GPR1, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "at" } },  /* at_64 */
    [MIPS_REG_COP00] = { .reg_id = REG_SYSMMU },  /* cop00 */
    [MIPS_REG_COP01] = { .reg_id = REG_SYSMMU },  /* cop01 */
    [MIPS_REG_COP02] = { .reg_id = REG_SYSMMU },  /* cop02 */
    [MIPS_REG_COP03] = { .reg_id = REG_SYSMMU },  /* cop03 */
    [MIPS_REG_COP04] = { .reg_id = REG_SYSMMU },  /* cop04 */
    [MIPS_REG_COP05] = { .reg_id = REG_SYSMMU },  /* cop05 */
    [MIPS_REG_COP06] = { .reg_id = REG_SYSMMU },  /* cop06 */
    [MIPS_REG_COP07] = { .reg_id = REG_SYS },  /* cop07 */
    [MIPS_REG_COP08] = { .reg_id = REG_SYSEXC, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "badvaddr" } },  /* cop08 */
    [MIPS_REG_COP09] = { .reg_id = REG_SYSTIMER },  /* cop09 */
    [MIPS_REG_COP20] = { .reg_id = REG_COPROC0 },  /* cop20 */
    [MIPS_REG_COP21] = { .reg_id = REG_COPROC0 },  /* cop21 */
    [MIPS_REG_COP22] = { .reg_id = REG_COPROC0 },  /* cop22 */
    [MIPS_REG_COP23] = { .reg_id = REG_COPROC0 },  /* cop23 */
    [MIPS_REG_COP24] = { .reg_id = REG_COPROC0 },  /* cop24 */
    [MIPS_REG_COP25] = { .reg_id = REG_COPROC0 },  /* cop25 */
    [MIPS_REG_COP26] = { .reg_id = REG_COPROC0 },  /* cop26 */
    [MIPS_REG_COP27] = { .reg_id = REG_COPROC0 },  /* cop27 */
    [MIPS_REG_COP28] = { .reg_id = REG_COPROC0 },  /* cop28 */
    [MIPS_REG_COP29] = { .reg_id = REG_COPROC0 },  /* cop29 */
    [MIPS_REG_COP30] = { .reg_id = REG_COPROC1 },  /* cop30 */
    [MIPS_REG_COP31] = { .reg_id = REG_COPROC1 },  /* cop31 */
    [MIPS_REG_COP32] = { .reg_id = REG_COPROC1 },  /* cop32 */
    [MIPS_REG_COP33] = { .reg_id = REG_COPROC1 },  /* cop33 */
    [MIPS_REG_COP34] = { .reg_id = REG_COPROC1 },  /* cop34 */
    [MIPS_REG_COP35] = { .reg_id = REG_COPROC1 },  /* cop35 */
    [MIPS_REG_COP36] = { .reg_id = REG_COPROC1 },  /* cop36 */
    [MIPS_REG_COP37] = { .reg_id = REG_COPROC1 },  /* cop37 */
    [MIPS_REG_COP38] = { .reg_id = REG_COPROC1 },  /* cop38 */
    [MIPS_REG_COP39] = { .reg_id = REG_COPROC1 },  /* cop39 */
    [MIPS_REG_COP010] = { .reg_id = REG_SYSMMU },  /* cop010 */
    [MIPS_REG_COP011] = { .reg_id = REG_SYSTIMER },  /* cop011 */
    [MIPS_REG_COP012] = { .reg_id = REG_SYSEXC, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "status" } },  /* cop012 */
    [MIPS_REG_COP013] = { .reg_id = REG_SYSEXC, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "cause" } },  /* cop013 */
    [MIPS_REG_COP014] = { .reg_id = REG_SYSEXC },  /* cop014 */
    [MIPS_REG_COP015] = { .reg_id = REG_SYSID },  /* cop015 */
    [MIPS_REG_COP016] = { .reg_id = REG_SYSID },  /* cop016 */
    [MIPS_REG_COP017] = { .reg_id = REG_SYS },  /* cop017 */
    [MIPS_REG_COP018] = { .reg_id = REG_SYSDBG },  /* cop018 */
    [MIPS_REG_COP019] = { .reg_id = REG_SYSDBG },  /* cop019 */
    [MIPS_REG_COP020] = { .reg_id = REG_SYSMMU },  /* cop020 */
    [MIPS_REG_COP021] = { .reg_id = REG_SYS },  /* cop021 */
    [MIPS_REG_COP022] = { .reg_id = REG_SYS },  /* cop022 */
    [MIPS_REG_COP023] = { .reg_id = REG_SYSDBG },  /* cop023 */
    [MIPS_REG_COP024] = { .reg_id = REG_SYSDBG },  /* cop024 */
    [MIPS_REG_COP025] = { .reg_id = REG_SYSPERF },  /* cop025 */
    [MIPS_REG_COP026] = { .reg_id = REG_SYSCACHE },  /* cop026 */
    [MIPS_REG_COP027] = { .reg_id = REG_SYSCACHE },  /* cop027 */
    [MIPS_REG_COP028] = { .reg_id = REG_SYSCACHE },  /* cop028 */
    [MIPS_REG_COP029] = { .reg_id = REG_SYSCACHE },  /* cop029 */
    [MIPS_REG_COP030] = { .reg_id = REG_SYSEXC },  /* cop030 */
    [MIPS_REG_COP031] = { .reg_id = REG_SYS },  /* cop031 */
    [MIPS_REG_COP210] = { .reg_id = REG_COPROC0 },  /* cop210 */
    [MIPS_REG_COP211] = { .reg_id = REG_COPROC0 },  /* cop211 */
    [MIPS_REG_COP212] = { .reg_id = REG_COPROC0 },  /* cop212 */
    [MIPS_REG_COP213] = { .reg_id = REG_COPROC0 },  /* cop213 */
    [MIPS_REG_COP214] = { .reg_id = REG_COPROC0 },  /* cop214 */
    [MIPS_REG_COP215] = { .reg_id = REG_COPROC0 },  /* cop215 */
    [MIPS_REG_COP216] = { .reg_id = REG_COPROC0 },  /* cop216 */
    [MIPS_REG_COP217] = { .reg_id = REG_COPROC0 },  /* cop217 */
    [MIPS_REG_COP218] = { .reg_id = REG_COPROC0 },  /* cop218 */
    [MIPS_REG_COP219] = { .reg_id = REG_COPROC0 },  /* cop219 */
    [MIPS_REG_COP220] = { .reg_id = REG_COPROC0 },  /* cop220 */
    [MIPS_REG_COP221] = { .reg_id = REG_COPROC0 },  /* cop221 */
    [MIPS_REG_COP222] = { .reg_id = REG_COPROC0 },  /* cop222 */
    [MIPS_REG_COP223] = { .reg_id = REG_COPROC0 },  /* cop223 */
    [MIPS_REG_COP224] = { .reg_id = REG_COPROC0 },  /* cop224 */
    [MIPS_REG_COP225] = { .reg_id = REG_COPROC0 },  /* cop225 */
    [MIPS_REG_COP226] = { .reg_id = REG_COPROC0 },  /* cop226 */
    [MIPS_REG_COP227] = { .reg_id = REG_COPROC0 },  /* cop227 */
    [MIPS_REG_COP228] = { .reg_id = REG_COPROC0 },  /* cop228 */
    [MIPS_REG_COP229] = { .reg_id = REG_COPROC0 },  /* cop229 */
    [MIPS_REG_COP230] = { .reg_id = REG_COPROC0 },  /* cop230 */
    [MIPS_REG_COP231] = { .reg_id = REG_COPROC0 },  /* cop231 */
    [MIPS_REG_COP310] = { .reg_id = REG_COPROC1 },  /* cop310 */
    [MIPS_REG_COP311] = { .reg_id = REG_COPROC1 },  /* cop311 */
    [MIPS_REG_COP312] = { .reg_id = REG_COPROC1 },  /* cop312 */
    [MIPS_REG_COP313] = { .reg_id = REG_COPROC1 },  /* cop313 */
    [MIPS_REG_COP314] = { .reg_id = REG_COPROC1 },  /* cop314 */
    [MIPS_REG_COP315] = { .reg_id = REG_COPROC1 },  /* cop315 */
    [MIPS_REG_COP316] = { .reg_id = REG_COPROC1 },  /* cop316 */
    [MIPS_REG_COP317] = { .reg_id = REG_COPROC1 },  /* cop317 */
    [MIPS_REG_COP318] = { .reg_id = REG_COPROC1 },  /* cop318 */
    [MIPS_REG_COP319] = { .reg_id = REG_COPROC1 },  /* cop319 */
    [MIPS_REG_COP320] = { .reg_id = REG_COPROC1 },  /* cop320 */
    [MIPS_REG_COP321] = { .reg_id = REG_COPROC1 },  /* cop321 */
    [MIPS_REG_COP322] = { .reg_id = REG_COPROC1 },  /* cop322 */
    [MIPS_REG_COP323] = { .reg_id = REG_COPROC1 },  /* cop323 */
    [MIPS_REG_COP324] = { .reg_id = REG_COPROC1 },  /* cop324 */
    [MIPS_REG_COP325] = { .reg_id = REG_COPROC1 },  /* cop325 */
    [MIPS_REG_COP326] = { .reg_id = REG_COPROC1 },  /* cop326 */
    [MIPS_REG_COP327] = { .reg_id = REG_COPROC1 },  /* cop327 */
    [MIPS_REG_COP328] = { .reg_id = REG_COPROC1 },  /* cop328 */
    [MIPS_REG_COP329] = { .reg_id = REG_COPROC1 },  /* cop329 */
    [MIPS_REG_COP330] = { .reg_id = REG_COPROC1 },  /* cop330 */
    [MIPS_REG_COP331] = { .reg_id = REG_COPROC1 },  /* cop331 */
    [MIPS_REG_D0] = { .reg_id = REG_FPR0, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f0" } },  /* d0 */
    [MIPS_REG_D1] = { .reg_id = REG_FPR2, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f2" } },  /* d1 */
    [MIPS_REG_D2] = { .reg_id = REG_FPR4, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f4" } },  /* d2 */
    [MIPS_REG_D3] = { .reg_id = REG_FPR6, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f6" } },  /* d3 */
    [MIPS_REG_D4] = { .reg_id = REG_FPR8, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f8" } },  /* d4 */
    [MIPS_REG_D5] = { .reg_id = REG_FPR10, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f10" } },  /* d5 */
    [MIPS_REG_D6] = { .reg_id = REG_FPR12, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f12" } },  /* d6 */
    [MIPS_REG_D7] = { .reg_id = REG_FPR14, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f14" } },  /* d7 */
    [MIPS_REG_D8] = { .reg_id = REG_FPR16, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f16" } },  /* d8 */
    [MIPS_REG_D9] = { .reg_id = REG_FPR18, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f18" } },  /* d9 */
    [MIPS_REG_D10] = { .reg_id = REG_FPR20, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f20" } },  /* d10 */
    [MIPS_REG_D11] = { .reg_id = REG_FPR22, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f22" } },  /* d11 */
    [MIPS_REG_D12] = { .reg_id = REG_FPR24, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f24" } },  /* d12 */
    [MIPS_REG_D13] = { .reg_id = REG_FPR26, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f26" } },  /* d13 */
    [MIPS_REG_D14] = { .reg_id = REG_FPR28, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f28" } },  /* d14 */
    [MIPS_REG_D15] = { .reg_id = REG_FPR30, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f30" } },  /* d15 */
    [MIPS_REG_DSPOUTFLAG20] = { .reg_id = REG_FLAGS },  /* dspoutflag20 */
    [MIPS_REG_DSPOUTFLAG21] = { .reg_id = REG_FLAGS },  /* dspoutflag21 */
    [MIPS_REG_DSPOUTFLAG22] = { .reg_id = REG_FLAGS },  /* dspoutflag22 */
    [MIPS_REG_DSPOUTFLAG23] = { .reg_id = REG_FLAGS },  /* dspoutflag23 */
    [MIPS_REG_F0] = { .reg_id = REG_FPR0, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f0" } },  /* f0 */
    [MIPS_REG_F1] = { .reg_id = REG_FPR1, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f1" } },  /* f1 */
    [MIPS_REG_F2] = { .reg_id = REG_FPR2, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f2" } },  /* f2 */
    [MIPS_REG_F3] = { .reg_id = REG_FPR3, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f3" } },  /* f3 */
    [MIPS_REG_F4] = { .reg_id = REG_FPR4, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f4" } },  /* f4 */
    [MIPS_REG_F5] = { .reg_id = REG_FPR5, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f5" } },  /* f5 */
    [MIPS_REG_F6] = { .reg_id = REG_FPR6, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f6" } },  /* f6 */
    [MIPS_REG_F7] = { .reg_id = REG_FPR7, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f7" } },  /* f7 */
    [MIPS_REG_F8] = { .reg_id = REG_FPR8, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f8" } },  /* f8 */
    [MIPS_REG_F9] = { .reg_id = REG_FPR9, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f9" } },  /* f9 */
    [MIPS_REG_F10] = { .reg_id = REG_FPR10, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f10" } },  /* f10 */
    [MIPS_REG_F11] = { .reg_id = REG_FPR11, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f11" } },  /* f11 */
    [MIPS_REG_F12] = { .reg_id = REG_FPR12, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f12" } },  /* f12 */
    [MIPS_REG_F13] = { .reg_id = REG_FPR13, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f13" } },  /* f13 */
    [MIPS_REG_F14] = { .reg_id = REG_FPR14, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f14" } },  /* f14 */
    [MIPS_REG_F15] = { .reg_id = REG_FPR15, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f15" } },  /* f15 */
    [MIPS_REG_F16] = { .reg_id = REG_FPR16, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f16" } },  /* f16 */
    [MIPS_REG_F17] = { .reg_id = REG_FPR17, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f17" } },  /* f17 */
    [MIPS_REG_F18] = { .reg_id = REG_FPR18, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f18" } },  /* f18 */
    [MIPS_REG_F19] = { .reg_id = REG_FPR19, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f19" } },  /* f19 */
    [MIPS_REG_F20] = { .reg_id = REG_FPR20, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f20" } },  /* f20 */
    [MIPS_REG_F21] = { .reg_id = REG_FPR21, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f21" } },  /* f21 */
    [MIPS_REG_F22] = { .reg_id = REG_FPR22, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f22" } },  /* f22 */
    [MIPS_REG_F23] = { .reg_id = REG_FPR23, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f23" } },  /* f23 */
    [MIPS_REG_F24] = { .reg_id = REG_FPR24, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f24" } },  /* f24 */
    [MIPS_REG_F25] = { .reg_id = REG_FPR25, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f25" } },  /* f25 */
    [MIPS_REG_F26] = { .reg_id = REG_FPR26, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f26" } },  /* f26 */
    [MIPS_REG_F27] = { .reg_id = REG_FPR27, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f27" } },  /* f27 */
    [MIPS_REG_F28] = { .reg_id = REG_FPR28, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f28" } },  /* f28 */
    [MIPS_REG_F29] = { .reg_id = REG_FPR29, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f29" } },  /* f29 */
    [MIPS_REG_F30] = { .reg_id = REG_FPR30, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f30" } },  /* f30 */
    [MIPS_REG_F31] = { .reg_id = REG_FPR31, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f31" } },  /* f31 */
    [MIPS_REG_FCC0] = { .reg_id = REG_PRED0 },  /* fcc0 */
    [MIPS_REG_FCC1] = { .reg_id = REG_PRED1 },  /* fcc1 */
    [MIPS_REG_FCC2] = { .reg_id = REG_PRED2 },  /* fcc2 */
    [MIPS_REG_FCC3] = { .reg_id = REG_PRED3 },  /* fcc3 */
    [MIPS_REG_FCC4] = { .reg_id = REG_PRED4 },  /* fcc4 */
    [MIPS_REG_FCC5] = { .reg_id = REG_PRED5 },  /* fcc5 */
    [MIPS_REG_FCC6] = { .reg_id = REG_PRED6 },  /* fcc6 */
    [MIPS_REG_FCC7] = { .reg_id = REG_PRED7 },  /* fcc7 */
    [MIPS_REG_FCR0] = { .reg_id = REG_SYSID, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "fcr0" } },  /* fcr0 */
    [MIPS_REG_FCR1] = { .reg_id = REG_FCSR },  /* fcr1 */
    [MIPS_REG_FCR2] = { .reg_id = REG_FCSR },  /* fcr2 */
    [MIPS_REG_FCR3] = { .reg_id = REG_FCSR },  /* fcr3 */
    [MIPS_REG_FCR4] = { .reg_id = REG_FCSR },  /* fcr4 */
    [MIPS_REG_FCR5] = { .reg_id = REG_FCSR },  /* fcr5 */
    [MIPS_REG_FCR6] = { .reg_id = REG_FCSR },  /* fcr6 */
    [MIPS_REG_FCR7] = { .reg_id = REG_FCSR },  /* fcr7 */
    [MIPS_REG_FCR8] = { .reg_id = REG_FCSR },  /* fcr8 */
    [MIPS_REG_FCR9] = { .reg_id = REG_FCSR },  /* fcr9 */
    [MIPS_REG_FCR10] = { .reg_id = REG_FCSR },  /* fcr10 */
    [MIPS_REG_FCR11] = { .reg_id = REG_FCSR },  /* fcr11 */
    [MIPS_REG_FCR12] = { .reg_id = REG_FCSR },  /* fcr12 */
    [MIPS_REG_FCR13] = { .reg_id = REG_FCSR },  /* fcr13 */
    [MIPS_REG_FCR14] = { .reg_id = REG_FCSR },  /* fcr14 */
    [MIPS_REG_FCR15] = { .reg_id = REG_FCSR },  /* fcr15 */
    [MIPS_REG_FCR16] = { .reg_id = REG_FCSR },  /* fcr16 */
    [MIPS_REG_FCR17] = { .reg_id = REG_FCSR },  /* fcr17 */
    [MIPS_REG_FCR18] = { .reg_id = REG_FCSR },  /* fcr18 */
    [MIPS_REG_FCR19] = { .reg_id = REG_FCSR },  /* fcr19 */
    [MIPS_REG_FCR20] = { .reg_id = REG_FCSR },  /* fcr20 */
    [MIPS_REG_FCR21] = { .reg_id = REG_FCSR },  /* fcr21 */
    [MIPS_REG_FCR22] = { .reg_id = REG_FCSR },  /* fcr22 */
    [MIPS_REG_FCR23] = { .reg_id = REG_FCSR },  /* fcr23 */
    [MIPS_REG_FCR24] = { .reg_id = REG_FCSR },  /* fcr24 */
    [MIPS_REG_FCR25] = { .reg_id = REG_FCSR },  /* fcr25 */
    [MIPS_REG_FCR26] = { .reg_id = REG_FCSR },  /* fcr26 */
    [MIPS_REG_FCR27] = { .reg_id = REG_FCSR },  /* fcr27 */
    [MIPS_REG_FCR28] = { .reg_id = REG_FCSR },  /* fcr28 */
    [MIPS_REG_FCR29] = { .reg_id = REG_FCSR },  /* fcr29 */
    [MIPS_REG_FCR30] = { .reg_id = REG_FCSR },  /* fcr30 */
    [MIPS_REG_FCR31] = { .reg_id = REG_FCSR, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "fcr31" } },  /* fcr31 */
    [MIPS_REG_FP_64] = { .reg_id = REG_FP_REG, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s8" } },  /* fp_64 */
    [MIPS_REG_F_HI0] = { .reg_id = REG_FPR0 },  /* f_hi0 */
    [MIPS_REG_F_HI1] = { .reg_id = REG_FPR1 },  /* f_hi1 */
    [MIPS_REG_F_HI2] = { .reg_id = REG_FPR2 },  /* f_hi2 */
    [MIPS_REG_F_HI3] = { .reg_id = REG_FPR3 },  /* f_hi3 */
    [MIPS_REG_F_HI4] = { .reg_id = REG_FPR4 },  /* f_hi4 */
    [MIPS_REG_F_HI5] = { .reg_id = REG_FPR5 },  /* f_hi5 */
    [MIPS_REG_F_HI6] = { .reg_id = REG_FPR6 },  /* f_hi6 */
    [MIPS_REG_F_HI7] = { .reg_id = REG_FPR7 },  /* f_hi7 */
    [MIPS_REG_F_HI8] = { .reg_id = REG_FPR8 },  /* f_hi8 */
    [MIPS_REG_F_HI9] = { .reg_id = REG_FPR9 },  /* f_hi9 */
    [MIPS_REG_F_HI10] = { .reg_id = REG_FPR10 },  /* f_hi10 */
    [MIPS_REG_F_HI11] = { .reg_id = REG_FPR11 },  /* f_hi11 */
    [MIPS_REG_F_HI12] = { .reg_id = REG_FPR12 },  /* f_hi12 */
    [MIPS_REG_F_HI13] = { .reg_id = REG_FPR13 },  /* f_hi13 */
    [MIPS_REG_F_HI14] = { .reg_id = REG_FPR14 },  /* f_hi14 */
    [MIPS_REG_F_HI15] = { .reg_id = REG_FPR15 },  /* f_hi15 */
    [MIPS_REG_F_HI16] = { .reg_id = REG_FPR16 },  /* f_hi16 */
    [MIPS_REG_F_HI17] = { .reg_id = REG_FPR17 },  /* f_hi17 */
    [MIPS_REG_F_HI18] = { .reg_id = REG_FPR18 },  /* f_hi18 */
    [MIPS_REG_F_HI19] = { .reg_id = REG_FPR19 },  /* f_hi19 */
    [MIPS_REG_F_HI20] = { .reg_id = REG_FPR20 },  /* f_hi20 */
    [MIPS_REG_F_HI21] = { .reg_id = REG_FPR21 },  /* f_hi21 */
    [MIPS_REG_F_HI22] = { .reg_id = REG_FPR22 },  /* f_hi22 */
    [MIPS_REG_F_HI23] = { .reg_id = REG_FPR23 },  /* f_hi23 */
    [MIPS_REG_F_HI24] = { .reg_id = REG_FPR24 },  /* f_hi24 */
    [MIPS_REG_F_HI25] = { .reg_id = REG_FPR25 },  /* f_hi25 */
    [MIPS_REG_F_HI26] = { .reg_id = REG_FPR26 },  /* f_hi26 */
    [MIPS_REG_F_HI27] = { .reg_id = REG_FPR27 },  /* f_hi27 */
    [MIPS_REG_F_HI28] = { .reg_id = REG_FPR28 },  /* f_hi28 */
    [MIPS_REG_F_HI29] = { .reg_id = REG_FPR29 },  /* f_hi29 */
    [MIPS_REG_F_HI30] = { .reg_id = REG_FPR30 },  /* f_hi30 */
    [MIPS_REG_F_HI31] = { .reg_id = REG_FPR31 },  /* f_hi31 */
    [MIPS_REG_GP_64] = { .reg_id = REG_GPR28, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "gp" } },  /* gp_64 */
    [MIPS_REG_HI0] = { .reg_id = REG_ACCHI0, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "hi" } },  /* hi0 */
    [MIPS_REG_HI1] = { .reg_id = REG_ACCHI1 },  /* hi1 */
    [MIPS_REG_HI2] = { .reg_id = REG_ACCHI2 },  /* hi2 */
    [MIPS_REG_HI3] = { .reg_id = REG_ACCHI3 },  /* hi3 */
    [MIPS_REG_HWR0] = { .reg_id = REG_SYSID },  /* hwr0 */
    [MIPS_REG_HWR1] = { .reg_id = REG_SYSID },  /* hwr1 */
    [MIPS_REG_HWR2] = { .reg_id = REG_SYSTIMER },  /* hwr2 */
    [MIPS_REG_HWR3] = { .reg_id = REG_SYSID },  /* hwr3 */
    [MIPS_REG_HWR4] = { .reg_id = REG_SYS },  /* hwr4 */
    [MIPS_REG_HWR5] = { .reg_id = REG_SYS },  /* hwr5 */
    [MIPS_REG_HWR6] = { .reg_id = REG_SYS },  /* hwr6 */
    [MIPS_REG_HWR7] = { .reg_id = REG_SYS },  /* hwr7 */
    [MIPS_REG_HWR8] = { .reg_id = REG_SYS },  /* hwr8 */
    [MIPS_REG_HWR9] = { .reg_id = REG_SYS },  /* hwr9 */
    [MIPS_REG_HWR10] = { .reg_id = REG_SYS },  /* hwr10 */
    [MIPS_REG_HWR11] = { .reg_id = REG_SYS },  /* hwr11 */
    [MIPS_REG_HWR12] = { .reg_id = REG_SYS },  /* hwr12 */
    [MIPS_REG_HWR13] = { .reg_id = REG_SYS },  /* hwr13 */
    [MIPS_REG_HWR14] = { .reg_id = REG_SYS },  /* hwr14 */
    [MIPS_REG_HWR15] = { .reg_id = REG_SYS },  /* hwr15 */
    [MIPS_REG_HWR16] = { .reg_id = REG_SYS },  /* hwr16 */
    [MIPS_REG_HWR17] = { .reg_id = REG_SYS },  /* hwr17 */
    [MIPS_REG_HWR18] = { .reg_id = REG_SYS },  /* hwr18 */
    [MIPS_REG_HWR19] = { .reg_id = REG_SYS },  /* hwr19 */
    [MIPS_REG_HWR20] = { .reg_id = REG_SYS },  /* hwr20 */
    [MIPS_REG_HWR21] = { .reg_id = REG_SYS },  /* hwr21 */
    [MIPS_REG_HWR22] = { .reg_id = REG_SYS },  /* hwr22 */
    [MIPS_REG_HWR23] = { .reg_id = REG_SYS },  /* hwr23 */
    [MIPS_REG_HWR24] = { .reg_id = REG_SYS },  /* hwr24 */
    [MIPS_REG_HWR25] = { .reg_id = REG_SYS },  /* hwr25 */
    [MIPS_REG_HWR26] = { .reg_id = REG_SYS },  /* hwr26 */
    [MIPS_REG_HWR27] = { .reg_id = REG_SYS },  /* hwr27 */
    [MIPS_REG_HWR28] = { .reg_id = REG_SYS },  /* hwr28 */
    [MIPS_REG_HWR29] = { .reg_id = REG_TLS },  /* hwr29 */
    [MIPS_REG_HWR30] = { .reg_id = REG_SYS },  /* hwr30 */
    [MIPS_REG_HWR31] = { .reg_id = REG_SYS },  /* hwr31 */
    [MIPS_REG_K0] = { .reg_id = REG_GPR26, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "k0" } },  /* k0 */
    [MIPS_REG_K1] = { .reg_id = REG_GPR27, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "k1" } },  /* k1 */
    [MIPS_REG_LO0] = { .reg_id = REG_ACC0, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "lo" } },  /* lo0 */
    [MIPS_REG_LO1] = { .reg_id = REG_ACC1 },  /* lo1 */
    [MIPS_REG_LO2] = { .reg_id = REG_ACC2 },  /* lo2 */
    [MIPS_REG_LO3] = { .reg_id = REG_ACC3 },  /* lo3 */
    [MIPS_REG_MPL0] = {},
    [MIPS_REG_MPL1] = {},
    [MIPS_REG_MPL2] = {},
    [MIPS_REG_MSA8] = { .reg_id = REG_SYS },  /* msa8 */
    [MIPS_REG_MSA9] = { .reg_id = REG_SYS },  /* msa9 */
    [MIPS_REG_MSA10] = { .reg_id = REG_SYS },  /* msa10 */
    [MIPS_REG_MSA11] = { .reg_id = REG_SYS },  /* msa11 */
    [MIPS_REG_MSA12] = { .reg_id = REG_SYS },  /* msa12 */
    [MIPS_REG_MSA13] = { .reg_id = REG_SYS },  /* msa13 */
    [MIPS_REG_MSA14] = { .reg_id = REG_SYS },  /* msa14 */
    [MIPS_REG_MSA15] = { .reg_id = REG_SYS },  /* msa15 */
    [MIPS_REG_MSA16] = { .reg_id = REG_SYS },  /* msa16 */
    [MIPS_REG_MSA17] = { .reg_id = REG_SYS },  /* msa17 */
    [MIPS_REG_MSA18] = { .reg_id = REG_SYS },  /* msa18 */
    [MIPS_REG_MSA19] = { .reg_id = REG_SYS },  /* msa19 */
    [MIPS_REG_MSA20] = { .reg_id = REG_SYS },  /* msa20 */
    [MIPS_REG_MSA21] = { .reg_id = REG_SYS },  /* msa21 */
    [MIPS_REG_MSA22] = { .reg_id = REG_SYS },  /* msa22 */
    [MIPS_REG_MSA23] = { .reg_id = REG_SYS },  /* msa23 */
    [MIPS_REG_MSA24] = { .reg_id = REG_SYS },  /* msa24 */
    [MIPS_REG_MSA25] = { .reg_id = REG_SYS },  /* msa25 */
    [MIPS_REG_MSA26] = { .reg_id = REG_SYS },  /* msa26 */
    [MIPS_REG_MSA27] = { .reg_id = REG_SYS },  /* msa27 */
    [MIPS_REG_MSA28] = { .reg_id = REG_SYS },  /* msa28 */
    [MIPS_REG_MSA29] = { .reg_id = REG_SYS },  /* msa29 */
    [MIPS_REG_MSA30] = { .reg_id = REG_SYS },  /* msa30 */
    [MIPS_REG_MSA31] = { .reg_id = REG_SYS },  /* msa31 */
    [MIPS_REG_P0] = {},
    [MIPS_REG_P1] = {},
    [MIPS_REG_P2] = {},
    [MIPS_REG_RA_64] = { .reg_id = REG_LR, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "ra" } },  /* ra_64 */
    [MIPS_REG_S0] = { .reg_id = REG_GPR16, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s0" } },  /* s0 */
    [MIPS_REG_S1] = { .reg_id = REG_GPR17, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s1" } },  /* s1 */
    [MIPS_REG_S2] = { .reg_id = REG_GPR18, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s2" } },  /* s2 */
    [MIPS_REG_S3] = { .reg_id = REG_GPR19, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s3" } },  /* s3 */
    [MIPS_REG_S4] = { .reg_id = REG_GPR20, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s4" } },  /* s4 */
    [MIPS_REG_S5] = { .reg_id = REG_GPR21, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s5" } },  /* s5 */
    [MIPS_REG_S6] = { .reg_id = REG_GPR22, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s6" } },  /* s6 */
    [MIPS_REG_S7] = { .reg_id = REG_GPR23, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s7" } },  /* s7 */
    [MIPS_REG_SP_64] = { .reg_id = REG_SP, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "sp" } },  /* sp_64 */
    [MIPS_REG_T0] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t0" } },  /* t0 */
    [MIPS_REG_T1] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t1" } },  /* t1 */
    [MIPS_REG_T2] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t2" } },  /* t2 */
    [MIPS_REG_T3] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t3" } },  /* t3 */
    [MIPS_REG_T4] = { .reg_id = REG_GPR12, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t4" } },  /* t4 */
    [MIPS_REG_T5] = { .reg_id = REG_GPR13, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t5" } },  /* t5 */
    [MIPS_REG_T6] = { .reg_id = REG_GPR14, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t6" } },  /* t6 */
    [MIPS_REG_T7] = { .reg_id = REG_GPR15, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t7" } },  /* t7 */
    [MIPS_REG_T8] = { .reg_id = REG_GPR24, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t8" } },  /* t8 */
    [MIPS_REG_T9] = { .reg_id = REG_GPR25, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t9" } },  /* t9 */
    [MIPS_REG_V0] = { .reg_id = REG_GPR2, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "v0" } },  /* v0 */
    [MIPS_REG_V1] = { .reg_id = REG_GPR3, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "v1" } },  /* v1 */
    [MIPS_REG_W0] = { .reg_id = REG_VEC0 },  /* w0 */
    [MIPS_REG_W1] = { .reg_id = REG_VEC1 },  /* w1 */
    [MIPS_REG_W2] = { .reg_id = REG_VEC2 },  /* w2 */
    [MIPS_REG_W3] = { .reg_id = REG_VEC3 },  /* w3 */
    [MIPS_REG_W4] = { .reg_id = REG_VEC4 },  /* w4 */
    [MIPS_REG_W5] = { .reg_id = REG_VEC5 },  /* w5 */
    [MIPS_REG_W6] = { .reg_id = REG_VEC6 },  /* w6 */
    [MIPS_REG_W7] = { .reg_id = REG_VEC7 },  /* w7 */
    [MIPS_REG_W8] = { .reg_id = REG_VEC8 },  /* w8 */
    [MIPS_REG_W9] = { .reg_id = REG_VEC9 },  /* w9 */
    [MIPS_REG_W10] = { .reg_id = REG_VEC10 },  /* w10 */
    [MIPS_REG_W11] = { .reg_id = REG_VEC11 },  /* w11 */
    [MIPS_REG_W12] = { .reg_id = REG_VEC12 },  /* w12 */
    [MIPS_REG_W13] = { .reg_id = REG_VEC13 },  /* w13 */
    [MIPS_REG_W14] = { .reg_id = REG_VEC14 },  /* w14 */
    [MIPS_REG_W15] = { .reg_id = REG_VEC15 },  /* w15 */
    [MIPS_REG_W16] = { .reg_id = REG_VEC16 },  /* w16 */
    [MIPS_REG_W17] = { .reg_id = REG_VEC17 },  /* w17 */
    [MIPS_REG_W18] = { .reg_id = REG_VEC18 },  /* w18 */
    [MIPS_REG_W19] = { .reg_id = REG_VEC19 },  /* w19 */
    [MIPS_REG_W20] = { .reg_id = REG_VEC20 },  /* w20 */
    [MIPS_REG_W21] = { .reg_id = REG_VEC21 },  /* w21 */
    [MIPS_REG_W22] = { .reg_id = REG_VEC22 },  /* w22 */
    [MIPS_REG_W23] = { .reg_id = REG_VEC23 },  /* w23 */
    [MIPS_REG_W24] = { .reg_id = REG_VEC24 },  /* w24 */
    [MIPS_REG_W25] = { .reg_id = REG_VEC25 },  /* w25 */
    [MIPS_REG_W26] = { .reg_id = REG_VEC26 },  /* w26 */
    [MIPS_REG_W27] = { .reg_id = REG_VEC27 },  /* w27 */
    [MIPS_REG_W28] = { .reg_id = REG_VEC28 },  /* w28 */
    [MIPS_REG_W29] = { .reg_id = REG_VEC29 },  /* w29 */
    [MIPS_REG_W30] = { .reg_id = REG_VEC30 },  /* w30 */
    [MIPS_REG_W31] = { .reg_id = REG_VEC31 },  /* w31 */
    [MIPS_REG_ZERO_64] = { .reg_id = REG_ZERO, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "zero" } },  /* zero_64 */
    [MIPS_REG_A0_NM] = { .reg_id = REG_GPR4, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a0" } },  /* a0_nm */
    [MIPS_REG_A1_NM] = { .reg_id = REG_GPR5, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a1" } },  /* a1_nm */
    [MIPS_REG_A2_NM] = { .reg_id = REG_GPR6, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a2" } },  /* a2_nm */
    [MIPS_REG_A3_NM] = { .reg_id = REG_GPR7, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a3" } },  /* a3_nm */
    [MIPS_REG_A4_NM] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t0" } },  /* a4_nm */
    [MIPS_REG_A5_NM] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t1" } },  /* a5_nm */
    [MIPS_REG_A6_NM] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t2" } },  /* a6_nm */
    [MIPS_REG_A7_NM] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t3" } },  /* a7_nm */
    [MIPS_REG_COP0SEL_BADINST] = { .reg_id = REG_SYSEXC },  /* cop0sel_badinst */
    [MIPS_REG_COP0SEL_BADINSTRP] = { .reg_id = REG_SYSEXC },  /* cop0sel_badinstrp */
    [MIPS_REG_COP0SEL_BADINSTRX] = { .reg_id = REG_SYSEXC },  /* cop0sel_badinstrx */
    [MIPS_REG_COP0SEL_BADVADDR] = { .reg_id = REG_SYSEXC, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "badvaddr" } },  /* cop0sel_badvaddr */
    [MIPS_REG_COP0SEL_BEVVA] = { .reg_id = REG_SYSEXC },  /* cop0sel_bevva */
    [MIPS_REG_COP0SEL_CACHEERR] = { .reg_id = REG_SYSCACHE },  /* cop0sel_cacheerr */
    [MIPS_REG_COP0SEL_CAUSE] = { .reg_id = REG_SYSEXC, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "cause" } },  /* cop0sel_cause */
    [MIPS_REG_COP0SEL_CDMMBASE] = { .reg_id = REG_SYSID },  /* cop0sel_cdmmbase */
    [MIPS_REG_COP0SEL_CMGCRBASE] = { .reg_id = REG_SYSID },  /* cop0sel_cmgcrbase */
    [MIPS_REG_COP0SEL_COMPARE] = { .reg_id = REG_SYSTIMER },  /* cop0sel_compare */
    [MIPS_REG_COP0SEL_CONFIG] = { .reg_id = REG_SYSID },  /* cop0sel_config */
    [MIPS_REG_COP0SEL_CONTEXT] = { .reg_id = REG_SYSMMU },  /* cop0sel_context */
    [MIPS_REG_COP0SEL_CONTEXTCONFIG] = { .reg_id = REG_SYSMMU },  /* cop0sel_contextconfig */
    [MIPS_REG_COP0SEL_COUNT] = { .reg_id = REG_SYSTIMER },  /* cop0sel_count */
    [MIPS_REG_COP0SEL_DDATAHI] = { .reg_id = REG_SYSCACHE },  /* cop0sel_ddatahi */
    [MIPS_REG_COP0SEL_DDATALO] = { .reg_id = REG_SYSCACHE },  /* cop0sel_ddatalo */
    [MIPS_REG_COP0SEL_DEBUG] = { .reg_id = REG_SYSDBG },  /* cop0sel_debug */
    [MIPS_REG_COP0SEL_DEBUGCONTEXTID] = { .reg_id = REG_SYSDBG },  /* cop0sel_debugcontextid */
    [MIPS_REG_COP0SEL_DEPC] = { .reg_id = REG_SYS },  /* cop0sel_depc */
    [MIPS_REG_COP0SEL_DESAVE] = { .reg_id = REG_SYS },  /* cop0sel_desave */
    [MIPS_REG_COP0SEL_DTAGHI] = { .reg_id = REG_SYSCACHE },  /* cop0sel_dtaghi */
    [MIPS_REG_COP0SEL_DTAGLO] = { .reg_id = REG_SYSCACHE },  /* cop0sel_dtaglo */
    [MIPS_REG_COP0SEL_EBASE] = { .reg_id = REG_SYSEXC },  /* cop0sel_ebase */
    [MIPS_REG_COP0SEL_ENTRYHI] = { .reg_id = REG_SYSMMU },  /* cop0sel_entryhi */
    [MIPS_REG_COP0SEL_EPC] = { .reg_id = REG_SYSEXC },  /* cop0sel_epc */
    [MIPS_REG_COP0SEL_ERRCTL] = { .reg_id = REG_SYSCACHE },  /* cop0sel_errctl */
    [MIPS_REG_COP0SEL_ERROREPC] = { .reg_id = REG_SYSEXC },  /* cop0sel_errorepc */
    [MIPS_REG_COP0SEL_GLOBALNUMBER] = { .reg_id = REG_SYSID },  /* cop0sel_globalnumber */
    [MIPS_REG_COP0SEL_GTOFFSET] = { .reg_id = REG_SYS },  /* cop0sel_gtoffset */
    [MIPS_REG_COP0SEL_HWRENA] = { .reg_id = REG_SYS },  /* cop0sel_hwrena */
    [MIPS_REG_COP0SEL_IDATAHI] = { .reg_id = REG_SYSCACHE },  /* cop0sel_idatahi */
    [MIPS_REG_COP0SEL_IDATALO] = { .reg_id = REG_SYSCACHE },  /* cop0sel_idatalo */
    [MIPS_REG_COP0SEL_INDEX] = { .reg_id = REG_SYSMMU },  /* cop0sel_index */
    [MIPS_REG_COP0SEL_INTCTL] = { .reg_id = REG_SYSEXC },  /* cop0sel_intctl */
    [MIPS_REG_COP0SEL_ITAGHI] = { .reg_id = REG_SYSCACHE },  /* cop0sel_itaghi */
    [MIPS_REG_COP0SEL_ITAGLO] = { .reg_id = REG_SYSCACHE },  /* cop0sel_itaglo */
    [MIPS_REG_COP0SEL_LLADDR] = { .reg_id = REG_SYS },  /* cop0sel_lladdr */
    [MIPS_REG_COP0SEL_MAAR] = { .reg_id = REG_SYSMMU },  /* cop0sel_maar */
    [MIPS_REG_COP0SEL_MAARI] = { .reg_id = REG_SYSMMU },  /* cop0sel_maari */
    [MIPS_REG_COP0SEL_MEMORYMAPID] = { .reg_id = REG_SYSMMU },  /* cop0sel_memorymapid */
    [MIPS_REG_COP0SEL_MVPCONTROL] = { .reg_id = REG_SYS },  /* cop0sel_mvpcontrol */
    [MIPS_REG_COP0SEL_NESTEDEPC] = { .reg_id = REG_SYSEXC },  /* cop0sel_nestedepc */
    [MIPS_REG_COP0SEL_NESTEDEXC] = { .reg_id = REG_SYSEXC },  /* cop0sel_nestedexc */
    [MIPS_REG_COP0SEL_PAGEGRAIN] = { .reg_id = REG_SYSMMU },  /* cop0sel_pagegrain */
    [MIPS_REG_COP0SEL_PAGEMASK] = { .reg_id = REG_SYSMMU },  /* cop0sel_pagemask */
    [MIPS_REG_COP0SEL_PRID] = { .reg_id = REG_SYSID },  /* cop0sel_prid */
    [MIPS_REG_COP0SEL_PWBASE] = { .reg_id = REG_SYSMMU },  /* cop0sel_pwbase */
    [MIPS_REG_COP0SEL_PWCTL] = { .reg_id = REG_SYSMMU },  /* cop0sel_pwctl */
    [MIPS_REG_COP0SEL_PWFIELD] = { .reg_id = REG_SYSMMU },  /* cop0sel_pwfield */
    [MIPS_REG_COP0SEL_PWSIZE] = { .reg_id = REG_SYSMMU },  /* cop0sel_pwsize */
    [MIPS_REG_COP0SEL_RANDOM] = { .reg_id = REG_SYSMMU },  /* cop0sel_random */
    [MIPS_REG_COP0SEL_SRSCTL] = { .reg_id = REG_SYSEXC },  /* cop0sel_srsctl */
    [MIPS_REG_COP0SEL_SRSMAP] = { .reg_id = REG_SYSEXC },  /* cop0sel_srsmap */
    [MIPS_REG_COP0SEL_STATUS] = { .reg_id = REG_SYSEXC, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "status" } },  /* cop0sel_status */
    [MIPS_REG_COP0SEL_TCBIND] = { .reg_id = REG_SYS },  /* cop0sel_tcbind */
    [MIPS_REG_COP0SEL_TCCONTEXT] = { .reg_id = REG_SYS },  /* cop0sel_tccontext */
    [MIPS_REG_COP0SEL_TCHALT] = { .reg_id = REG_SYS },  /* cop0sel_tchalt */
    [MIPS_REG_COP0SEL_TCOPT] = { .reg_id = REG_SYS },  /* cop0sel_tcopt */
    [MIPS_REG_COP0SEL_TCRESTART] = { .reg_id = REG_SYS },  /* cop0sel_tcrestart */
    [MIPS_REG_COP0SEL_TCSCHEDULE] = { .reg_id = REG_SYS },  /* cop0sel_tcschedule */
    [MIPS_REG_COP0SEL_TCSCHEFBACK] = { .reg_id = REG_SYS },  /* cop0sel_tcschefback */
    [MIPS_REG_COP0SEL_TCSTATUS] = { .reg_id = REG_SYS },  /* cop0sel_tcstatus */
    [MIPS_REG_COP0SEL_TRACECONTROL] = { .reg_id = REG_SYSDBG },  /* cop0sel_tracecontrol */
    [MIPS_REG_COP0SEL_TRACEDBPC] = { .reg_id = REG_SYSDBG },  /* cop0sel_tracedbpc */
    [MIPS_REG_COP0SEL_TRACEIBPC] = { .reg_id = REG_SYSDBG },  /* cop0sel_traceibpc */
    [MIPS_REG_COP0SEL_USERLOCAL] = { .reg_id = REG_TLS },  /* cop0sel_userlocal */
    [MIPS_REG_COP0SEL_VIEW_IPL] = { .reg_id = REG_SYSEXC },  /* cop0sel_view_ipl */
    [MIPS_REG_COP0SEL_VIEW_RIPL] = { .reg_id = REG_SYSEXC },  /* cop0sel_view_ripl */
    [MIPS_REG_COP0SEL_VPCONTROL] = { .reg_id = REG_SYS },  /* cop0sel_vpcontrol */
    [MIPS_REG_COP0SEL_VPECONTROL] = { .reg_id = REG_SYS },  /* cop0sel_vpecontrol */
    [MIPS_REG_COP0SEL_VPEOPT] = { .reg_id = REG_SYS },  /* cop0sel_vpeopt */
    [MIPS_REG_COP0SEL_VPESCHEDULE] = { .reg_id = REG_SYS },  /* cop0sel_vpeschedule */
    [MIPS_REG_COP0SEL_VPESCHEFBACK] = { .reg_id = REG_SYS },  /* cop0sel_vpeschefback */
    [MIPS_REG_COP0SEL_WIRED] = { .reg_id = REG_SYSMMU },  /* cop0sel_wired */
    [MIPS_REG_COP0SEL_XCONTEXT] = { .reg_id = REG_SYSMMU },  /* cop0sel_xcontext */
    [MIPS_REG_COP0SEL_XCONTEXTCONFIG] = { .reg_id = REG_SYSMMU },  /* cop0sel_xcontextconfig */
    [MIPS_REG_COP0SEL_YQMASK] = { .reg_id = REG_SYS },  /* cop0sel_yqmask */
    [MIPS_REG_K0_NM] = { .reg_id = REG_GPR26, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "k0" } },  /* k0_nm */
    [MIPS_REG_K1_NM] = { .reg_id = REG_GPR27, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "k1" } },  /* k1_nm */
    [MIPS_REG_S0_NM] = { .reg_id = REG_GPR16, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s0" } },  /* s0_nm */
    [MIPS_REG_S1_NM] = { .reg_id = REG_GPR17, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s1" } },  /* s1_nm */
    [MIPS_REG_S2_NM] = { .reg_id = REG_GPR18, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s2" } },  /* s2_nm */
    [MIPS_REG_S3_NM] = { .reg_id = REG_GPR19, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s3" } },  /* s3_nm */
    [MIPS_REG_S4_NM] = { .reg_id = REG_GPR20, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s4" } },  /* s4_nm */
    [MIPS_REG_S5_NM] = { .reg_id = REG_GPR21, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s5" } },  /* s5_nm */
    [MIPS_REG_S6_NM] = { .reg_id = REG_GPR22, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s6" } },  /* s6_nm */
    [MIPS_REG_S7_NM] = { .reg_id = REG_GPR23, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s7" } },  /* s7_nm */
    [MIPS_REG_T0_NM] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t0" } },  /* t0_nm */
    [MIPS_REG_T1_NM] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t1" } },  /* t1_nm */
    [MIPS_REG_T2_NM] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t2" } },  /* t2_nm */
    [MIPS_REG_T3_NM] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t3" } },  /* t3_nm */
    [MIPS_REG_T4_NM] = { .reg_id = REG_GPR12, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t4" } },  /* t4_nm */
    [MIPS_REG_T5_NM] = { .reg_id = REG_GPR13, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t5" } },  /* t5_nm */
    [MIPS_REG_T8_NM] = { .reg_id = REG_GPR24, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t8" } },  /* t8_nm */
    [MIPS_REG_T9_NM] = { .reg_id = REG_GPR25, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t9" } },  /* t9_nm */
    [MIPS_REG_A0_64] = { .reg_id = REG_GPR4, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a0" } },  /* a0_64 */
    [MIPS_REG_A1_64] = { .reg_id = REG_GPR5, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a1" } },  /* a1_64 */
    [MIPS_REG_A2_64] = { .reg_id = REG_GPR6, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a2" } },  /* a2_64 */
    [MIPS_REG_A3_64] = { .reg_id = REG_GPR7, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "a3" } },  /* a3_64 */
    [MIPS_REG_AC0_64] = { .reg_id = REG_ACC0, .n_regs = 2, .regs = { REG_ACC0, REG_ACCHI0 } },  /* ac0_64 */
    [MIPS_REG_COP0SEL_CONFIG1] = { .reg_id = REG_SYSID },  /* cop0sel_config1 */
    [MIPS_REG_COP0SEL_CONFIG2] = { .reg_id = REG_SYSID },  /* cop0sel_config2 */
    [MIPS_REG_COP0SEL_CONFIG3] = { .reg_id = REG_SYSID },  /* cop0sel_config3 */
    [MIPS_REG_COP0SEL_CONFIG4] = { .reg_id = REG_SYSID },  /* cop0sel_config4 */
    [MIPS_REG_COP0SEL_CONFIG5] = { .reg_id = REG_SYSID },  /* cop0sel_config5 */
    [MIPS_REG_COP0SEL_DEBUG2] = { .reg_id = REG_SYSDBG },  /* cop0sel_debug2 */
    [MIPS_REG_COP0SEL_ENTRYLO0] = { .reg_id = REG_SYSMMU },  /* cop0sel_entrylo0 */
    [MIPS_REG_COP0SEL_ENTRYLO1] = { .reg_id = REG_SYSMMU },  /* cop0sel_entrylo1 */
    [MIPS_REG_COP0SEL_GUESTCTL0] = { .reg_id = REG_SYS },  /* cop0sel_guestctl0 */
    [MIPS_REG_COP0SEL_GUESTCTL1] = { .reg_id = REG_SYS },  /* cop0sel_guestctl1 */
    [MIPS_REG_COP0SEL_GUESTCTL2] = { .reg_id = REG_SYS },  /* cop0sel_guestctl2 */
    [MIPS_REG_COP0SEL_GUESTCTL3] = { .reg_id = REG_SYS },  /* cop0sel_guestctl3 */
    [MIPS_REG_COP0SEL_KSCRATCH1] = { .reg_id = REG_SYS },  /* cop0sel_kscratch1 */
    [MIPS_REG_COP0SEL_KSCRATCH2] = { .reg_id = REG_SYS },  /* cop0sel_kscratch2 */
    [MIPS_REG_COP0SEL_KSCRATCH3] = { .reg_id = REG_SYS },  /* cop0sel_kscratch3 */
    [MIPS_REG_COP0SEL_KSCRATCH4] = { .reg_id = REG_SYS },  /* cop0sel_kscratch4 */
    [MIPS_REG_COP0SEL_KSCRATCH5] = { .reg_id = REG_SYS },  /* cop0sel_kscratch5 */
    [MIPS_REG_COP0SEL_KSCRATCH6] = { .reg_id = REG_SYS },  /* cop0sel_kscratch6 */
    [MIPS_REG_COP0SEL_MVPCONF0] = { .reg_id = REG_SYSID },  /* cop0sel_mvpconf0 */
    [MIPS_REG_COP0SEL_MVPCONF1] = { .reg_id = REG_SYSID },  /* cop0sel_mvpconf1 */
    [MIPS_REG_COP0SEL_PERFCNT0] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt0 */
    [MIPS_REG_COP0SEL_PERFCNT1] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt1 */
    [MIPS_REG_COP0SEL_PERFCNT2] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt2 */
    [MIPS_REG_COP0SEL_PERFCNT3] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt3 */
    [MIPS_REG_COP0SEL_PERFCNT4] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt4 */
    [MIPS_REG_COP0SEL_PERFCNT5] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt5 */
    [MIPS_REG_COP0SEL_PERFCNT6] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt6 */
    [MIPS_REG_COP0SEL_PERFCNT7] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfcnt7 */
    [MIPS_REG_COP0SEL_PERFCTL0] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl0 */
    [MIPS_REG_COP0SEL_PERFCTL1] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl1 */
    [MIPS_REG_COP0SEL_PERFCTL2] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl2 */
    [MIPS_REG_COP0SEL_PERFCTL3] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl3 */
    [MIPS_REG_COP0SEL_PERFCTL4] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl4 */
    [MIPS_REG_COP0SEL_PERFCTL5] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl5 */
    [MIPS_REG_COP0SEL_PERFCTL6] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl6 */
    [MIPS_REG_COP0SEL_PERFCTL7] = { .reg_id = REG_SYSPERF },  /* cop0sel_perfctl7 */
    [MIPS_REG_COP0SEL_SEGCTL0] = { .reg_id = REG_SYSMMU },  /* cop0sel_segctl0 */
    [MIPS_REG_COP0SEL_SEGCTL1] = { .reg_id = REG_SYSMMU },  /* cop0sel_segctl1 */
    [MIPS_REG_COP0SEL_SEGCTL2] = { .reg_id = REG_SYSMMU },  /* cop0sel_segctl2 */
    [MIPS_REG_COP0SEL_SRSCONF0] = { .reg_id = REG_SYSID },  /* cop0sel_srsconf0 */
    [MIPS_REG_COP0SEL_SRSCONF1] = { .reg_id = REG_SYSID },  /* cop0sel_srsconf1 */
    [MIPS_REG_COP0SEL_SRSCONF2] = { .reg_id = REG_SYSID },  /* cop0sel_srsconf2 */
    [MIPS_REG_COP0SEL_SRSCONF3] = { .reg_id = REG_SYSID },  /* cop0sel_srsconf3 */
    [MIPS_REG_COP0SEL_SRSCONF4] = { .reg_id = REG_SYSID },  /* cop0sel_srsconf4 */
    [MIPS_REG_COP0SEL_SRSMAP2] = { .reg_id = REG_SYSEXC },  /* cop0sel_srsmap2 */
    [MIPS_REG_COP0SEL_TRACECONTROL2] = { .reg_id = REG_SYSDBG },  /* cop0sel_tracecontrol2 */
    [MIPS_REG_COP0SEL_TRACECONTROL3] = { .reg_id = REG_SYSDBG },  /* cop0sel_tracecontrol3 */
    [MIPS_REG_COP0SEL_USERTRACEDATA1] = { .reg_id = REG_SYSDBG },  /* cop0sel_usertracedata1 */
    [MIPS_REG_COP0SEL_USERTRACEDATA2] = { .reg_id = REG_SYSDBG },  /* cop0sel_usertracedata2 */
    [MIPS_REG_COP0SEL_VPECONF0] = { .reg_id = REG_SYS },  /* cop0sel_vpeconf0 */
    [MIPS_REG_COP0SEL_VPECONF1] = { .reg_id = REG_SYS },  /* cop0sel_vpeconf1 */
    [MIPS_REG_COP0SEL_WATCHHI0] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi0 */
    [MIPS_REG_COP0SEL_WATCHHI1] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi1 */
    [MIPS_REG_COP0SEL_WATCHHI2] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi2 */
    [MIPS_REG_COP0SEL_WATCHHI3] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi3 */
    [MIPS_REG_COP0SEL_WATCHHI4] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi4 */
    [MIPS_REG_COP0SEL_WATCHHI5] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi5 */
    [MIPS_REG_COP0SEL_WATCHHI6] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi6 */
    [MIPS_REG_COP0SEL_WATCHHI7] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi7 */
    [MIPS_REG_COP0SEL_WATCHHI8] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi8 */
    [MIPS_REG_COP0SEL_WATCHHI9] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi9 */
    [MIPS_REG_COP0SEL_WATCHHI10] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi10 */
    [MIPS_REG_COP0SEL_WATCHHI11] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi11 */
    [MIPS_REG_COP0SEL_WATCHHI12] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi12 */
    [MIPS_REG_COP0SEL_WATCHHI13] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi13 */
    [MIPS_REG_COP0SEL_WATCHHI14] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi14 */
    [MIPS_REG_COP0SEL_WATCHHI15] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchhi15 */
    [MIPS_REG_COP0SEL_WATCHLO0] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo0 */
    [MIPS_REG_COP0SEL_WATCHLO1] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo1 */
    [MIPS_REG_COP0SEL_WATCHLO2] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo2 */
    [MIPS_REG_COP0SEL_WATCHLO3] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo3 */
    [MIPS_REG_COP0SEL_WATCHLO4] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo4 */
    [MIPS_REG_COP0SEL_WATCHLO5] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo5 */
    [MIPS_REG_COP0SEL_WATCHLO6] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo6 */
    [MIPS_REG_COP0SEL_WATCHLO7] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo7 */
    [MIPS_REG_COP0SEL_WATCHLO8] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo8 */
    [MIPS_REG_COP0SEL_WATCHLO9] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo9 */
    [MIPS_REG_COP0SEL_WATCHLO10] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo10 */
    [MIPS_REG_COP0SEL_WATCHLO11] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo11 */
    [MIPS_REG_COP0SEL_WATCHLO12] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo12 */
    [MIPS_REG_COP0SEL_WATCHLO13] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo13 */
    [MIPS_REG_COP0SEL_WATCHLO14] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo14 */
    [MIPS_REG_COP0SEL_WATCHLO15] = { .reg_id = REG_SYSDBG },  /* cop0sel_watchlo15 */
    [MIPS_REG_D0_64] = { .reg_id = REG_FPR0, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f0" } },  /* d0_64 */
    [MIPS_REG_D1_64] = { .reg_id = REG_FPR1, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f1" } },  /* d1_64 */
    [MIPS_REG_D2_64] = { .reg_id = REG_FPR2, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f2" } },  /* d2_64 */
    [MIPS_REG_D3_64] = { .reg_id = REG_FPR3, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f3" } },  /* d3_64 */
    [MIPS_REG_D4_64] = { .reg_id = REG_FPR4, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f4" } },  /* d4_64 */
    [MIPS_REG_D5_64] = { .reg_id = REG_FPR5, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f5" } },  /* d5_64 */
    [MIPS_REG_D6_64] = { .reg_id = REG_FPR6, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f6" } },  /* d6_64 */
    [MIPS_REG_D7_64] = { .reg_id = REG_FPR7, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f7" } },  /* d7_64 */
    [MIPS_REG_D8_64] = { .reg_id = REG_FPR8, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f8" } },  /* d8_64 */
    [MIPS_REG_D9_64] = { .reg_id = REG_FPR9, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f9" } },  /* d9_64 */
    [MIPS_REG_D10_64] = { .reg_id = REG_FPR10, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f10" } },  /* d10_64 */
    [MIPS_REG_D11_64] = { .reg_id = REG_FPR11, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f11" } },  /* d11_64 */
    [MIPS_REG_D12_64] = { .reg_id = REG_FPR12, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f12" } },  /* d12_64 */
    [MIPS_REG_D13_64] = { .reg_id = REG_FPR13, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f13" } },  /* d13_64 */
    [MIPS_REG_D14_64] = { .reg_id = REG_FPR14, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f14" } },  /* d14_64 */
    [MIPS_REG_D15_64] = { .reg_id = REG_FPR15, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f15" } },  /* d15_64 */
    [MIPS_REG_D16_64] = { .reg_id = REG_FPR16, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f16" } },  /* d16_64 */
    [MIPS_REG_D17_64] = { .reg_id = REG_FPR17, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f17" } },  /* d17_64 */
    [MIPS_REG_D18_64] = { .reg_id = REG_FPR18, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f18" } },  /* d18_64 */
    [MIPS_REG_D19_64] = { .reg_id = REG_FPR19, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f19" } },  /* d19_64 */
    [MIPS_REG_D20_64] = { .reg_id = REG_FPR20, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f20" } },  /* d20_64 */
    [MIPS_REG_D21_64] = { .reg_id = REG_FPR21, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f21" } },  /* d21_64 */
    [MIPS_REG_D22_64] = { .reg_id = REG_FPR22, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f22" } },  /* d22_64 */
    [MIPS_REG_D23_64] = { .reg_id = REG_FPR23, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f23" } },  /* d23_64 */
    [MIPS_REG_D24_64] = { .reg_id = REG_FPR24, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f24" } },  /* d24_64 */
    [MIPS_REG_D25_64] = { .reg_id = REG_FPR25, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f25" } },  /* d25_64 */
    [MIPS_REG_D26_64] = { .reg_id = REG_FPR26, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f26" } },  /* d26_64 */
    [MIPS_REG_D27_64] = { .reg_id = REG_FPR27, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f27" } },  /* d27_64 */
    [MIPS_REG_D28_64] = { .reg_id = REG_FPR28, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f28" } },  /* d28_64 */
    [MIPS_REG_D29_64] = { .reg_id = REG_FPR29, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f29" } },  /* d29_64 */
    [MIPS_REG_D30_64] = { .reg_id = REG_FPR30, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f30" } },  /* d30_64 */
    [MIPS_REG_D31_64] = { .reg_id = REG_FPR31, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "f31" } },  /* d31_64 */
    [MIPS_REG_DSPOUTFLAG16_19] = { .reg_id = REG_FLAGS },  /* dspoutflag16_19 */
    [MIPS_REG_HI0_64] = { .reg_id = REG_ACCHI0, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "hi" } },  /* hi0_64 */
    [MIPS_REG_K0_64] = { .reg_id = REG_GPR26, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "k0" } },  /* k0_64 */
    [MIPS_REG_K1_64] = { .reg_id = REG_GPR27, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "k1" } },  /* k1_64 */
    [MIPS_REG_LO0_64] = { .reg_id = REG_ACC0, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "lo" } },  /* lo0_64 */
    [MIPS_REG_S0_64] = { .reg_id = REG_GPR16, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s0" } },  /* s0_64 */
    [MIPS_REG_S1_64] = { .reg_id = REG_GPR17, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s1" } },  /* s1_64 */
    [MIPS_REG_S2_64] = { .reg_id = REG_GPR18, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s2" } },  /* s2_64 */
    [MIPS_REG_S3_64] = { .reg_id = REG_GPR19, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s3" } },  /* s3_64 */
    [MIPS_REG_S4_64] = { .reg_id = REG_GPR20, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s4" } },  /* s4_64 */
    [MIPS_REG_S5_64] = { .reg_id = REG_GPR21, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s5" } },  /* s5_64 */
    [MIPS_REG_S6_64] = { .reg_id = REG_GPR22, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s6" } },  /* s6_64 */
    [MIPS_REG_S7_64] = { .reg_id = REG_GPR23, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "s7" } },  /* s7_64 */
    [MIPS_REG_T0_64] = { .reg_id = REG_GPR8, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t0" } },  /* t0_64 */
    [MIPS_REG_T1_64] = { .reg_id = REG_GPR9, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t1" } },  /* t1_64 */
    [MIPS_REG_T2_64] = { .reg_id = REG_GPR10, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t2" } },  /* t2_64 */
    [MIPS_REG_T3_64] = { .reg_id = REG_GPR11, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t3" } },  /* t3_64 */
    [MIPS_REG_T4_64] = { .reg_id = REG_GPR12, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t4" } },  /* t4_64 */
    [MIPS_REG_T5_64] = { .reg_id = REG_GPR13, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t5" } },  /* t5_64 */
    [MIPS_REG_T6_64] = { .reg_id = REG_GPR14, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t6" } },  /* t6_64 */
    [MIPS_REG_T7_64] = { .reg_id = REG_GPR15, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t7" } },  /* t7_64 */
    [MIPS_REG_T8_64] = { .reg_id = REG_GPR24, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t8" } },  /* t8_64 */
    [MIPS_REG_T9_64] = { .reg_id = REG_GPR25, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "t9" } },  /* t9_64 */
    [MIPS_REG_V0_64] = { .reg_id = REG_GPR2, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "v0" } },  /* v0_64 */
    [MIPS_REG_V1_64] = { .reg_id = REG_GPR3, .qemu_reg = { .feature = "org.gnu.gdb.mips.cpu", .name = "v1" } },  /* v1_64 */
    [MIPS_REG_COP0SEL_GUESTCTL0EXT] = { .reg_id = REG_SYS },  /* cop0sel_guestctl0ext */
};

/*
 * THE CANONICAL MIPS `nop` IS `sll $zero, $zero, 0`, AND THE CLASS IT
 * PUBLISHES IS RULED.
 *
 * MIPS gives `nop` no encoding of its own; the word is 0x00000000, which
 * is SLL with all three register/shift fields zero.  Capstone prints the
 * idiom and leaves `insn->id` at MIPS_INS_SLL -- it carries the idiom in
 * `alias_id`, and the AArch64 `ret` workaround in disas/capstone.c records
 * why that field may not be consulted -- so this row, correct for every
 * real shift, is also the row the nop lands on.
 *
 * WHICH CLASS IS RIGHT IS NOT AN OPEN QUESTION.  QEMU's own translator
 * separates the encoding (translate.c OPC_SLL, the rd == rt == rs == 0
 * arm), the identity table states it as
 * `translate_mips/OPC_SLL@00000000000000000000000000000000` -> GEN_OP_NOP,
 * and the R20 admission wave ADJUDICATED the move: exec96/ADM_OPCENC.txt
 * carries the row
 *
 *     MOVE mipsel 00000000 nop GEN_OP_SHL -> GEN_OP_NOP
 *                              the qualified SLL r0,r0,0 arm
 *
 * as one of its 20 counted-and-excluded moves.  The WIRE has published
 * GEN_OP_NOP since; this row had not caught up, so the two live
 * instruments disagreed on four bytes (FINDING 74-D(b)).
 *
 * WHY A `.refine` AND NOT A TABLE ROW.  A row is keyed on `insn->id`, and
 * `nop` and `sll $v0,$v0,1` share one.  A row cannot separate them; the
 * printed form can, which is exactly what `.refine` is for.
 *
 * AND WHY THIS DOES NOT BECOME A SECOND, QUIETER OPINION.  `.refine` is
 * taken from the WINNING classification, and on the correct path that is
 * the identity row -- which carries no refiner and already answers
 * GEN_OP_NOP.  This body runs only where the enum table is the answer,
 * i.e. `decode_id == 0`: bytes QEMU exported no identity for, which a
 * wrong-path walk reaches and which every offline consumer of this table
 * (isaxcheck's `fields` layer among them) sees for every encoding.  It
 * corrects the RETIRING key toward the ruled answer and cannot contradict
 * the winning one.  That is the same separation for which the aarch64
 * `b.<cc>` arm was DELETED from refine_alias_fields: an arm that only
 * re-derives what the identity row already gives has no business running
 * beside it.
 *
 * SCOPED BY THE MNEMONIC, and the neighbours prove the scope is not
 * over-wide: `ssnop` (0x40000000) and `ehb` (0xc0000000) are SLL r0,r0,sa
 * words too and Capstone gives each its OWN id, so both already reach
 * GEN_OP_NOP through their own rows and never enter this body; `sll
 * $v0,$v0,0` (0x00100200) and `sll $v0,$v0,1` (0x40100200) keep
 * GEN_OP_SHL.  Self-retiring in the same way f486209fa3's operand repair
 * is: a Capstone that stops printing the alias stops reaching this body.
 *
 * The register sets are NOT touched here.  f486209fa3 already restored
 * them at the boundary (RD{r0} WR{r0}); what was left was the class.
 */
static void refine_mips_nop_alias(
    const struct qemu_plugin_insn_info *info, InsnFields *f)
{
    if (info && !strcmp(info->mnemonic, "nop")) {
        f->opcode = GEN_OP_NOP;
    }
}

/*
 * `mips_insn_class[]` STOOD HERE, AND IS RETIRED (ruling R14).
 *
 * One row per Capstone instruction id, carrying the opcode,
 * branch class, flags, `.refine`, `.dep_refine` and the lane pair.
 * It was the wire's classification key until QEMU's own decode
 * identity replaced it, and after that it answered only where the
 * identity said nothing.  `enumocc.py` counted that population
 * over the whole enumerated encoding space -- four ISAs, wp0 and
 * wp16 -- and read `ENUM-OCCUPANCY total=0 key=STATED`.
 *
 * WHAT STAYS IN THIS FILE, and why it is not the table: the
 * Capstone arch/mode derivation, the register-classification
 * table, the address canonicaliser, the flags mapper and the
 * per-instance `.refine` callbacks.  The refiners in particular
 * are LIVE CODE ON THE IDENTITY KEY -- champsim_tracer_qemu_ident_
 * aarch64.h alone names refine_arm64_ldst_access on 218 rows --
 * so they retire with the operand walk, not with the table.
 */

#endif /* CHAMPSIM_TRACER_MNEMONICS_MIPS_H */
