#ifndef CHAMPSIM_TRACER_QEMU_REGS_RISCV_H
#define CHAMPSIM_TRACER_QEMU_REGS_RISCV_H

/*
 * QEMU-indexed register table for riscv -- auto-generated by
 * champsim_tracer_mnemonic_audit.py --qemu-regs.  Do not hand-edit a row.
 *
 * One row per register in QEMU's GDB-stub namespace -- the
 * namespace qemu_plugin_get_registers() reports -- sorted by
 * (feature, name) so a consumer can bisect.  This is the
 * authority for what generic dependency slot a register is;
 * the Capstone-keyed table is a route to these rows and is
 * cross-checked against them at install.
 *
 * .tier says whether the Capstone key can reach the row:
 *   QREG_ROUTED   at least one Capstone register id maps here
 *   QREG_UNNAMED  QEMU carries the register and Capstone's enum
 *                 has no id for it, so no Capstone-fed operand
 *                 can ever name it.  These rows are reachable
 *                 only by QEMU identity.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * Author: Maccoy Merrell
 */

/* riscv: 104 QEMU registers, 103 reachable from
 * Capstone, 1 reachable only by QEMU identity,
 * 103 carrying a generic id. */
static const QemuRegRow qemu_regs_riscv[] = {
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a0", .reg_id = REG_GPR10, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a1", .reg_id = REG_GPR11, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a2", .reg_id = REG_GPR12, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a3", .reg_id = REG_GPR13, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a4", .reg_id = REG_GPR14, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a5", .reg_id = REG_GPR15, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a6", .reg_id = REG_GPR16, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "a7", .reg_id = REG_GPR17, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "fp", .reg_id = REG_FP_REG, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "gp", .reg_id = REG_GPR3, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "pc", .reg_id = REG_NONE, .cap_rows = 0, .tier = QREG_UNNAMED },
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "ra", .reg_id = REG_LR, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s1", .reg_id = REG_GPR9, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s10", .reg_id = REG_GPR26, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s11", .reg_id = REG_GPR27, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s2", .reg_id = REG_GPR18, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s3", .reg_id = REG_GPR19, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s4", .reg_id = REG_GPR20, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s5", .reg_id = REG_GPR21, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s6", .reg_id = REG_GPR22, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s7", .reg_id = REG_GPR23, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s8", .reg_id = REG_GPR24, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "s9", .reg_id = REG_GPR25, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "sp", .reg_id = REG_SP, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "t0", .reg_id = REG_GPR5, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "t1", .reg_id = REG_GPR6, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "t2", .reg_id = REG_GPR7, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "t3", .reg_id = REG_GPR28, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "t4", .reg_id = REG_GPR29, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "t5", .reg_id = REG_GPR30, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "t6", .reg_id = REG_GPR31, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "tp", .reg_id = REG_GPR4, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.cpu", .name = "zero", .reg_id = REG_ZERO, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.csr", .name = "fflags", .reg_id = REG_FCSR, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.csr", .name = "frm", .reg_id = REG_FCSR, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.csr", .name = "vl", .reg_id = REG_VCTRL, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.csr", .name = "vlenb", .reg_id = REG_SYSID, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.csr", .name = "vtype", .reg_id = REG_VCTRL, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.csr", .name = "vxrm", .reg_id = REG_FCSR, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.csr", .name = "vxsat", .reg_id = REG_FCSR, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa0", .reg_id = REG_FPR10, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa1", .reg_id = REG_FPR11, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa2", .reg_id = REG_FPR12, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa3", .reg_id = REG_FPR13, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa4", .reg_id = REG_FPR14, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa5", .reg_id = REG_FPR15, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa6", .reg_id = REG_FPR16, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fa7", .reg_id = REG_FPR17, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs0", .reg_id = REG_FPR8, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs1", .reg_id = REG_FPR9, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs10", .reg_id = REG_FPR26, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs11", .reg_id = REG_FPR27, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs2", .reg_id = REG_FPR18, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs3", .reg_id = REG_FPR19, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs4", .reg_id = REG_FPR20, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs5", .reg_id = REG_FPR21, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs6", .reg_id = REG_FPR22, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs7", .reg_id = REG_FPR23, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs8", .reg_id = REG_FPR24, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "fs9", .reg_id = REG_FPR25, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft0", .reg_id = REG_FPR0, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft1", .reg_id = REG_FPR1, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft10", .reg_id = REG_FPR30, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft11", .reg_id = REG_FPR31, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft2", .reg_id = REG_FPR2, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft3", .reg_id = REG_FPR3, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft4", .reg_id = REG_FPR4, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft5", .reg_id = REG_FPR5, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft6", .reg_id = REG_FPR6, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft7", .reg_id = REG_FPR7, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft8", .reg_id = REG_FPR28, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.fpu", .name = "ft9", .reg_id = REG_FPR29, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v0", .reg_id = REG_VEC0, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v1", .reg_id = REG_VEC1, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v10", .reg_id = REG_VEC10, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v11", .reg_id = REG_VEC11, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v12", .reg_id = REG_VEC12, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v13", .reg_id = REG_VEC13, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v14", .reg_id = REG_VEC14, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v15", .reg_id = REG_VEC15, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v16", .reg_id = REG_VEC16, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v17", .reg_id = REG_VEC17, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v18", .reg_id = REG_VEC18, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v19", .reg_id = REG_VEC19, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v2", .reg_id = REG_VEC2, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v20", .reg_id = REG_VEC20, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v21", .reg_id = REG_VEC21, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v22", .reg_id = REG_VEC22, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v23", .reg_id = REG_VEC23, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v24", .reg_id = REG_VEC24, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v25", .reg_id = REG_VEC25, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v26", .reg_id = REG_VEC26, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v27", .reg_id = REG_VEC27, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v28", .reg_id = REG_VEC28, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v29", .reg_id = REG_VEC29, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v3", .reg_id = REG_VEC3, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v30", .reg_id = REG_VEC30, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v31", .reg_id = REG_VEC31, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v4", .reg_id = REG_VEC4, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v5", .reg_id = REG_VEC5, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v6", .reg_id = REG_VEC6, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v7", .reg_id = REG_VEC7, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v8", .reg_id = REG_VEC8, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.riscv.vector", .name = "v9", .reg_id = REG_VEC9, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
};

static const size_t qemu_regs_riscv_count =
    sizeof(qemu_regs_riscv) / sizeof(qemu_regs_riscv[0]);

#endif /* CHAMPSIM_TRACER_QEMU_REGS_RISCV_H */
