#ifndef CHAMPSIM_TRACER_QEMU_REGS_MIPS_H
#define CHAMPSIM_TRACER_QEMU_REGS_MIPS_H

/*
 * QEMU-indexed register table for mips -- auto-generated by
 * champsim_tracer_mnemonic_audit.py --qemu-regs.  Do not hand-edit a row.
 *
 * One row per register in QEMU's GDB-stub namespace -- the
 * namespace qemu_plugin_get_registers() reports -- sorted by
 * (feature, name) so a consumer can bisect.  This is the
 * authority for what generic dependency slot a register is;
 * the Capstone-keyed table is a route to these rows and is
 * cross-checked against them at install.
 *
 * .tier says whether the Capstone key can reach the row:
 *   QREG_ROUTED   at least one Capstone register id maps here
 *   QREG_UNNAMED  QEMU carries the register and Capstone's enum
 *                 has no id for it, so no Capstone-fed operand
 *                 can ever name it.  These rows are reachable
 *                 only by QEMU identity.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * Author: Maccoy Merrell
 */

/* mips: 73 QEMU registers, 72 reachable from
 * Capstone, 1 reachable only by QEMU identity,
 * 72 carrying a generic id. */
static const QemuRegRow qemu_regs_mips[] = {
    { .feature = "org.gnu.gdb.mips.cpu", .name = "a0", .reg_id = REG_GPR4, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "a1", .reg_id = REG_GPR5, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "a2", .reg_id = REG_GPR6, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "a3", .reg_id = REG_GPR7, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "at", .reg_id = REG_GPR1, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "badvaddr", .reg_id = REG_SYSEXC, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "cause", .reg_id = REG_SYSEXC, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f0", .reg_id = REG_FPR0, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f1", .reg_id = REG_FPR1, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f10", .reg_id = REG_FPR10, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f11", .reg_id = REG_FPR11, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f12", .reg_id = REG_FPR12, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f13", .reg_id = REG_FPR13, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f14", .reg_id = REG_FPR14, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f15", .reg_id = REG_FPR15, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f16", .reg_id = REG_FPR16, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f17", .reg_id = REG_FPR17, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f18", .reg_id = REG_FPR18, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f19", .reg_id = REG_FPR19, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f2", .reg_id = REG_FPR2, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f20", .reg_id = REG_FPR20, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f21", .reg_id = REG_FPR21, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f22", .reg_id = REG_FPR22, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f23", .reg_id = REG_FPR23, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f24", .reg_id = REG_FPR24, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f25", .reg_id = REG_FPR25, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f26", .reg_id = REG_FPR26, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f27", .reg_id = REG_FPR27, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f28", .reg_id = REG_FPR28, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f29", .reg_id = REG_FPR29, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f3", .reg_id = REG_FPR3, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f30", .reg_id = REG_FPR30, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f31", .reg_id = REG_FPR31, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f4", .reg_id = REG_FPR4, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f5", .reg_id = REG_FPR5, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f6", .reg_id = REG_FPR6, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f7", .reg_id = REG_FPR7, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f8", .reg_id = REG_FPR8, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "f9", .reg_id = REG_FPR9, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "fcr0", .reg_id = REG_SYSID, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "fcr31", .reg_id = REG_FCSR, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "fp", .reg_id = REG_NONE, .cap_rows = 0, .tier = QREG_UNNAMED },
    { .feature = "org.gnu.gdb.mips.cpu", .name = "gp", .reg_id = REG_GPR28, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "hi", .reg_id = REG_ACCHI0, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "k0", .reg_id = REG_GPR26, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "k1", .reg_id = REG_GPR27, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "lo", .reg_id = REG_ACC0, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "pc", .reg_id = REG_IP, .cap_rows = 1, .tier = QREG_ROUTED },  /* 1 capstone row */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "ra", .reg_id = REG_LR, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s0", .reg_id = REG_GPR16, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s1", .reg_id = REG_GPR17, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s2", .reg_id = REG_GPR18, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s3", .reg_id = REG_GPR19, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s4", .reg_id = REG_GPR20, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s5", .reg_id = REG_GPR21, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s6", .reg_id = REG_GPR22, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s7", .reg_id = REG_GPR23, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "s8", .reg_id = REG_FP_REG, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "sp", .reg_id = REG_SP, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "status", .reg_id = REG_SYSEXC, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t0", .reg_id = REG_GPR8, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t1", .reg_id = REG_GPR9, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t2", .reg_id = REG_GPR10, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t3", .reg_id = REG_GPR11, .cap_rows = 4, .tier = QREG_ROUTED },  /* 4 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t4", .reg_id = REG_GPR12, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t5", .reg_id = REG_GPR13, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t6", .reg_id = REG_GPR14, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t7", .reg_id = REG_GPR15, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t8", .reg_id = REG_GPR24, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "t9", .reg_id = REG_GPR25, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "v0", .reg_id = REG_GPR2, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "v1", .reg_id = REG_GPR3, .cap_rows = 2, .tier = QREG_ROUTED },  /* 2 capstone rows */
    { .feature = "org.gnu.gdb.mips.cpu", .name = "zero", .reg_id = REG_ZERO, .cap_rows = 3, .tier = QREG_ROUTED },  /* 3 capstone rows */
};

static const size_t qemu_regs_mips_count =
    sizeof(qemu_regs_mips) / sizeof(qemu_regs_mips[0]);

#endif /* CHAMPSIM_TRACER_QEMU_REGS_MIPS_H */
