#!/usr/bin/env python3
"""Generate encblob.S: the encodings the CPL0 probe will execute.

Rows listed in skip.txt are omitted.  A CPL0 probe really can execute HLT or
reprogram CR0, so an encoding that wedges the machine is named by the hex the
probe printed before running it and is retried nowhere -- it is carried as its
own measured verdict instead.
"""
import os, sys
src = sys.argv[1] if len(sys.argv) > 1 else 'reach_in.hex'
hexes = [h.strip() for h in open(src) if h.strip()]
skip = set(open('skip.txt').read().split()) if os.path.exists('skip.txt') else set()
sel = [h for h in hexes if h not in skip]
with open('encblob.S', 'w') as f:
    f.write('/* GENERATED by mkblob.py -- do not edit */\n'
            '    .section .rodata\n    .align 16\n    .globl enc_blob\nenc_blob:\n')
    for h in sel:
        b = [h[i:i + 2] for i in range(0, len(h), 2)]
        assert len(b) <= 15, h
        f.write('    .byte %d' % len(b) + ''.join(',0x%s' % x for x in b) +
                ',0' * (15 - len(b)) + '\n')
    f.write('    .globl enc_count\n    .align 8\nenc_count: .quad %d\n' % len(sel))
sys.stderr.write('blob rows %d, skipped %d\n' % (len(sel), len(skip)))
