"""
aarch64 guests whose WRONG PATH is worth measuring.

The correct-path probe set (``../probes/mkprobes_aarch64.py``) covers the ISA
classes an execution reference had never seen, but it covers them on the
CORRECT path: most of those probes are straight-line, so they kick no excursion
at all and the wrong-path leg sees nothing from them.  An axis with no instance
of its fact in any excursion cannot be proven to fire, and an unfirable axis
agrees for ever -- which is exactly the shape the riscv64 leg's negative
control caught, and why ``probes_wp.py`` had to exist there too.

Every class below therefore sits in the SHADOW of a conditional branch, which
is where the tracer's wrong-path walker goes.  As in the correct-path set, the
data lives in a ``.data`` arena at a FIXED virtual address and the probes never
touch the stack: gem5's SE-mode process loader and qemu-user lay the stack out
differently, so an address derived from SP would differ between the two runs
for reasons that have nothing to do with either tool.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CC = 'aarch64-linux-gnu-gcc'

HEAD = """\
// GENERATED by probes_wp_a64.py -- ARC 3 aarch64 wrong-path probe
.section .data
.balign 64
.globl arena
arena:
"""

#: Straight-line work between a shadow and the exit.  Without it the walker
#: runs off the end of .text within a couple of blocks and gem5 -- whose SE
#: mode turns the guest's own `svc` into a process exit -- can say nothing
#: about the rest, so the tail of every excursion would be a GEM5-LIMIT the
#: probe itself manufactured.  Filler converts those rows into COMPARED
#: instructions, which is the whole point of choosing the guest.
def filler(n=40, reg=19):
    out = []
    for i in range(n):
        out.append('  add  x%d, x%d, #%d' % (reg, reg, (i % 15) + 1))
        out.append('  eor  x%d, x%d, #%d' % (reg, reg, 1 << (i % 12)))
    return '\n'.join(out) + '\n'


TAIL = """
.globl done
done:
  mov  x8, #93
  mov  x0, #0
  svc  #0
"""

PRO = """
.section .text
.globl _start
_start:
  adrp x20, arena
  add  x20, x20, :lo12:arena
"""


def arena(n=192, seed=0x9E37):
    out, v = [], seed
    for _ in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .quad 0x%016x' % v)
    return '\n'.join(out) + '\n'


PROBES = {}

# The loop is taken nine times, so every excursion the walker kicks off the
# `b.lt` runs the FALL-THROUGH -- which is where every memory, FP and vector
# class below sits.  SUB-WORD loads and stores are deliberate: a width the
# wire states wrongly is invisible on a full-width access, and `memop-width`
# had no firing mutation on the riscv64 leg until such a probe existed.
PROBES['p_wpmem'] = """
  mov  x0, #0
  mov  x1, #10
  mov  x2, #0
loop:
  ldr  x3, [x20]
  add  x2, x2, x3
  add  x0, x0, #1
  cmp  x0, x1
  b.lt loop
shadow:
  ldrb w4, [x20, #8]
  ldrh w5, [x20, #10]
  ldr  w6, [x20, #12]
  ldrsb x7, [x20, #9]
  ldrsh x9, [x20, #14]
  ldrsw x10, [x20, #16]
  strb w4, [x20, #512]
  strh w5, [x20, #514]
  str  w6, [x20, #516]
  str  x7, [x20, #520]
  add  x22, x20, #512
  ldp  x11, x12, [x20, #24]
  stp  x11, x12, [x22, #16]
  ldr  q0, [x20, #40]
  ldr  q1, [x20, #56]
  add  v2.2d, v0.2d, v1.2d
  mul  v3.4s, v0.4s, v1.4s
  str  q3, [x20, #544]
  ldr  d4, [x20, #72]
  ldr  d5, [x20, #80]
  fadd d6, d4, d5
  fmul d7, d4, d5
  str  d6, [x20, #560]
  ldr  s8, [x20, #88]
  fcvt d9, s8
  str  s8, [x20, #568]
"""

# A second shape: the shadow is a chain of DEPENDENT loads, so the excursion's
# addresses depend on data the reconstruction had to get right.  A
# reconstruction that silently zeroed a register would produce a different
# address here and nowhere else -- which is what makes this the guest the
# injection control is worth running on.
PROBES['p_wpchain'] = """
  mov  x0, #0
  mov  x1, #8
  add  x21, x20, #256
chain:
  ldr  x3, [x21]
  and  x3, x3, #0x1f8
  add  x4, x20, x3
  ldr  x5, [x4]
  add  x0, x0, #1
  cmp  x0, x1
  b.lo chain
tail:
  ldr  x6, [x4]
  add  x7, x6, x5
  str  x7, [x20, #640]
  ldr  x9, [x20, #640]
  eor  x10, x9, x7
  str  x10, [x20, #648]
  ldr  w11, [x20, #648]
  str  w11, [x20, #656]
  ldr  x12, [x20, x3]
  str  x12, [x20, #664]
"""

# The shadow of a branch that is taken on the correct path, holding the forms
# whose DESTINATION SET is the interesting fact: conditional selects (R4 --
# both candidate sources recorded, the destination written whatever the
# condition did), a flag-setting compare, an exclusive pair and an LSE atomic.
PROBES['p_wpsel'] = """
  mov  x0, #0
  mov  x1, #6
  mov  x2, #0x55
  mov  x3, #0xaa
  add  x21, x20, #672
sloop:
  add  x0, x0, #1
  cmp  x0, x1
  b.lt sloop
sshadow:
  cmp  x2, x3
  csel  x4, x2, x3, eq
  csinc x5, x2, x3, ne
  csinv x6, x2, x3, mi
  csneg x7, x2, x3, ge
  cset  x9, lt
  ccmp  x2, x3, #0, eq
  ccmn  x2, x3, #4, ne
  adds  x10, x2, x3
  subs  x11, x2, x3
  ldxr  x12, [x21]
  add   x12, x12, #1
  stxr  w13, x12, [x21]
  ldadd x2, x14, [x21]
  swp   x3, x15, [x21]
  cas   x2, x3, [x21]
"""


# THE PANIC PROBE, kept deliberately.  gem5's SE mode aborts on AArch64 cache
# maintenance -- `dc cvau` ends in
# `src/sim/faults.cc:103: panic: ... Page table fault when accessing virtual
# address 0x400` -- so the correct-path leg excludes this class outright.  The
# wrong-path leg does NOT exclude it: an excursion that aborts the reference
# is exactly the case where the reference's silence must be NAMED rather than
# read as agreement, and a limit nobody has watched fire is a limit nobody can
# check.  The class stays in the run set and its rows carry gem5's own text.
# The cache block sits at the TARGET of a branch that is never taken on the
# correct path, so the correct-path run -- which is where the entry-state
# ground truth comes from -- never executes it and gem5 completes.  Only the
# INJECTED wrong-path run reaches it, which is precisely the arrangement that
# makes the reference's abort a measurement rather than a broken harness.
PROBES['p_wpcache'] = """
  mov  x0, #0
  mov  x1, #5
  add  x21, x20, #704
cloop:
  add  x0, x0, #1
  cmp  x0, #100
  b.gt cshadow
  cmp  x0, x1
  b.lt cloop
  b    cskip
cshadow:
  dc   cvau, x21
  ic   ivau, x21
  dc   civac, x21
  dsb  ish
  isb
  ldr  x2, [x21]
  add  x2, x2, #1
  str  x2, [x21]
cskip:
  ldr  x3, [x21]
  eor  x3, x3, #0xff
  str  x3, [x21, #8]
"""


def build(outdir, cc=CC):
    os.makedirs(outdir, exist_ok=True)
    made, failed = [], []
    for name, body in sorted(PROBES.items()):
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD + arena() + PRO + body + filler() + TAIL)
        elf = os.path.join(outdir, name)
        cmd = [cc, '-nostdlib', '-nostartfiles', '-static', '-no-pie',
               '-Wl,--build-id=none', '-march=armv8.4-a+lse', '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            failed.append((name, p.stdout.decode('utf-8', 'replace')))
        else:
            made.append(elf)
    return made, failed


if __name__ == '__main__':
    made, failed = build(sys.argv[1] if len(sys.argv) > 1
                         else os.path.join(HERE, 'build'))
    for n, err in failed:
        sys.stderr.write('FAILED %s\n%s\n' % (n, err))
    print('\n'.join(made))
    sys.exit(1 if failed else 0)
