"""
x86_64 guests whose WRONG PATH is worth measuring.

An axis with no instance of its fact in any excursion cannot be proven to
fire, and an unfirable axis agrees forever.  The correct-path probe sets in
this tree cover ISA classes on the CORRECT path and are mostly straight-line,
so they kick no excursion at all and the wrong-path leg sees nothing from
them.  These guests exist so the memory, flag, SSE and x87 axes have
wrong-path instances to be measured on: every class below sits in the SHADOW
of a conditional branch, which is exactly where the tracer's wrong-path walker
goes.

CONSTRAINTS EVERY PROBE OBEYS, AND WHY
======================================
* ``-nostdlib``, non-PIE, static.  gem5's SE-mode loader and qemu-user lay out
  the stack, the auxiliary vector and the environment differently, so any
  address derived from SP differs between the two for reasons that have
  nothing to do with either tool.  A link-time address does not, which is what
  makes ``memop-addr`` an exact-equality axis rather than a delta model.
* No stack traffic at all.  The reconstruction installs RSP from the wire, and
  the wire's RSP is qemu-user's stack -- an address the injected image never
  lays down.  A probe that pushed would be measuring the harness.
* The loop is taken several times, so the excursion the walker kicks off the
  conditional branch runs the FALL-THROUGH, which is where the classes sit.

Author: Maccoy Merrell.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

HEAD = """\
# GENERATED by probes_wp_x86.py -- ARC 3 x86_64 wrong-path probe
.section .data
.balign 64
.globl arena
arena:
"""

TAIL = """
.globl done
done:
  mov $60, %eax
  xor %edi, %edi
  syscall
"""


def arena(n=128, seed=0x51ED):
    out, v = [], seed
    for _i in range(n):
        v = (v * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        out.append('  .quad 0x%016x' % v)
    return '\n'.join(out) + '\n'


PROBES = {}

# Sub-word memory in the shadow.  A width the wire states wrongly is invisible
# on a full-width access, so 1-, 2-, 4- and 8-byte loads AND stores are all
# here -- and the 8- and 16-bit destination writes are the ones that read
# their own destination back, which is a fact the reference states and the
# tracer's source set is measured against.
PROBES['p_wpmem'] = """
.section .text
.globl _start
_start:
  movabs $arena, %r15
  mov  $10, %ecx
  xor  %rax, %rax
loop:
  mov  (%r15), %rdx
  add  %rdx, %rax
  dec  %rcx
  jnz  loop
shadow:
  movzbl 8(%r15), %ebx
  movzwl 10(%r15), %esi
  mov  12(%r15), %edi
  mov  16(%r15), %r8
  mov  24(%r15), %r9b
  mov  26(%r15), %r10w
  mov  %bl,  256(%r15)
  mov  %si,  258(%r15)
  mov  %edi, 260(%r15)
  mov  %r8,  264(%r15)
  movsbl 9(%r15), %r11d
  movswq 14(%r15), %r12
  movslq 20(%r15), %r13
  mov  %r12, 272(%r15)
  mov  %r13, 280(%r15)
  jmp  done
"""

# A dependent-load chain in the shadow: every address depends on data the
# reconstruction had to get right.  A reconstruction that silently zeroed a
# register would produce a different address HERE and nowhere else.
PROBES['p_wpchain'] = """
.section .text
.globl _start
_start:
  movabs $arena, %r15
  lea  512(%r15), %r14
  mov  $8, %ecx
  xor  %rax, %rax
chain:
  mov  (%r14), %rdx
  and  $0x1f8, %edx
  lea  (%r15,%rdx), %r13
  mov  (%r13), %rbx
  dec  %rcx
  jnz  chain
tail:
  mov  (%r13), %rsi
  add  %rbx, %rsi
  mov  %rsi, 320(%r15)
  mov  320(%r15), %rdi
  xor  %rsi, %rdi
  mov  %rdi, 328(%r15)
  and  $0x3f8, %edi
  lea  (%r15,%rdi), %r12
  mov  (%r12), %r11
  mov  %r11, 336(%r15)
  jmp  done
"""

# Flag producers and flag consumers in the shadow.  `adc`, `sbb`, `setcc` and
# `cmovcc` all READ the flags word; `inc` and `dec` write it only in part and
# therefore read it too (R4: a partial write also reads what it preserves).
# This is the probe the reg-src-set axis lives on.
PROBES['p_wpflag'] = """
.section .text
.globl _start
_start:
  movabs $arena, %r15
  mov  $6, %ecx
  xor  %rax, %rax
floop:
  mov  (%r15), %rdx
  add  %rdx, %rax
  dec  %rcx
  jnz  floop
fshadow:
  mov  32(%r15), %rbx
  mov  40(%r15), %rsi
  add  %rbx, %rsi
  adc  %rbx, %rdi
  sbb  %rsi, %r8
  inc  %r9
  dec  %r10
  cmp  %rbx, %rsi
  cmovb %rbx, %r11
  cmova %rsi, %r12
  seta %r13b
  setb %r14b
  bt   $3, %rbx
  adc  $0, %rax
  neg  %rsi
  not  %rbx
  mov  %rax, 384(%r15)
  jmp  done
"""

# SSE in the shadow: 128-bit loads and stores, packed and scalar arithmetic,
# and the moves between the integer and vector files.  A scalar op writes only
# the low half of its destination, which is the case the XMM-half rule names.
PROBES['p_wpsse'] = """
.section .text
.globl _start
_start:
  movabs $arena, %r15
  mov  $6, %ecx
  xor  %rax, %rax
sloop:
  mov  (%r15), %rdx
  add  %rdx, %rax
  dec  %rcx
  jnz  sloop
sshadow:
  movups 48(%r15), %xmm0
  movups 64(%r15), %xmm1
  paddq  %xmm1, %xmm0
  pxor   %xmm2, %xmm2
  por    %xmm0, %xmm2
  movaps %xmm0, %xmm3
  mulps  %xmm1, %xmm3
  addpd  %xmm1, %xmm0
  movq   %rax, %xmm4
  movq   %xmm3, %rbx
  addsd  %xmm1, %xmm4
  movups %xmm0, 448(%r15)
  movups %xmm3, 464(%r15)
  movq   %xmm4, 480(%r15)
  jmp  done
"""

# x87 in the shadow.  The x87 dataflow repair landed this arc, and until it
# did the dependency chain of these instructions was absent; reaching them
# here exercises code that had no execution reference at all.  Loads and
# stores are 32-, 64- and 80-bit so the memop-width axis has x87 instances.
PROBES['p_wpx87'] = """
.section .text
.globl _start
_start:
  movabs $arena, %r15
  mov  $6, %ecx
  xor  %rax, %rax
xloop:
  mov  (%r15), %rdx
  add  %rdx, %rax
  dec  %rcx
  jnz  xloop
xshadow:
  flds   96(%r15)
  fldl   104(%r15)
  fadd   %st(1), %st
  fmul   %st(1), %st
  fldl   112(%r15)
  fsub   %st(1), %st
  fstps  512(%r15)
  fstpl  520(%r15)
  fldl   120(%r15)
  fabs
  fchs
  fstpl  528(%r15)
  jmp  done
"""


def build(outdir, cc='gcc'):
    os.makedirs(outdir, exist_ok=True)
    made = []
    for name, body in sorted(PROBES.items()):
        src = os.path.join(outdir, name + '.S')
        with open(src, 'w') as fh:
            fh.write(HEAD)
            fh.write(arena())
            fh.write(body)
            fh.write(TAIL)
        elf = os.path.join(outdir, name)
        cmd = [cc, '-static', '-nostdlib', '-nostartfiles', '-no-pie',
               '-Wl,-e,_start', '-o', elf, src]
        p = subprocess.run(cmd, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        if p.returncode != 0:
            sys.stderr.write('FAILED %s:\n%s\n'
                             % (name, p.stdout.decode('utf-8', 'replace')))
            continue
        made.append(elf)
    return made


if __name__ == '__main__':
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'build')
    for e in build(out):
        print(e)
